const beans_data = [

  {
    id: "blackBeans",
    icon:"🫘", name:"Black Beans",
    desc:"Classic black bean dishes from soups and stews to tacos, rice bowls, and dips.",
    recipes:[
      {name:"Black Bean Soup",servings:"6 servings",ingredients:["2 cans black beans, drained","1 onion, diced","4 garlic cloves, minced","1 jalapeño, diced","1 red bell pepper, diced","4 cups vegetable broth","1 tsp cumin","1 tsp smoked paprika","½ tsp oregano","2 tbsp olive oil","Juice of 1 lime","Salt and pepper","Sour cream, avocado, and cilantro to serve"],prep:"Heat olive oil in a large pot. Cook onion, jalapeño, and bell pepper until soft. Add garlic and spices and cook 1 minute. Add beans and broth. Simmer 20 minutes. Blend half the soup and return to pot. Add lime juice. Season with salt and pepper."},
      {name:"Black Bean Tacos",servings:"4 servings",ingredients:["2 cans black beans, drained","1 onion, diced","3 garlic cloves","1 tsp cumin","1 tsp chili powder","½ tsp smoked paprika","2 tbsp olive oil","8 corn tortillas","Shredded cabbage, avocado, salsa, sour cream, cilantro, lime"],prep:"Heat olive oil in a skillet. Cook onion until soft. Add garlic and spices and cook 1 minute. Add black beans and a splash of water. Cook 5 minutes mashing some beans. Season with salt. Fill warm tortillas with bean mixture and toppings."},
      {name:"Black Beans and Rice",servings:"4 servings",ingredients:["2 cans black beans, drained","2 cups long grain white rice, cooked","1 onion, diced","4 garlic cloves","1 green bell pepper, diced","1 tsp cumin","1 tsp oregano","½ cup vegetable broth","2 tbsp olive oil","Salt and pepper","Fresh cilantro and lime"],prep:"Heat olive oil in a skillet. Cook onion and bell pepper until soft. Add garlic, cumin, and oregano. Add black beans and broth. Simmer 10 minutes until sauce thickens. Season with salt and pepper. Serve over steamed white rice with cilantro and lime."},
      {name:"Black Bean Burgers",servings:"4 servings",ingredients:["2 cans black beans, drained and dried","½ cup breadcrumbs","1 egg","3 garlic cloves, minced","1 tsp cumin","1 tsp smoked paprika","½ tsp chili powder","¼ cup fresh cilantro, chopped","Salt and pepper","Burger buns and toppings"],prep:"Mash black beans leaving some chunks for texture. Mix with breadcrumbs, egg, garlic, spices, and cilantro. Season with salt and pepper. Form into 4 patties. Refrigerate 30 minutes. Cook in a well-oiled skillet over medium heat 4 minutes per side. Serve on buns with desired toppings."},
      {name:"Cuban Black Beans",servings:"6 servings",ingredients:["500g dried black beans, soaked overnight","1 onion, diced","1 green bell pepper, diced","6 garlic cloves, minced","2 bay leaves","1 tsp cumin","1 tsp oregano","3 tbsp olive oil","3 tbsp red wine vinegar","1 tsp sugar","Salt and pepper","White rice to serve"],prep:"Cook soaked beans in fresh water with bay leaves until tender — about 1–1.5 hours. In a skillet cook onion, bell pepper, and garlic in olive oil until soft. Add cumin and oregano. Add a cup of cooked beans and mash. Return everything to the pot. Add vinegar and sugar. Simmer 20 minutes. Season with salt and pepper. Serve over white rice."},
      {name:"Black Bean Enchiladas",servings:"4 servings",ingredients:["2 cans black beans, drained","8 corn tortillas","2 cups enchilada sauce","2 cups shredded cheese","1 onion, diced","3 garlic cloves","1 tsp cumin","1 tsp chili powder","Sour cream, avocado, and cilantro to serve"],prep:"Preheat oven to 375F. Cook onion and garlic in oil. Add beans and spices. Cook 5 minutes. Dip tortillas in enchilada sauce. Fill with bean mixture and cheese. Roll up and place seam side down in a baking dish. Pour remaining sauce and cheese on top. Bake 20–25 minutes until bubbly."},
      {name:"Black Bean Chili",servings:"6 servings",ingredients:["3 cans black beans, drained","1 can (28oz) crushed tomatoes","1 onion, diced","4 garlic cloves","1 red bell pepper, diced","1 chipotle in adobo, minced","2 tbsp chili powder","1 tsp cumin","1 tsp smoked paprika","2 tbsp olive oil","Salt and pepper","Avocado, sour cream, and lime to serve"],prep:"Heat olive oil. Cook onion and bell pepper until soft. Add garlic, chipotle, and all spices and cook 1 minute. Add tomatoes and black beans. Simmer 25 minutes. Mash about a third of the beans for a thicker texture. Season with salt and pepper."},
      {name:"Black Bean Dip",servings:"6 servings",ingredients:["2 cans black beans, drained","4 garlic cloves, minced","Juice of 2 limes","2 tbsp olive oil","1 tsp cumin","1 tsp smoked paprika","½ tsp cayenne","Salt and pepper","Tortilla chips to serve","Sour cream, jalapeños, cilantro"],prep:"Blend black beans, garlic, lime juice, olive oil, cumin, paprika, and cayenne until smooth. Add a splash of water to reach desired consistency. Season with salt and pepper. Transfer to a serving bowl. Drizzle with olive oil. Top with sour cream, jalapeños, and cilantro. Serve with tortilla chips."},
      {name:"Black Bean Stuffed Peppers",servings:"4 servings",ingredients:["4 large bell peppers, tops cut off and seeded","2 cans black beans, drained","1 cup cooked rice","1 onion, diced","3 garlic cloves","1 cup corn kernels","1 tsp cumin","1 tsp chili powder","1½ cups shredded cheese","Salt and pepper"],prep:"Preheat oven to 375F. Cook onion and garlic in oil. Add beans, rice, corn, and spices. Season with salt and pepper. Fill peppers with bean mixture. Top with shredded cheese. Place in a baking dish with ¼ cup water. Cover and bake 30 minutes. Uncover and bake 15 more minutes until cheese is golden."},
      {name:"Black Bean Shakshuka",servings:"4 servings",ingredients:["1 can black beans, drained","1 can (28oz) crushed tomatoes","4 large eggs","1 onion, diced","4 garlic cloves","1 jalapeño, diced","1 tsp cumin","1 tsp smoked paprika","½ tsp cayenne","3 tbsp olive oil","Fresh cilantro and feta to serve"],prep:"Heat olive oil in a large skillet. Cook onion, jalapeño, and garlic until soft. Add spices. Add tomatoes and beans. Simmer 10 minutes. Make 4 wells in the sauce. Crack an egg into each well. Cover and cook 6–8 minutes until whites are set but yolks are still runny. Top with crumbled feta and fresh cilantro."},
      {name:"Black Bean Pasta",servings:"4 servings",ingredients:["400g pasta","1 can black beans, drained","1 can diced tomatoes","4 garlic cloves, minced","½ cup fresh basil","¼ cup olive oil","½ tsp red pepper flakes","Salt and pepper","Parmesan to serve"],prep:"Cook pasta until al dente. Reserve 1 cup pasta water. Heat olive oil in a skillet. Cook garlic and red pepper flakes 1 minute. Add tomatoes and beans. Simmer 5 minutes. Toss in drained pasta with a splash of pasta water. Add basil. Season with salt and pepper. Serve with Parmesan."},
      {name:"Frijoles Negros",servings:"6 servings",ingredients:["500g dried black beans, soaked overnight","1 onion, halved","6 garlic cloves","2 bay leaves","1 green bell pepper, halved","1 tsp cumin","1 tsp oregano","3 tbsp olive oil","Salt","Sofrito: ½ onion diced, ½ bell pepper diced, 4 garlic cloves, tomato paste"],prep:"Cook soaked beans with onion halves, garlic, bay leaves, and bell pepper in fresh water until tender — 1–1.5 hours. Make sofrito by cooking diced onion, bell pepper, and garlic in olive oil until soft. Add tomato paste and cook 2 minutes. Stir sofrito into beans. Add cumin and oregano. Simmer 20 minutes. Season with salt."},
      {name:"Black Bean Breakfast Bowl",servings:"2 servings",ingredients:["1 can black beans, drained","4 large eggs","1 avocado, sliced","1 cup cherry tomatoes, halved","¼ cup salsa","½ cup shredded cheese","1 tsp cumin","Salt and pepper","Hot sauce and cilantro to serve"],prep:"Season black beans with cumin, salt, and pepper. Warm in a skillet. Fry or scramble eggs in a separate pan. Layer beans in bowls. Top with eggs, avocado, cherry tomatoes, salsa, and shredded cheese. Add hot sauce and fresh cilantro."},
      {name:"Black Bean Quesadillas",servings:"4 servings",ingredients:["1 can black beans, drained and mashed","4 large flour tortillas","1½ cups shredded Monterey Jack cheese","1 jalapeño, finely diced","½ red onion, finely diced","¼ cup fresh cilantro","1 tsp cumin","Salt and pepper","Salsa and sour cream to serve"],prep:"Mix mashed beans with jalapeño, onion, cilantro, cumin, salt, and pepper. Spread bean mixture on half of each tortilla. Top with shredded cheese. Fold tortillas over. Cook in a dry skillet over medium heat 2–3 minutes per side until golden and cheese is melted. Slice and serve with salsa and sour cream."},
      {name:"Black Bean and Corn Salad",servings:"4 servings",ingredients:["1 can black beans, drained","1 cup corn kernels","1 red bell pepper, diced","½ red onion, finely diced","1 avocado, diced","¼ cup fresh cilantro","Dressing: 3 tbsp lime juice, 2 tbsp olive oil, 1 tsp cumin, 1 tsp chili powder, salt and pepper"],prep:"Combine black beans, corn, bell pepper, and red onion. Whisk dressing ingredients. Toss salad with dressing. Add avocado and cilantro gently. Serve at room temperature."}
    ]
  },

  {
    id: "chickpeas",
    icon:"🟤", name:"Chickpeas",
    desc:"Hummus, chana masala, roasted chickpeas, salads, soups, and more.",
    recipes:[
      {name:"Classic Hummus",servings:"6 servings",ingredients:["2 cans chickpeas, drained — reserve liquid","¼ cup tahini","Juice of 2 lemons","3 garlic cloves","½ tsp cumin","3 tbsp extra virgin olive oil","Salt","Ice water to thin","Paprika and olive oil to garnish"],prep:"Blend chickpeas, tahini, lemon juice, garlic, and cumin until very smooth — about 3–4 minutes. Add ice water a tablespoon at a time until very creamy and light. Season generously with salt. Transfer to a bowl. Drizzle with olive oil and sprinkle with paprika."},
      {name:"Chana Masala",servings:"4 servings",ingredients:["2 cans chickpeas, drained","1 onion, finely diced","4 garlic cloves, minced","1 tbsp fresh ginger","1 can crushed tomatoes","2 tsp garam masala","1 tsp cumin","1 tsp coriander","1 tsp turmeric","½ tsp cayenne","3 tbsp oil","Juice of 1 lemon","Fresh cilantro","Salt","Basmati rice or naan to serve"],prep:"Heat oil in a large pot. Cook onion until deeply golden — about 15 minutes. Add garlic and ginger and cook 2 minutes. Add all spices and cook 1 minute. Add tomatoes and simmer 10 minutes. Add chickpeas and simmer 20 minutes until sauce thickens. Add lemon juice. Season with salt. Garnish with cilantro."},
      {name:"Roasted Chickpeas",servings:"4 servings",ingredients:["2 cans chickpeas, drained and patted completely dry","3 tbsp olive oil","1 tsp smoked paprika","1 tsp garlic powder","1 tsp cumin","½ tsp cayenne","Salt"],prep:"Preheat oven to 425F. Dry chickpeas very thoroughly — moisture prevents crispiness. Spread on a baking sheet. Drizzle with olive oil and all spices. Toss well. Roast 30–40 minutes shaking pan every 10 minutes until deeply golden and very crispy. Cool on the pan — they crisp more as they cool."},
      {name:"Chickpea Curry",servings:"4 servings",ingredients:["2 cans chickpeas, drained","1 onion, diced","4 garlic cloves","1 tbsp fresh ginger","1 can coconut milk","1 can crushed tomatoes","2 tbsp curry powder","1 tsp garam masala","1 tsp turmeric","3 tbsp oil","Salt","Fresh cilantro and rice to serve"],prep:"Cook onion in oil until golden. Add garlic and ginger and cook 2 minutes. Add curry powder, garam masala, and turmeric and cook 1 minute. Add tomatoes and simmer 10 minutes. Add coconut milk and chickpeas. Simmer 20 minutes until sauce is thick. Season with salt. Garnish with cilantro."},
      {name:"Falafel",servings:"~20 pieces",ingredients:["2 cans chickpeas, drained (or 500g dried soaked overnight — preferred)","1 onion, roughly chopped","4 garlic cloves","1 cup fresh parsley and cilantro","1 tsp cumin","1 tsp coriander","½ tsp cayenne","1 tsp baking powder","3 tbsp flour","Salt","Oil for frying","Pita, tahini, and salad to serve"],prep:"Process chickpeas, onion, garlic, herbs, and spices in a food processor until a coarse mixture forms — do not blend smooth. Add baking powder and flour. Season with salt. Refrigerate 1 hour. Shape into balls or discs. Deep fry at 350F for 3–4 minutes until golden and crispy. Drain on paper towels. Serve in pita with tahini sauce and fresh salad."},
      {name:"Chickpea Salad",servings:"4 servings",ingredients:["2 cans chickpeas, drained","1 cucumber, diced","1 cup cherry tomatoes, halved","½ red onion, finely diced","¼ cup Kalamata olives","100g feta, crumbled","¼ cup fresh parsley","Dressing: 3 tbsp olive oil, 2 tbsp lemon juice, 1 tsp cumin, 1 tsp sumac, salt and pepper"],prep:"Combine chickpeas, cucumber, tomatoes, onion, olives, and parsley. Whisk dressing and toss. Top with crumbled feta. Let sit 10 minutes before serving."},
      {name:"Chickpea and Spinach Stew",servings:"4 servings",ingredients:["2 cans chickpeas, drained","4 cups fresh spinach","1 onion, diced","4 garlic cloves","1 can crushed tomatoes","1 tsp smoked paprika","1 tsp cumin","½ tsp turmeric","3 tbsp olive oil","Salt and pepper","Crusty bread to serve"],prep:"Heat olive oil in a large pot. Cook onion until soft. Add garlic and all spices and cook 1 minute. Add tomatoes and simmer 10 minutes. Add chickpeas and simmer 15 minutes. Add spinach and stir until wilted. Season with salt and pepper."},
      {name:"Chickpea Tikka Masala",servings:"4 servings",ingredients:["2 cans chickpeas, drained","1 onion, diced","4 garlic cloves","1 tbsp ginger","1 can (28oz) crushed tomatoes","1 cup heavy cream","2 tsp garam masala","1 tsp cumin","1 tsp coriander","1 tsp paprika","3 tbsp butter","Salt","Fresh cilantro and naan to serve"],prep:"Cook onion in butter until golden. Add garlic and ginger and cook 2 minutes. Add all spices and cook 1 minute. Add tomatoes and simmer 15 minutes. Blend sauce until smooth. Return to pan. Add cream and simmer 5 minutes. Add chickpeas and simmer 10 more minutes. Season with salt."},
      {name:"Aquafaba Meringues",servings:"~20 meringues",ingredients:["¾ cup aquafaba — liquid from 1 can of chickpeas","½ cup granulated sugar","½ tsp cream of tartar","1 tsp vanilla extract"],prep:"Preheat oven to 225F. Add cream of tartar to aquafaba. Beat with an electric mixer on medium until soft peaks form — about 5 minutes. Increase to high and gradually add sugar one tablespoon at a time. Continue beating until stiff glossy peaks form — about 10 minutes. Add vanilla. Pipe onto parchment-lined baking sheets. Bake 1.5–2 hours until dry and crisp."},
      {name:"Moroccan Chickpea Tagine",servings:"4 servings",ingredients:["2 cans chickpeas, drained","1 onion, diced","4 garlic cloves","1 can diced tomatoes","1 cup vegetable broth","½ cup dried apricots","¼ cup raisins","2 tsp ras el hanout","1 tsp cinnamon","1 tsp cumin","3 tbsp olive oil","Salt and pepper","Cilantro and toasted almonds","Couscous to serve"],prep:"Heat olive oil in a tagine or Dutch oven. Cook onion until golden. Add garlic and spices and cook 1 minute. Add tomatoes, broth, chickpeas, apricots, and raisins. Cover and simmer 30 minutes until sauce is thick and fragrant. Season with salt and pepper. Garnish with cilantro and toasted almonds. Serve over couscous."},
      {name:"Chickpea Soup",servings:"6 servings",ingredients:["2 cans chickpeas, drained","1 onion, diced","3 carrots, diced","3 celery stalks, diced","4 garlic cloves","1 can diced tomatoes","6 cups vegetable broth","1 tsp cumin","1 tsp smoked paprika","3 tbsp olive oil","Fresh parsley","Salt and pepper"],prep:"Heat olive oil in a large pot. Cook onion, carrots, and celery until soft. Add garlic and spices and cook 1 minute. Add tomatoes, broth, and chickpeas. Simmer 25 minutes. Mash some chickpeas for a thicker texture. Season with salt and pepper."},
      {name:"Chickpea Shawarma Bowl",servings:"4 servings",ingredients:["2 cans chickpeas, drained","2 tsp cumin, 1 tsp coriander, 1 tsp turmeric, 1 tsp smoked paprika, ½ tsp cinnamon, ½ tsp cayenne","3 tbsp olive oil","2 cups cooked rice or quinoa","Hummus, tzatziki, cucumber, tomatoes, pickled onion, fresh parsley"],prep:"Toss chickpeas with shawarma spices and olive oil. Roast at 425F for 25–30 minutes until crispy. Assemble bowls with rice or quinoa. Top with roasted chickpeas, hummus, tzatziki, diced cucumber, tomatoes, pickled onion, and fresh parsley."},
      {name:"Chickpea Fritters",servings:"4 servings",ingredients:["1 can chickpeas, drained and mashed","½ cup flour","1 egg","½ onion, grated","2 garlic cloves, minced","¼ cup fresh parsley, chopped","1 tsp cumin","½ tsp smoked paprika","Salt and pepper","Oil for frying","Yogurt dipping sauce to serve"],prep:"Mash chickpeas until mostly smooth with some texture. Mix with flour, egg, onion, garlic, parsley, cumin, paprika, salt, and pepper. Form into patties. Heat oil in a skillet over medium heat. Cook fritters 3 minutes per side until golden and cooked through. Serve with garlic yogurt sauce."},
      {name:"Chickpea Pasta",servings:"4 servings",ingredients:["400g short pasta","1 can chickpeas, drained","4 garlic cloves, thinly sliced","1 can diced tomatoes","½ cup fresh basil","¼ cup olive oil","½ tsp red pepper flakes","Salt and pepper","Parmesan to serve"],prep:"Cook pasta until al dente. Reserve 1 cup pasta water. Heat olive oil in a large skillet. Cook garlic and red pepper flakes 1 minute. Add tomatoes and chickpeas. Simmer 10 minutes. Add drained pasta and toss with a splash of pasta water. Add basil. Season and serve with Parmesan."},
      {name:"Chickpea Stew with Roasted Vegetables",servings:"4 servings",ingredients:["2 cans chickpeas, drained","1 zucchini, cubed and roasted","1 red bell pepper, cubed and roasted","1 cup cherry tomatoes, roasted","1 onion, diced","4 garlic cloves","1 cup vegetable broth","2 tsp smoked paprika","1 tsp cumin","3 tbsp olive oil","Salt and pepper","Fresh parsley"],prep:"Roast zucchini, bell pepper, and tomatoes at 400F with olive oil, salt, and pepper for 25 minutes. Cook onion and garlic in olive oil in a large pot. Add smoked paprika and cumin. Add broth and chickpeas. Simmer 15 minutes. Add roasted vegetables and simmer 5 more minutes. Season with salt and pepper."}
    ]
  },

  {
    id: "kidneyBeans",
    icon:"🟥", name:"Red & Kidney Beans",
    desc:"Red beans and rice, kidney bean chili, stews, and classic dishes.",
    recipes:[
      {name:"Red Beans and Rice",servings:"6 servings",ingredients:["500g dried red kidney beans, soaked overnight","300g andouille sausage, sliced","1 onion, diced","3 celery stalks, diced","1 green bell pepper, diced","4 garlic cloves, minced","2 bay leaves","1 tsp thyme","1 tsp smoked paprika","Cajun seasoning","Salt and pepper","Steamed white rice, green onions and hot sauce"],prep:"Cook soaked beans in fresh water until almost tender — about 1 hour. In a large pot cook sausage until browned. Remove. Cook onion, celery, and bell pepper in sausage fat until soft. Add garlic, thyme, paprika, and Cajun seasoning. Add beans with their cooking liquid and bay leaves. Simmer 1 hour. Mash some beans against the side for a creamy thick texture. Add sausage back. Season with salt and pepper. Serve over white rice."},
      {name:"Kidney Bean Chili",servings:"6 servings",ingredients:["2 cans kidney beans, drained","700g ground beef","1 can (28oz) crushed tomatoes","1 onion, diced","4 garlic cloves","1 red bell pepper, diced","2 tbsp chili powder","1 tsp cumin","1 tsp smoked paprika","½ tsp cayenne","2 tbsp olive oil","Salt and pepper"],prep:"Brown ground beef and drain excess fat. Add onion, bell pepper, and garlic and cook until soft. Add all spices and cook 1 minute. Add tomatoes and kidney beans. Simmer 30–40 minutes until thick. Season with salt and pepper."},
      {name:"Rajma",servings:"4 servings",ingredients:["2 cans kidney beans, drained","1 onion, finely diced","4 garlic cloves, minced","1 tbsp fresh ginger","1 can crushed tomatoes","1 tsp garam masala","1 tsp cumin","1 tsp coriander","1 tsp turmeric","½ tsp cayenne","3 tbsp oil","Salt","Basmati rice and fresh cilantro to serve"],prep:"Cook onion in oil until deeply golden — about 15 minutes. Add garlic and ginger and cook 2 minutes. Add all spices and cook 1 minute. Add tomatoes and simmer 15 minutes. Add kidney beans and a cup of water. Simmer 20 minutes until sauce is very thick. Season with salt. Serve over basmati rice."},
      {name:"Kidney Bean Soup",servings:"6 servings",ingredients:["2 cans kidney beans, drained","1 onion, diced","3 carrots, diced","3 celery stalks, diced","4 garlic cloves","1 can diced tomatoes","6 cups vegetable broth","1 tsp Italian seasoning","3 tbsp olive oil","Salt, pepper, and red pepper flakes","Parmesan and crusty bread to serve"],prep:"Heat olive oil in a large pot. Cook onion, carrots, and celery until soft. Add garlic and Italian seasoning and cook 1 minute. Add tomatoes, broth, and beans. Simmer 25 minutes. Mash some beans for a thicker texture. Season with salt, pepper, and red pepper flakes."},
      {name:"Three Bean Salad",servings:"6 servings",ingredients:["1 can kidney beans, drained","1 can cannellini beans, drained","1 can chickpeas, drained","½ red onion, finely diced","3 celery stalks, diced","¼ cup fresh parsley","Dressing: ¼ cup olive oil, 3 tbsp apple cider vinegar, 2 tbsp sugar, 1 tsp Dijon, salt and pepper"],prep:"Combine all beans, red onion, celery, and parsley. Whisk dressing until sugar dissolves. Toss salad with dressing. Refrigerate at least 1 hour. Toss again before serving."},
      {name:"Red Bean Burgers",servings:"4 servings",ingredients:["2 cans red kidney beans, drained and dried","½ cup oats, blended","1 egg","3 garlic cloves, minced","1 tsp smoked paprika","1 tsp cumin","½ onion, grated","Salt and pepper","Burger buns and toppings"],prep:"Mash beans leaving some chunks. Mix with blended oats, egg, garlic, onion, smoked paprika, and cumin. Season with salt and pepper. Form into 4 patties. Refrigerate 30 minutes. Cook in a well-oiled skillet over medium heat 4 minutes per side. Serve on buns."},
      {name:"Kidney Bean Stew",servings:"4 servings",ingredients:["2 cans kidney beans, drained","300g smoked sausage, sliced","1 onion, diced","2 carrots, diced","4 garlic cloves","1 can crushed tomatoes","2 cups chicken broth","1 tsp smoked paprika","1 tsp cumin","2 tbsp olive oil","Salt and pepper"],prep:"Brown sausage in a large pot. Remove. Cook onion, carrots, and garlic until soft. Add spices. Add tomatoes, broth, beans, and sausage. Simmer 25 minutes until sauce thickens. Season with salt and pepper."},
      {name:"Red Bean Paste",servings:"8 servings",ingredients:["500g dried adzuki beans, soaked overnight","1 cup sugar","2 tbsp vegetable oil","Pinch of salt"],prep:"Cook soaked beans in fresh water until very soft — about 1.5 hours. Drain reserving some liquid. Mash or blend until smooth. Transfer to a non-stick pan over medium heat. Add sugar, oil, and salt. Cook stirring constantly until mixture thickens and pulls away from the sides — about 20–25 minutes. Cool completely. Use as a filling for mochi, buns, pancakes, and Asian pastries."},
      {name:"Haitian Red Bean Stew",servings:"4 servings",ingredients:["2 cans red kidney beans, drained","1 onion, diced","4 garlic cloves","1 green bell pepper, diced","1 can diced tomatoes","2 cups vegetable broth","1 tsp thyme","1 tsp smoked paprika","¼ tsp cloves","3 tbsp oil","Salt and pepper","White rice to serve"],prep:"Cook onion, bell pepper, and garlic in oil until soft. Add thyme, paprika, and cloves. Add tomatoes, broth, and beans. Simmer 25 minutes until sauce is thick and flavorful. Season with salt and pepper. Serve over white rice."},
      {name:"Kidney Bean Salad",servings:"4 servings",ingredients:["2 cans kidney beans, drained","½ red onion, finely diced","3 celery stalks, diced","¼ cup fresh parsley, chopped","Dressing: 3 tbsp olive oil, 2 tbsp red wine vinegar, 1 tsp Dijon mustard, 1 tsp honey, salt and pepper"],prep:"Combine kidney beans, red onion, celery, and parsley. Whisk dressing ingredients. Toss salad with dressing. Let sit 30 minutes before serving for flavors to develop."},
      {name:"Red Bean and Rice Soup",servings:"4 servings",ingredients:["1 can red kidney beans, drained","½ cup long grain rice","1 onion, diced","3 celery stalks, diced","1 green bell pepper, diced","3 garlic cloves","6 cups chicken broth","1 tsp thyme","1 tsp smoked paprika","Cajun seasoning","2 tbsp oil","Salt and pepper"],prep:"Cook onion, celery, and bell pepper in oil until soft. Add garlic and spices. Add broth, beans, and rice. Simmer 20 minutes until rice is cooked and soup has thickened. Season with salt, pepper, and Cajun seasoning."},
      {name:"Red Beans with Coconut Milk",servings:"4 servings",ingredients:["2 cans red kidney beans, drained","1 can coconut milk","1 onion, diced","4 garlic cloves","1-inch ginger, grated","1 tsp curry powder","1 tsp turmeric","½ tsp cayenne","3 tbsp oil","Salt","Rice to serve"],prep:"Cook onion in oil until golden. Add garlic, ginger, curry powder, turmeric, and cayenne and cook 1 minute. Add beans and coconut milk. Simmer 20 minutes until sauce thickens. Season with salt. Serve over steamed rice."},
      {name:"Red Bean Coconut Dessert Soup",servings:"4 servings",ingredients:["1 can red kidney or adzuki beans, drained","1 can coconut milk","2 cups water","¼ cup palm sugar or brown sugar","1 pandan leaf or vanilla extract","Pinch of salt"],prep:"Combine beans, water, coconut milk, sugar, and pandan leaf in a pot. Bring to a gentle simmer. Cook 15 minutes. Remove pandan leaf. Add salt. Adjust sweetness to taste. Serve warm or chilled."},
      {name:"Kidney Bean Pasta",servings:"4 servings",ingredients:["400g short pasta","1 can kidney beans, drained","4 garlic cloves","1 can diced tomatoes","½ cup fresh basil","¼ cup olive oil","½ tsp red pepper flakes","Salt and pepper","Parmesan to serve"],prep:"Cook pasta until al dente. Reserve 1 cup pasta water. Heat olive oil. Cook garlic and red pepper flakes. Add tomatoes and simmer 10 minutes. Add beans and simmer 5 minutes. Toss with pasta and pasta water as needed. Add basil. Season with salt and pepper."},
      {name:"Kidney Bean Dhal",servings:"4 servings",ingredients:["2 cans kidney beans, drained","1 onion, finely diced","4 garlic cloves","1 tbsp ginger","1 can crushed tomatoes","1 tsp garam masala","1 tsp cumin","1 tsp turmeric","Tadka: ghee, cumin seeds, mustard seeds, dried red chilies","Salt","Basmati rice and naan to serve"],prep:"Cook onion until golden. Add garlic and ginger and cook 2 minutes. Add spices. Add tomatoes and simmer 10 minutes. Add kidney beans and a splash of water. Simmer 20 minutes until very thick. Make tadka by frying cumin seeds, mustard seeds, and dried chilies in ghee until fragrant. Pour over the dhal. Season with salt."}
    ]
  },

  {
    id: "lentils",
    icon:"🟡", name:"Lentils",
    desc:"Red, green, and French lentil dishes including soups, dahls, salads, and veggie burgers.",
    recipes:[
      {name:"Red Lentil Soup",servings:"6 servings",ingredients:["1½ cups red lentils, rinsed","1 onion, diced","3 carrots, diced","4 garlic cloves, minced","1 can crushed tomatoes","6 cups vegetable broth","2 tsp cumin","1 tsp smoked paprika","½ tsp turmeric","3 tbsp olive oil","Juice of 1 lemon","Salt and pepper","Fresh parsley to garnish"],prep:"Heat olive oil in a large pot. Cook onion and carrots until soft. Add garlic and all spices and cook 1 minute. Add lentils, tomatoes, and broth. Bring to a boil. Reduce heat and simmer 25–30 minutes until lentils have completely dissolved and soup is thick. Add lemon juice. Season with salt and pepper."},
      {name:"Red Lentil Dhal",servings:"4 servings",ingredients:["1½ cups red lentils","1 onion, finely diced","4 garlic cloves","1 tbsp fresh ginger","1 can crushed tomatoes","1 can coconut milk","2 tsp curry powder","1 tsp turmeric","1 tsp cumin","½ tsp cayenne","3 tbsp oil","Salt","Basmati rice and naan to serve","Tadka: oil, mustard seeds, curry leaves, dried red chilies"],prep:"Cook onion in oil until golden. Add garlic and ginger and cook 2 minutes. Add curry powder, turmeric, cumin, and cayenne and cook 1 minute. Add tomatoes and simmer 5 minutes. Add lentils and coconut milk. Simmer 20–25 minutes until lentils dissolve and dhal is thick. Make tadka by frying mustard seeds, curry leaves, and dried chilies in hot oil until they pop. Pour over dhal. Season with salt."},
      {name:"French Lentil Salad",servings:"4 servings",ingredients:["1½ cups French green lentils, cooked","2 carrots, finely diced","2 celery stalks, finely diced","½ red onion, finely diced","¼ cup fresh parsley, chopped","Dressing: 3 tbsp olive oil, 2 tbsp red wine vinegar, 1 tbsp Dijon mustard, 1 garlic clove, salt and pepper"],prep:"Cook lentils in salted water 20–25 minutes until tender but still holding shape. Drain and cool. Combine with carrots, celery, onion, and parsley. Whisk dressing and toss well. Let sit 15 minutes before serving."},
      {name:"Lentil Bolognese",servings:"4 servings",ingredients:["1½ cups green or brown lentils, cooked","1 onion, finely diced","2 carrots, finely diced","2 celery stalks, finely diced","4 garlic cloves","1 can (28oz) crushed tomatoes","½ cup red wine","1 tsp Italian seasoning","3 tbsp olive oil","Salt and pepper","Pasta and Parmesan to serve"],prep:"Cook onion, carrots, and celery in olive oil until very soft — 15 minutes. Add garlic and Italian seasoning. Add wine and reduce. Add tomatoes and lentils. Simmer 20 minutes until sauce is thick. Season with salt and pepper. Serve over spaghetti with Parmesan."},
      {name:"Mujaddara",servings:"4 servings",ingredients:["1 cup green or brown lentils","1 cup long grain rice","2 large onions, thinly sliced","4 tbsp olive oil","1 tsp cumin","½ tsp cinnamon","Salt and pepper","Greek yogurt and fresh herbs to serve"],prep:"Caramelize onions in olive oil over medium-low heat for 30–40 minutes until deeply golden and sweet. Reserve half for garnish. Add cumin and cinnamon to remaining onions. Cook lentils in salted water 15 minutes until just tender. Drain. Cook rice. Combine lentils and rice. Season with salt and pepper. Top with caramelized onions. Serve with yogurt and fresh herbs."},
      {name:"Lentil Tacos",servings:"4 servings",ingredients:["1½ cups green lentils, cooked","1 onion, diced","3 garlic cloves","1 tsp cumin","1 tsp chili powder","1 tsp smoked paprika","½ cup vegetable broth","8 corn tortillas","Shredded cabbage, avocado, salsa, lime, cilantro"],prep:"Cook onion and garlic in oil until soft. Add spices. Add cooked lentils and broth. Cook 5–8 minutes until mixture thickens. Season with salt. Mash lightly. Warm tortillas. Fill with lentil mixture and desired toppings."},
      {name:"Lentil Burgers",servings:"4 servings",ingredients:["1½ cups green lentils, cooked and cooled","½ cup breadcrumbs","1 egg","3 garlic cloves, minced","½ onion, grated","1 tsp cumin","1 tsp smoked paprika","¼ cup fresh parsley","Salt and pepper","Oil for frying","Burger buns and toppings"],prep:"Mash lentils thoroughly leaving some texture. Mix with breadcrumbs, egg, garlic, onion, spices, and parsley. Season with salt and pepper. Form into 4 patties. Refrigerate 30 minutes. Cook in well-oiled skillet over medium heat 4 minutes per side until golden."},
      {name:"Lentil Soup",servings:"6 servings",ingredients:["1½ cups green or brown lentils","1 onion, diced","3 carrots, diced","3 celery stalks, diced","4 garlic cloves","1 can diced tomatoes","6 cups vegetable or chicken broth","2 tsp cumin","1 tsp coriander","Juice of 1 lemon","3 tbsp olive oil","Salt and pepper","Fresh parsley"],prep:"Heat olive oil in a large pot. Cook onion, carrots, and celery until soft. Add garlic and spices and cook 1 minute. Add lentils, tomatoes, and broth. Simmer 30 minutes until lentils are tender. Add lemon juice. Season with salt and pepper."},
      {name:"Lebanese Lentil Soup",servings:"4 servings",ingredients:["1½ cups red lentils","1 large onion, diced","4 garlic cloves","1 tsp cumin","1 tsp turmeric","½ tsp coriander","6 cups vegetable broth","Juice of 1–2 lemons","3 tbsp olive oil","Salt and pepper","Crispy fried onions and lemon wedges to serve"],prep:"Cook onion in olive oil until deeply golden — 20 minutes. Reserve some for garnish. Add garlic and spices and cook 1 minute. Add lentils and broth. Simmer 25 minutes until lentils dissolve. Blend until smooth. Season very generously with lemon juice, salt, and pepper. Serve topped with crispy onions and extra lemon wedges."},
      {name:"Lentil and Sweet Potato Stew",servings:"4 servings",ingredients:["1 cup red lentils","2 sweet potatoes, cubed","1 onion, diced","4 garlic cloves","1-inch ginger, grated","1 can coconut milk","2 cups vegetable broth","2 tsp curry powder","1 tsp turmeric","3 tbsp oil","Juice of 1 lime","Salt","Cilantro to garnish"],prep:"Cook onion in oil until soft. Add garlic, ginger, curry powder, and turmeric. Add sweet potatoes and stir to coat. Add lentils, broth, and coconut milk. Simmer 20–25 minutes until lentils dissolve and sweet potato is very tender. Add lime juice. Season with salt."},
      {name:"Lentil Stuffed Peppers",servings:"4 servings",ingredients:["4 large bell peppers","1 cup green lentils, cooked","1 cup cooked rice","1 onion, diced","3 garlic cloves","1 can diced tomatoes","1 tsp Italian seasoning","1½ cups shredded mozzarella","Salt and pepper"],prep:"Preheat oven to 375F. Cook onion and garlic. Add tomatoes, lentils, rice, and Italian seasoning. Season with salt and pepper. Cut tops off peppers and remove seeds. Fill with lentil mixture. Top with mozzarella. Place in a baking dish with ¼ cup water. Cover and bake 30 minutes. Uncover and bake 15 more minutes."},
      {name:"Lentil Shepherd's Pie",servings:"6 servings",ingredients:["1½ cups green lentils, cooked","1 onion, diced","2 carrots, diced","2 celery stalks, diced","3 garlic cloves","1 cup frozen peas","1 cup vegetable broth","2 tbsp tomato paste","1 tbsp Worcestershire sauce","Mashed potato topping: 1kg potatoes, 4 tbsp butter, ½ cup cream, salt and pepper"],prep:"Cook onion, carrots, and celery until soft. Add garlic and tomato paste. Add broth, Worcestershire, and lentils. Simmer 15 minutes until thick. Add peas. Transfer to a baking dish. Top with creamy mashed potatoes. Rough up surface with a fork. Bake at 375F for 25–30 minutes until golden."},
      {name:"Lentil and Vegetable Curry",servings:"4 servings",ingredients:["1 cup red lentils","1 sweet potato, cubed","2 cups spinach","1 onion, diced","4 garlic cloves","1 tbsp ginger","1 can coconut milk","1 can diced tomatoes","2 tbsp curry powder","1 tsp turmeric","3 tbsp oil","Salt","Rice to serve"],prep:"Cook onion in oil until golden. Add garlic, ginger, curry powder, and turmeric and cook 1 minute. Add tomatoes, coconut milk, lentils, and sweet potato. Simmer 20–25 minutes until lentils dissolve and sweet potato is tender. Add spinach and stir until wilted. Season with salt."},
      {name:"Beluga Lentil Salad",servings:"4 servings",ingredients:["1½ cups beluga black lentils, cooked","1 cup cherry tomatoes, halved","½ red onion, finely diced","½ cucumber, diced","¼ cup fresh herbs — parsley and mint","100g feta, crumbled","Dressing: 3 tbsp olive oil, 2 tbsp lemon juice, 1 tsp Dijon, 1 tsp honey, salt and pepper"],prep:"Cook beluga lentils in salted water 20–25 minutes until tender. Drain and cool. Combine with tomatoes, red onion, cucumber, and herbs. Whisk dressing and toss. Top with crumbled feta."}
    ]
  },

  {
    id: "whiteBeans",
    icon:"⬜", name:"White Beans",
    desc:"Cannellini, navy, and Great Northern bean dishes — soups, stews, dips, and Italian classics.",
    recipes:[
      {name:"White Bean Soup",servings:"6 servings",ingredients:["2 cans cannellini beans, drained","1 onion, diced","4 garlic cloves","2 carrots, diced","3 celery stalks, diced","4 cups chicken or vegetable broth","2 cups spinach or kale","3 tbsp olive oil","Fresh rosemary and thyme","Salt, pepper, and red pepper flakes","Parmesan and crusty bread"],prep:"Heat olive oil in a large pot. Cook onion, carrots, and celery until soft. Add garlic and herbs and cook 1 minute. Add broth and beans. Simmer 20 minutes. Mash some beans for a thicker texture. Add greens and stir until wilted. Season with salt, pepper, and red pepper flakes."},
      {name:"White Bean Dip",servings:"6 servings",ingredients:["2 cans cannellini beans, drained","4 garlic cloves","Juice of 2 lemons","¼ cup tahini","3 tbsp olive oil","½ tsp cumin","Salt and pepper","Olive oil, paprika, and parsley to garnish","Pita and vegetables to serve"],prep:"Blend beans, garlic, lemon juice, tahini, and cumin until very smooth. Add olive oil and blend again. Season with salt and pepper. Add a splash of water if needed. Transfer to a bowl. Drizzle with olive oil and sprinkle with paprika and parsley."},
      {name:"Pasta e Fagioli",servings:"6 servings",ingredients:["2 cans cannellini beans, drained","400g short pasta — ditalini or elbow","1 onion, diced","4 garlic cloves","2 celery stalks, diced","1 can (28oz) crushed tomatoes","6 cups chicken or vegetable broth","Parmesan rind","Fresh rosemary","3 tbsp olive oil","Salt, pepper, and red pepper flakes","Parmesan for serving"],prep:"Heat olive oil in a large pot. Cook onion, celery, and garlic until soft. Add rosemary. Add tomatoes, broth, and Parmesan rind. Simmer 15 minutes. Add beans. Simmer 10 more minutes. Mash some beans for a thick texture. Remove Parmesan rind. Add pasta and cook until tender. Season with salt, pepper, and red pepper flakes. Serve with Parmesan drizzled with olive oil."},
      {name:"Tuscan White Beans",servings:"4 servings",ingredients:["2 cans cannellini beans, drained","4 garlic cloves, thinly sliced","2 cups cherry tomatoes","2 cups fresh spinach","½ cup vegetable broth","¼ cup olive oil","Fresh sage and rosemary","Salt, pepper, and red pepper flakes","Crusty bread to serve"],prep:"Heat olive oil in a large skillet over medium heat. Add garlic and cook until just golden. Add sage and rosemary. Add cherry tomatoes and cook until they burst. Add beans and broth. Simmer 10 minutes. Add spinach and stir until wilted. Season with salt, pepper, and red pepper flakes. Serve with crusty bread."},
      {name:"White Bean and Kale Soup",servings:"6 servings",ingredients:["2 cans cannellini beans, drained","3 cups kale, chopped","200g Italian sausage, sliced","1 onion, diced","4 garlic cloves","6 cups chicken broth","1 can diced tomatoes","3 tbsp olive oil","Fresh thyme and rosemary","Salt, pepper, and red pepper flakes"],prep:"Brown sausage in olive oil. Remove. Cook onion and garlic in same pot. Add tomatoes, broth, and herbs. Simmer 15 minutes. Add beans and sausage. Simmer 15 more minutes. Add kale and cook until wilted. Season with salt, pepper, and red pepper flakes."},
      {name:"White Bean Shakshuka",servings:"4 servings",ingredients:["1 can cannellini beans, drained","1 can (28oz) crushed tomatoes","4 large eggs","1 onion, diced","4 garlic cloves","1 tsp smoked paprika","1 tsp cumin","½ tsp cayenne","3 tbsp olive oil","Fresh parsley and feta to serve"],prep:"Heat olive oil in a large skillet. Cook onion and garlic until soft. Add spices and cook 1 minute. Add tomatoes and beans. Simmer 10 minutes until slightly thickened. Make 4 wells in the sauce. Crack an egg into each well. Cover and cook 6–8 minutes until whites are set but yolks are still runny. Top with crumbled feta and fresh parsley."},
      {name:"White Bean and Tuna Salad",servings:"4 servings",ingredients:["2 cans cannellini beans, drained","2 cans tuna in olive oil, drained","½ red onion, finely diced","¼ cup Kalamata olives, halved","2 tbsp capers","¼ cup fresh parsley","3 tbsp olive oil","2 tbsp lemon juice","Salt and pepper"],prep:"Combine beans, tuna, red onion, olives, capers, and parsley. Dress with olive oil and lemon juice. Toss gently. Season with salt and pepper. Serve at room temperature with crusty bread."},
      {name:"Navy Bean Soup with Ham",servings:"6 servings",ingredients:["500g dried navy beans, soaked overnight","1 ham hock","1 onion, diced","3 carrots, diced","3 celery stalks, diced","4 garlic cloves","8 cups chicken broth","Bay leaves and thyme","Salt and pepper","Fresh parsley"],prep:"Cook soaked navy beans with ham hock, onion, carrots, celery, garlic, broth, and bay leaves. Simmer covered 1.5–2 hours until beans are very tender. Remove ham hock and shred meat. Return meat to soup. Remove bay leaves. Mash some beans for a thicker texture. Season with salt and pepper."},
      {name:"Boston Baked Beans",servings:"8 servings",ingredients:["500g dried navy beans, soaked overnight","200g salt pork or bacon, diced","1 onion, diced","½ cup molasses","2 tbsp brown sugar","1 tbsp dry mustard","1 tbsp Worcestershire sauce","Salt and pepper"],prep:"Cook soaked beans in fresh water until almost tender — about 45 minutes. Drain. Layer salt pork, onion, and beans in a large bean pot or Dutch oven. Mix molasses, brown sugar, mustard, Worcestershire, salt, and enough hot water to cover. Pour over beans. Cover and bake at 300F for 6 hours. Check every hour and add water as needed. Uncover for last hour to develop a dark caramelized crust."},
      {name:"Ribollita",servings:"6 servings",ingredients:["2 cans cannellini beans, drained","1 onion, diced","2 carrots, diced","2 celery stalks, diced","4 garlic cloves","2 cups cavolo nero or kale, chopped","1 can diced tomatoes","6 cups vegetable broth","4 thick slices day-old bread","3 tbsp olive oil","Parmesan rind","Salt, pepper, and red pepper flakes"],prep:"Cook onion, carrots, and celery in olive oil. Add garlic. Add tomatoes, broth, beans, cavolo nero, and Parmesan rind. Simmer 30 minutes. Tear bread into chunks and stir in. Simmer 15 minutes until bread breaks down and thickens the soup. Season well. Remove Parmesan rind. Even better reheated the next day."},
      {name:"White Bean Cassoulet",servings:"6 servings",ingredients:["500g dried white beans, soaked overnight","4 duck confit legs","300g pork sausages","200g bacon, cubed","1 onion, diced","4 garlic cloves","1 can (28oz) crushed tomatoes","4 cups chicken broth","Bouquet garni","Breadcrumbs for topping"],prep:"Cook soaked beans until almost tender. Brown sausages, bacon, and duck confit in a Dutch oven. Cook onion and garlic. Layer everything — beans, meats, tomatoes, broth, and bouquet garni — in a large casserole. Bake covered at 325F for 2 hours. Uncover, top with breadcrumbs, and bake 30 more minutes until crust is golden."},
      {name:"Gigante Beans in Tomato Sauce",servings:"4 servings",ingredients:["2 cans gigante or large lima beans, drained","1 onion, diced","4 garlic cloves","1 can (28oz) crushed tomatoes","3 tbsp olive oil","1 tsp sugar","Fresh parsley","Salt, pepper, and red pepper flakes","Feta cheese to serve"],prep:"Preheat oven to 375F. Cook onion and garlic in olive oil until soft. Add tomatoes, sugar, salt, and red pepper flakes. Simmer 10 minutes. Add beans. Transfer to a baking dish. Bake uncovered 45 minutes until sauce is thick and beans are caramelized on top. Top with crumbled feta and fresh parsley."},
      {name:"Great Northern Bean Stew",servings:"4 servings",ingredients:["2 cans Great Northern beans, drained","300g smoked sausage, sliced","1 onion, diced","3 carrots, diced","4 garlic cloves","1 can diced tomatoes","3 cups chicken broth","1 tsp Italian seasoning","3 tbsp olive oil","Salt and pepper"],prep:"Cook sausage in olive oil until browned. Remove. Cook onion, carrots, and garlic. Add Italian seasoning. Add tomatoes, broth, beans, and sausage. Simmer 25 minutes until thick and flavorful. Season with salt and pepper."},
      {name:"White Bean and Roasted Garlic Spread",servings:"6 servings",ingredients:["2 cans cannellini beans, drained","2 heads garlic, roasted","3 tbsp olive oil","Juice of 1 lemon","Fresh rosemary, finely chopped","Salt and pepper","Crostini and vegetables to serve"],prep:"Roast garlic heads at 400F for 45 minutes until very soft. Squeeze out cloves. Blend beans and roasted garlic until smooth. Add olive oil and lemon juice. Stir in rosemary. Season with salt and pepper. Spread on crostini or serve as a dip."},
      {name:"White Bean Hummus",servings:"6 servings",ingredients:["2 cans cannellini beans, drained","4 garlic cloves, roasted","Juice of 2 lemons","3 tbsp tahini","¼ cup olive oil","½ tsp cumin","Salt and pepper","Olive oil and paprika to garnish"],prep:"Roast garlic at 400F until soft. Squeeze out cloves. Blend beans, roasted garlic, lemon juice, tahini, and cumin until very smooth. Drizzle in olive oil while blending. Season with salt and pepper. Add a splash of cold water for creamier texture. Transfer to a bowl and drizzle with olive oil."}
    ]
  },

  {
    id: "edamame",
    icon:"🟢", name:"Edamame & Soybeans",
    desc:"Edamame snacks, soybean dishes, tofu preparations, and soy-based recipes.",
    recipes:[
      {name:"Salted Edamame",servings:"4 servings",ingredients:["500g frozen edamame in pods","2 tbsp coarse sea salt","1 tsp sesame oil (optional)","Optional: garlic, chili flakes, furikake"],prep:"Bring a large pot of well-salted water to a boil. Add frozen edamame pods. Cook 4–5 minutes until tender. Drain. Immediately toss with coarse sea salt. Serve hot or at room temperature. To eat squeeze pods and pop beans into your mouth."},
      {name:"Edamame Hummus",servings:"6 servings",ingredients:["2 cups shelled edamame, cooked","3 garlic cloves","Juice of 2 lemons","3 tbsp tahini","2 tbsp olive oil","½ tsp cumin","Salt and pepper","Sesame seeds and edamame to garnish","Pita and vegetables to serve"],prep:"Blend edamame, garlic, lemon juice, tahini, and cumin until smooth. Add olive oil and blend again. Add cold water a tablespoon at a time until creamy. Season with salt and pepper. Garnish with sesame seeds and a few edamame beans."},
      {name:"Edamame Fried Rice",servings:"4 servings",ingredients:["3 cups day-old cooked rice","1 cup shelled edamame, thawed","3 large eggs","1 cup frozen corn","3 green onions, sliced","3 garlic cloves, minced","3 tbsp soy sauce","1 tbsp oyster sauce","1 tsp sesame oil","2 tbsp vegetable oil"],prep:"Heat vegetable oil in a wok over very high heat. Scramble eggs and set aside. Add garlic and cook 30 seconds. Add cold rice and press into the pan. Stir fry 3 minutes until slightly crispy. Add edamame and corn. Add soy sauce, oyster sauce, and sesame oil. Return eggs and toss everything together. Add green onions. Serve immediately."},
      {name:"Edamame Salad",servings:"4 servings",ingredients:["2 cups shelled edamame, cooked and cooled","1 cup shredded carrots","1 red bell pepper, finely diced","3 green onions, sliced","¼ cup fresh cilantro","Dressing: 2 tbsp soy sauce, 2 tbsp rice vinegar, 1 tbsp sesame oil, 1 tsp honey, 1 tsp ginger","Sesame seeds to garnish"],prep:"Combine edamame, carrots, bell pepper, green onions, and cilantro in a bowl. Whisk dressing ingredients. Toss salad with dressing. Top with sesame seeds. Serve chilled or at room temperature."},
      {name:"Edamame Guacamole",servings:"6 servings",ingredients:["1 cup shelled edamame, cooked","2 avocados","Juice of 2 limes","2 garlic cloves","¼ cup fresh cilantro","1 jalapeño, minced","½ red onion, finely diced","Salt and pepper","Tortilla chips to serve"],prep:"Blend edamame until smooth. Mash avocados in a bowl leaving some texture. Mix in edamame, lime juice, garlic, jalapeño, and red onion. Add cilantro. Season with salt and pepper. Serve immediately with tortilla chips."},
      {name:"Spicy Edamame",servings:"4 servings",ingredients:["500g frozen edamame in pods","3 garlic cloves, minced","2 tbsp soy sauce","1 tbsp chili paste or sriracha","1 tsp sesame oil","1 tbsp butter","Sesame seeds and green onions"],prep:"Cook edamame pods in boiling salted water 4–5 minutes. Drain. In a skillet melt butter and cook garlic 1 minute. Add soy sauce, chili paste, and sesame oil. Add edamame and toss to coat. Cook 2 minutes until sauce caramelizes slightly. Transfer to a bowl. Top with sesame seeds and green onions."},
      {name:"Tempeh Stir Fry",servings:"4 servings",ingredients:["300g tempeh, cubed","2 cups broccoli florets","1 red bell pepper, sliced","2 carrots, julienned","3 garlic cloves, minced","1 tbsp fresh ginger","Sauce: 3 tbsp soy sauce, 2 tbsp hoisin, 1 tbsp sesame oil, 1 tbsp cornstarch, 1 tsp chili paste","2 tbsp oil","Sesame seeds and rice to serve"],prep:"Whisk sauce ingredients. Pan fry tempeh in oil over medium-high heat until golden on all sides. Remove. Add vegetables and stir fry 3–4 minutes. Add garlic and ginger and cook 30 seconds. Return tempeh. Pour sauce over and toss until everything is coated and sauce thickens. Serve over rice."},
      {name:"Cold Edamame Noodle Salad",servings:"4 servings",ingredients:["400g soba noodles, cooked and chilled","1 cup shelled edamame","2 cups shredded carrots","1 cucumber, julienned","3 green onions, sliced","¼ cup cilantro","Dressing: 3 tbsp soy sauce, 2 tbsp sesame oil, 2 tbsp rice vinegar, 1 tbsp honey, 1 tbsp ginger","Sesame seeds"],prep:"Cook soba noodles and rinse under cold water until completely cold. Drain well. Combine with carrots, edamame, cucumber, green onions, and cilantro. Whisk dressing and toss. Top with sesame seeds. Serve chilled."},
      {name:"Edamame Rice Bowl",servings:"4 servings",ingredients:["2 cups cooked sushi rice","1 cup shelled edamame","1 avocado, sliced","1 cup shredded carrots","1 cucumber, sliced","2 tbsp sesame seeds","Nori strips","Sauce: soy sauce, rice vinegar, sesame oil, honey"],prep:"Divide sushi rice into bowls. Arrange edamame, avocado, carrots, and cucumber in sections over rice. Drizzle sauce over. Top with sesame seeds and nori strips. Serve immediately."},
      {name:"Edamame and Tofu Stir Fry",servings:"4 servings",ingredients:["1 block (400g) firm tofu, cubed and pressed","1 cup shelled edamame","2 cups bok choy, chopped","3 garlic cloves","1 tbsp ginger","Sauce: 3 tbsp soy sauce, 1 tbsp oyster sauce, 1 tbsp sesame oil, 1 tsp cornstarch","2 tbsp oil","Rice to serve"],prep:"Press tofu dry. Pan fry in oil over high heat until golden on all sides. Remove. Stir fry bok choy until wilted. Add edamame, garlic, and ginger. Return tofu. Pour sauce over and toss until thickened. Serve over steamed rice."},
      {name:"Edamame Soup",servings:"4 servings",ingredients:["2 cups shelled edamame","1 onion, diced","3 garlic cloves","4 cups vegetable broth","½ cup coconut milk","1 tbsp fresh ginger","1 tsp cumin","3 tbsp olive oil","Juice of 1 lime","Salt and pepper","Sesame oil and edamame to garnish"],prep:"Cook onion in olive oil until soft. Add garlic, ginger, and cumin and cook 1 minute. Add edamame and broth. Simmer 10 minutes. Blend until very smooth. Add coconut milk and lime juice. Season with salt and pepper. Garnish with a drizzle of sesame oil and reserved edamame."},
      {name:"Edamame Avocado Toast",servings:"2 servings",ingredients:["½ cup shelled edamame, cooked","1 avocado","Juice of 1 lime","4 slices sourdough bread, toasted","Salt, pepper, and red pepper flakes","Everything bagel seasoning","Microgreens to garnish"],prep:"Mash avocado with lime juice, salt, and pepper. Blend edamame until roughly mashed. Spread avocado on toasted sourdough. Top with edamame mash. Season with salt, red pepper flakes, and everything bagel seasoning. Garnish with microgreens."},
      {name:"Soy Milk",servings:"4 cups",ingredients:["1 cup dried soybeans, soaked overnight","4 cups fresh water","1 tbsp sugar or to taste","Pinch of salt","Vanilla extract (optional)"],prep:"Drain soaked soybeans. Blend with 4 cups fresh water until very smooth. Strain through a nut milk bag or fine cheesecloth — squeeze firmly to extract all liquid. Pour strained milk into a pot. Bring to a boil over medium heat stirring frequently. Reduce heat and simmer 10–15 minutes. Add sugar, salt, and vanilla if using. Cool and refrigerate."},
      {name:"Soybean Stew",servings:"4 servings",ingredients:["2 cups dried soybeans, soaked overnight and cooked until tender","1 onion, diced","4 garlic cloves","2 carrots, diced","1 can diced tomatoes","2 cups vegetable broth","1 tsp cumin","1 tsp smoked paprika","3 tbsp olive oil","Salt and pepper","Fresh parsley"],prep:"Cook onion and carrots in olive oil until soft. Add garlic and spices and cook 1 minute. Add tomatoes, broth, and cooked soybeans. Simmer 25 minutes until flavors meld. Season with salt and pepper. Garnish with parsley."},
      {name:"Doenjang Jjigae with Edamame",servings:"4 servings",ingredients:["3 tbsp doenjang (Korean fermented soybean paste)","1 cup shelled edamame","200g firm tofu, cubed","1 zucchini, diced","1 onion, diced","1 cup mushrooms","4 cups anchovy or vegetable broth","1 jalapeño, sliced","2 green onions"],prep:"Bring broth to a boil. Dissolve doenjang in a ladle of broth and stir into pot. Add onion, zucchini, mushrooms, and jalapeño. Simmer 10 minutes. Add tofu and edamame and simmer 5 more minutes. Add green onions. Serve with steamed rice."}
    ]
  },

  {
    id: "splitPeas",
    icon:"🫘", name:"Split Peas & Dried Peas",
    desc:"Split pea soup, pea dhal, mushy peas, and comforting pea-based dishes.",
    recipes:[
      {name:"Classic Split Pea Soup",servings:"6 servings",ingredients:["500g dried split peas, rinsed","1 ham hock or 2 cups diced ham","1 onion, diced","3 carrots, diced","3 celery stalks, diced","4 garlic cloves, minced","8 cups chicken broth","Bay leaves and fresh thyme","Salt and pepper","Fresh parsley to garnish"],prep:"Combine split peas, ham hock, onion, carrots, celery, garlic, broth, and bay leaves in a large pot. Bring to a boil. Skim any foam. Reduce heat and simmer covered 1–1.5 hours until peas completely dissolve and soup is very thick. Remove ham hock and shred meat. Return meat to soup. Remove bay leaves. Season with salt and pepper. Garnish with parsley."},
      {name:"Yellow Split Pea Dhal",servings:"4 servings",ingredients:["1½ cups yellow split peas","1 onion, finely diced","4 garlic cloves","1 tbsp fresh ginger","1 can crushed tomatoes","1 tsp turmeric","1 tsp cumin","1 tsp coriander","½ tsp cayenne","3 tbsp oil","Salt","Tadka: ghee, mustard seeds, curry leaves, dried red chilies","Rice and naan to serve"],prep:"Rinse split peas and cook in water with turmeric until very soft and dissolved — about 30 minutes. In a separate pan cook onion in oil until golden. Add garlic, ginger, and remaining spices. Add tomatoes and simmer 10 minutes. Combine with cooked peas. Make tadka and pour over dhal. Season with salt."},
      {name:"Green Split Pea Soup",servings:"6 servings",ingredients:["500g green split peas, rinsed","1 onion, diced","3 carrots, diced","3 celery stalks, diced","4 garlic cloves","8 cups vegetable broth","1 tsp cumin","1 tsp smoked paprika","3 tbsp olive oil","Juice of 1 lemon","Salt and pepper","Croutons and fresh mint to serve"],prep:"Heat olive oil in a large pot. Cook onion, carrots, and celery until soft. Add garlic, cumin, and paprika. Add split peas and broth. Bring to a boil. Reduce heat and simmer 1 hour until peas dissolve. Add lemon juice. Season with salt and pepper."},
      {name:"Mushy Peas",servings:"4 servings",ingredients:["500g dried marrowfat peas, soaked overnight in water with 1 tsp bicarbonate of soda","3 cups fresh water","2 tbsp butter","Salt and pepper","Fresh mint (optional)"],prep:"Drain and rinse soaked peas thoroughly. Place in a pot with fresh water. Bring to a boil. Reduce heat and simmer 20–30 minutes until peas are completely soft and starting to break down. Mash roughly or stir vigorously. Stir in butter. Season with salt and pepper. Serve alongside fish and chips."},
      {name:"Matar Paneer",servings:"4 servings",ingredients:["2 cups fresh or frozen peas","300g paneer, cubed","1 onion, finely diced","4 garlic cloves","1 tbsp ginger","1 can crushed tomatoes","1 tsp garam masala","1 tsp cumin","1 tsp coriander","1 tsp turmeric","3 tbsp oil","Salt","Fresh cilantro and cream to serve"],prep:"Fry paneer cubes in oil until golden on all sides. Remove. Cook onion until golden. Add garlic, ginger, and all spices and cook 2 minutes. Add tomatoes and simmer 10 minutes. Add peas and cook 5 minutes. Return paneer. Simmer 5 more minutes. Season with salt. Add a swirl of cream and fresh cilantro."},
      {name:"Pea and Ham Soup",servings:"6 servings",ingredients:["500g split peas, rinsed","1 ham hock","1 onion, diced","3 carrots, diced","3 celery stalks, diced","4 garlic cloves","8 cups chicken broth","Bay leaves and thyme","Salt and pepper"],prep:"Combine all ingredients in a large pot. Bring to a boil. Skim foam. Reduce heat and simmer covered 2 hours until peas completely dissolve. Remove ham hock. Pull off meat and shred. Return meat to soup. Remove bay leaves. Season with salt and pepper."},
      {name:"Cold Pea Soup",servings:"4 servings",ingredients:["500g frozen peas","1 onion, diced","3 garlic cloves","4 cups vegetable broth","½ cup Greek yogurt","Large handful fresh mint","3 tbsp butter","Juice of 1 lemon","Salt, pepper, and sugar"],prep:"Cook onion in butter until soft. Add garlic. Add broth and bring to a boil. Add peas and cook just 3 minutes — do not overcook or the color will fade. Add mint. Immediately blend until smooth. Stir in yogurt and lemon juice. Season with salt, pepper, and a pinch of sugar. Refrigerate until very cold — at least 2 hours. Serve chilled."},
      {name:"Split Pea and Sausage Soup",servings:"6 servings",ingredients:["500g split peas, rinsed","300g smoked sausage, sliced","1 onion, diced","3 carrots, diced","3 celery stalks, diced","4 garlic cloves","8 cups chicken broth","Bay leaves and thyme","Salt and pepper"],prep:"Brown sausage in a large pot. Remove. Cook onion, carrots, celery, and garlic. Add split peas, broth, bay leaves, and thyme. Simmer 1 hour until peas dissolve. Return sausage. Season with salt and pepper. Remove bay leaves."},
      {name:"Hoppin John",servings:"6 servings",ingredients:["500g dried black eyed peas","200g bacon or ham hock","1 onion, diced","3 celery stalks, diced","4 garlic cloves","8 cups chicken broth","Bay leaves and thyme","Salt and pepper","White rice and collard greens to serve"],prep:"Cook bacon or brown ham hock in a large pot. Add onion, celery, and garlic and cook until soft. Add black eyed peas, broth, bay leaves, and thyme. Simmer 1–1.5 hours until peas are very tender. Season with salt and pepper. Remove bay leaves. Serve over white rice with collard greens on the side. Traditional New Year's Day good luck dish."},
      {name:"Marinated Black Eyed Peas",servings:"4 servings",ingredients:["2 cans black eyed peas, drained","½ red onion, finely diced","1 red bell pepper, finely diced","¼ cup fresh parsley","Dressing: 3 tbsp olive oil, 2 tbsp red wine vinegar, 1 tbsp Dijon mustard, 1 tsp honey, salt and pepper"],prep:"Combine black eyed peas, red onion, bell pepper, and parsley. Whisk dressing and pour over. Toss well. Refrigerate at least 1 hour. Toss again before serving."},
      {name:"Pigeon Peas and Rice",servings:"4 servings",ingredients:["1 can pigeon peas, drained","1½ cups long grain rice","1 onion, diced","4 garlic cloves","1 can coconut milk","1½ cups vegetable broth","1 tsp cumin","1 tsp thyme","3 tbsp olive oil","Salt and pepper","Fresh cilantro and lime"],prep:"Cook onion and garlic in olive oil until soft. Add cumin and thyme. Add rice and stir to coat. Add coconut milk, broth, and pigeon peas. Bring to a boil. Reduce heat, cover tightly, and cook 18–20 minutes until rice is fully cooked and liquid is absorbed. Fluff with a fork. Season with salt and pepper."},
      {name:"Split Pea Fritters",servings:"4 servings",ingredients:["1 cup yellow split peas, soaked overnight and drained","½ onion, roughly chopped","3 garlic cloves","1 tsp cumin","1 tsp coriander","½ tsp turmeric","¼ cup fresh cilantro","Salt and pepper","Oil for shallow frying","Yogurt dipping sauce"],prep:"Blend soaked split peas with onion, garlic, and spices until a coarse paste forms. Add cilantro. Season with salt and pepper. Shape into small patties. Shallow fry in oil over medium heat 3 minutes per side until golden and cooked through. Serve with garlic yogurt sauce."},
      {name:"Cowpea Stew",servings:"4 servings",ingredients:["2 cans cowpeas or black eyed peas, drained","1 onion, diced","4 garlic cloves","1 can crushed tomatoes","2 cups vegetable broth","1 tsp smoked paprika","1 tsp cumin","½ tsp cayenne","3 tbsp olive oil","Salt and pepper","Fresh parsley"],prep:"Cook onion and garlic in olive oil until soft. Add smoked paprika, cumin, and cayenne and cook 1 minute. Add tomatoes, broth, and cowpeas. Simmer 25 minutes. Mash some peas for a thicker texture. Season with salt and pepper. Garnish with parsley."},
      {name:"Gungo Pea Soup",servings:"6 servings",ingredients:["2 cans pigeon peas, drained","1 onion, diced","4 garlic cloves","2 carrots, diced","1 can coconut milk","4 cups vegetable broth","1 tsp thyme","1 tsp allspice","3 tbsp olive oil","Salt and pepper","Dumplings (optional): 1 cup flour, water, and salt"],prep:"Cook onion, garlic, and carrots in olive oil until soft. Add thyme and allspice. Add broth, coconut milk, and pigeon peas. Simmer 20 minutes. For dumplings mix flour and salt with just enough water to form a firm dough. Shape into small dumplings and drop into simmering soup. Cook 15 minutes. Season with salt and pepper."}
    ]
  },

  {
    id: "pintoBeans",
    icon:"🟠", name:"Pinto Beans & Other Varieties",
    desc:"Pinto beans, fava beans, navy beans, lima beans, adzuki beans, and more.",
    recipes:[
      {name:"Refried Beans",servings:"4 servings",ingredients:["2 cans pinto beans, drained — reserve liquid","3 garlic cloves, minced","1 onion, finely diced","1 tsp cumin","½ tsp smoked paprika","3 tbsp lard or vegetable oil","Salt and pepper","Cheese, sour cream, and jalapeños to serve"],prep:"Heat lard or oil in a large skillet over medium heat. Cook onion until deeply golden. Add garlic, cumin, and paprika and cook 1 minute. Add beans and a splash of reserved bean liquid. Begin mashing beans with a fork or potato masher while stirring — add liquid gradually to reach desired consistency. Cook stirring frequently until beans pull away from the sides of the pan. Season with salt and pepper."},
      {name:"Borracho Beans",servings:"6 servings",ingredients:["500g dried pinto beans, soaked overnight","200g bacon, diced","1 onion, diced","4 garlic cloves","2 jalapeños, diced","1 can diced tomatoes","1 bottle (12 oz) Mexican beer","4 cups chicken broth","1 tsp cumin","1 tsp oregano","Salt and pepper","Fresh cilantro"],prep:"Cook bacon in a large pot until crispy. Remove. Cook onion, jalapeños, and garlic in bacon fat until soft. Add cumin and oregano. Add soaked beans, tomatoes, beer, broth, and bacon. Bring to a boil. Reduce heat and simmer 1.5–2 hours until beans are very tender. Season with salt and pepper. Garnish with cilantro. The beer gives these beans incredible depth."},
      {name:"Fava Bean Bruschetta",servings:"4 servings",ingredients:["2 cups fresh or frozen fava beans, shelled","4 garlic cloves","¼ cup fresh mint, chopped","¼ cup Pecorino Romano, shaved","3 tbsp extra virgin olive oil","Juice of 1 lemon","Salt and pepper","Crusty bread, toasted"],prep:"Blanch fava beans in boiling water 2 minutes. Transfer to ice water. Pop outer skins off each bean. Crush beans roughly with a fork. Mix with garlic, mint, olive oil, and lemon juice. Season with salt and pepper. Spread on toasted bread. Top with Pecorino shavings."},
      {name:"Lima Bean Stew",servings:"4 servings",ingredients:["2 cans lima beans, drained","1 onion, diced","3 garlic cloves","2 carrots, diced","1 can diced tomatoes","2 cups vegetable broth","1 tsp smoked paprika","1 tsp cumin","3 tbsp olive oil","Salt and pepper","Fresh parsley"],prep:"Heat olive oil in a large pot. Cook onion and carrots until soft. Add garlic and spices and cook 1 minute. Add tomatoes, broth, and lima beans. Simmer 20 minutes until sauce thickens. Season with salt and pepper. Garnish with parsley."},
      {name:"Adzuki Bean Rice",servings:"4 servings",ingredients:["1 cup dried adzuki beans, soaked overnight","2 cups Japanese short grain rice","3 cups water","1 tsp salt","Sesame seeds and sea salt to garnish"],prep:"Cook soaked adzuki beans in fresh water until just tender — about 40 minutes. Reserve the cooking liquid. Add enough water to adzuki cooking liquid to make 3 cups total. Rinse rice and combine with adzuki beans and liquid. Cook in a rice cooker or pot until rice is fully cooked. Fluff with a fork. Serve topped with sesame seeds and a pinch of sea salt."},
      {name:"Pinto Bean Tacos",servings:"4 servings",ingredients:["2 cans pinto beans, drained","1 onion, diced","3 garlic cloves","1 tsp cumin","1 tsp chili powder","½ cup vegetable broth","8 corn tortillas","Shredded cabbage, pico de gallo, avocado, cilantro, lime"],prep:"Cook onion and garlic in oil until soft. Add spices. Add beans and broth. Cook 10 minutes mashing some beans for a creamy texture. Season with salt. Warm tortillas. Fill with bean mixture and all desired toppings."},
      {name:"Fava Bean Soup",servings:"4 servings",ingredients:["500g dried fava beans, soaked overnight and peeled","1 onion, diced","4 garlic cloves","4 cups vegetable broth","¼ cup olive oil","1 tsp cumin","Juice of 1 lemon","Salt and pepper","Fresh herbs and olive oil to garnish"],prep:"Cook peeled fava beans with onion and garlic in broth until very soft — about 45 minutes. Blend until completely smooth. Stir in olive oil, cumin, and lemon juice. Season generously with salt and pepper. Thin with water or broth if needed. Serve topped with a drizzle of olive oil and fresh herbs."},
      {name:"Butter Bean Stew",servings:"4 servings",ingredients:["2 cans butter beans, drained","1 onion, diced","4 garlic cloves","1 can crushed tomatoes","2 cups vegetable broth","2 cups spinach","1 tsp smoked paprika","1 tsp cumin","3 tbsp olive oil","Salt and pepper","Crusty bread to serve"],prep:"Heat olive oil in a large pot. Cook onion and garlic until soft. Add spices. Add tomatoes, broth, and butter beans. Simmer 20 minutes. Add spinach and stir until wilted. Season with salt and pepper. Serve with crusty bread."},
      {name:"Pinto Bean Soup",servings:"6 servings",ingredients:["2 cans pinto beans, drained","1 onion, diced","3 garlic cloves","2 carrots, diced","3 celery stalks, diced","4 cups chicken or vegetable broth","1 tsp cumin","1 tsp smoked paprika","2 tbsp olive oil","Salt, pepper, and cayenne","Cilantro, sour cream, and lime"],prep:"Heat olive oil in a large pot. Cook onion, carrots, and celery until soft. Add garlic and spices and cook 1 minute. Add beans and broth. Simmer 25 minutes. Mash some beans for a thicker texture. Season with salt, pepper, and cayenne."},
      {name:"Cranberry Bean Stew",servings:"4 servings",ingredients:["2 cans cranberry or borlotti beans, drained","1 onion, diced","4 garlic cloves","1 can crushed tomatoes","2 cups vegetable broth","Fresh sage and rosemary","3 tbsp olive oil","Salt and pepper","Parmesan and bread to serve"],prep:"Cook onion in olive oil until soft. Add garlic and herbs and cook 1 minute. Add tomatoes, broth, and beans. Simmer 20 minutes until sauce thickens and flavors develop. Season with salt and pepper. Drizzle with olive oil. Serve with Parmesan and crusty bread."},
      {name:"Mung Bean Congee",servings:"4 servings",ingredients:["½ cup mung beans, soaked 1 hour","1 cup jasmine rice","8 cups water or broth","1-inch ginger, sliced","Salt","Toppings: green onions, sesame oil, fried shallots, soy sauce, white pepper"],prep:"Drain soaked mung beans. Combine with rice and water in a large pot. Bring to a boil. Reduce heat and simmer uncovered 45–60 minutes stirring occasionally until rice and beans break down completely and porridge is silky and thick. Add ginger early and remove before serving. Season with salt. Serve in bowls with toppings on the side."},
      {name:"Wax Bean Salad",servings:"4 servings",ingredients:["500g wax beans, trimmed","½ red onion, thinly sliced","¼ cup Kalamata olives","¼ cup fresh parsley","Dressing: 3 tbsp olive oil, 2 tbsp red wine vinegar, 1 tsp Dijon, 1 tsp honey, salt and pepper"],prep:"Blanch wax beans in boiling salted water 3–4 minutes until tender-crisp. Transfer to ice water. Drain and dry. Combine with red onion, olives, and parsley. Whisk dressing and toss. Let sit 15 minutes before serving."},
      {name:"Runner Bean Stew",servings:"4 servings",ingredients:["500g fresh runner beans, sliced","1 onion, diced","3 garlic cloves","1 can crushed tomatoes","1 cup vegetable broth","1 tsp smoked paprika","3 tbsp olive oil","Salt and pepper","Fresh parsley"],prep:"Cook onion and garlic in olive oil until soft. Add smoked paprika. Add tomatoes, broth, and runner beans. Simmer 20–25 minutes until beans are very tender and sauce is thick. Season with salt and pepper. Garnish with parsley."},
      {name:"Dragon Tongue Bean Stir Fry",servings:"4 servings",ingredients:["500g dragon tongue or yellow wax beans, trimmed","3 garlic cloves, minced","1-inch ginger, grated","2 tbsp soy sauce","1 tbsp sesame oil","1 tsp chili paste","2 tbsp vegetable oil","Sesame seeds to garnish"],prep:"Blanch beans in boiling water 2 minutes. Drain. Heat oil in a wok over very high heat. Add beans and stir fry 3 minutes until lightly charred. Add garlic and ginger and cook 30 seconds. Add soy sauce, sesame oil, and chili paste. Toss until beans are coated. Transfer to a plate. Top with sesame seeds."}
    ]
  }
  ];



// ================================================================
//  TOGGLE CATEGORY — shows/hides recipe list under a card
// ================================================================
function toggleCategory(catId) {
  var ul = document.getElementById(catId);
  if (!ul) return;

  if (ul.style.display === 'block') {
    ul.style.display = 'none';
    return;
  }

  var cat = beans_data.find(function(c) { return c.id === catId; });
  if (!cat) return;

  if (ul.innerHTML === '') {
    cat.recipes.forEach(function(recipe, idx) {
      var li = document.createElement('li');
      li.className = 'browser-item';
      li.innerHTML =
        '<span class="browser-item-name">' + recipe.name + '</span>' +
        '<span class="browser-item-arrow">›</span>';
      li.addEventListener('click', function() {
        open_recipe_modal(recipe, catId);
      });
      ul.appendChild(li);
    });
  }

  ul.style.display = 'block';
}

