const pork_data = [

  // ===========================
  // 🥩 PORK CHOPS & STEAKS
  // ===========================
  {
    id: 'pork-chops',
    icon:"🥩", name:"Pork Chops & Steaks",
    desc:"Pan-seared pork chops, smothered pork chops, grilled pork steaks, stuffed chops, and classic skillet pork recipes.",
    recipes:[
      {id:"pc1", name:"Pan-Seared Pork Chops",servings:"4 servings",ingredients:["4 bone-in pork chops, 1 inch thick","2 tbsp olive oil","3 tbsp unsalted butter","4 garlic cloves, smashed","Fresh thyme and rosemary","Kosher salt and black pepper"],prep:"Remove pork chops from refrigerator 30 minutes before cooking. Pat completely dry with paper towels. Season generously on all sides with salt and pepper. Heat olive oil in a cast iron skillet over high heat until smoking. Place chops and sear without moving 4 minutes until a deep golden crust forms. Flip. Add butter, garlic, and herbs. Baste continuously with foaming butter 3–4 minutes. Internal temperature should reach 145°F (63°C). Rest 5 minutes before serving — the center will still be slightly pink which is perfectly safe and desirable."},
      {id:"pc2", name:"Smothered Pork Chops",servings:"4 servings",ingredients:["4 bone-in pork chops, 1 inch thick","1 large onion, thinly sliced","3 garlic cloves, minced","2 cups (480 ml) chicken broth","½ cup (120 ml) heavy cream","3 tbsp all-purpose flour","2 tbsp olive oil","2 tbsp butter","Fresh thyme","Salt and pepper"],prep:"Season pork chops with salt and pepper. Dredge in flour shaking off excess. Sear in hot oil in a skillet 3–4 minutes per side until golden. Remove. Cook onions in butter in same pan over medium heat 15 minutes until deeply caramelized. Add garlic and cook 1 minute. Sprinkle remaining flour over onions and stir 1 minute. Add broth and scrape up browned bits. Add cream and thyme. Return pork chops. Cover and simmer on low heat 20 minutes until very tender and gravy is thick."},
      {id:"pc3", name:"Grilled Pork Chops with Apple Glaze",servings:"4 servings",ingredients:["4 bone-in pork chops, 1¼ inch thick","Apple Glaze: 1 cup apple cider, 2 tbsp brown sugar, 1 tbsp Dijon mustard, 1 tbsp apple cider vinegar, 1 tsp fresh thyme","Dry Rub: 1 tsp garlic powder, 1 tsp onion powder, 1 tsp smoked paprika, salt and pepper","2 tbsp olive oil"],prep:"Mix dry rub and coat pork chops. Refrigerate 1 hour. Make glaze by simmering all glaze ingredients in a small saucepan until reduced by half and slightly syrupy. Brush chops with olive oil. Grill over medium-high heat 4–5 minutes per side. Brush generously with apple glaze in the last 2 minutes of cooking on each side. Internal temperature should reach 145°F (63°C). Rest 5 minutes."},
      {id:"pc4", name:"Stuffed Pork Chops",servings:"4 servings",ingredients:["4 thick-cut bone-in pork chops, 1½ inch thick","Stuffing: 1 cup breadcrumbs, ½ cup Parmesan, 2 garlic cloves, 2 tbsp fresh sage, 2 tbsp fresh parsley, 2 tbsp butter, salt and pepper","2 tbsp olive oil","1 cup (240 ml) chicken broth","Salt and pepper"],prep:"Cut a deep pocket into each pork chop through the side. Mix stuffing ingredients together. Fill each pocket generously. Secure with toothpicks. Season outside with salt and pepper. Sear in hot olive oil in an oven-safe skillet 3 minutes per side until golden. Add broth to pan. Transfer to oven at 375°F (190°C) and bake 20–25 minutes until internal temperature reaches 145°F (63°C). Rest 5 minutes. Remove toothpicks before serving."},
      {id:"pc5", name:"Honey Garlic Pork Chops",servings:"4 servings",ingredients:["4 boneless pork chops","Sauce: 4 tbsp honey, 4 garlic cloves minced, 2 tbsp soy sauce, 1 tbsp apple cider vinegar, 1 tsp red pepper flakes","2 tbsp olive oil","Salt and pepper","Fresh parsley"],prep:"Season pork chops with salt and pepper. Heat oil in a skillet over medium-high heat. Cook chops 4–5 minutes per side until cooked through and golden. Remove and rest. In same pan mix honey, garlic, soy sauce, and vinegar. Cook 2 minutes until slightly thickened. Return chops and coat in sauce for 1 minute per side. Garnish with parsley. Serve with sauce spooned over."},
      {id:"pc6", name:"Pork Schnitzel",servings:"4 servings",ingredients:["4 boneless pork chops, pounded to ¼-inch thickness","1 cup all-purpose flour","3 large eggs, beaten","1½ cups fine breadcrumbs","Salt and white pepper","Clarified butter or vegetable oil for frying","Lemon wedges and parsley to serve"],prep:"Season pork with salt and white pepper. Set up breading station: flour, beaten eggs, and fine breadcrumbs. Coat each piece in flour, then egg, then breadcrumbs. Pat gently — for authentic schnitzel do not press too hard so the breading puffs when fried. Heat ½ inch of clarified butter in a large skillet over medium-high heat. Fry schnitzel 3 minutes per side until deeply golden. Drain on a wire rack. Serve immediately with lemon wedges."},
      {id:"pc7", name:"Pork Chops with Mushroom Sauce",servings:"4 servings",ingredients:["4 bone-in pork chops","400 g (14 oz) cremini mushrooms, sliced","3 garlic cloves, minced","2 shallots, minced","½ cup (120 ml) white wine","1 cup (240 ml) heavy cream","2 tbsp butter","2 tbsp olive oil","Fresh thyme","Salt and pepper"],prep:"Season and sear pork chops in hot oil 4 minutes per side until golden. Remove. Cook mushrooms in butter over high heat until golden — about 5 minutes. Add shallots and garlic and cook 2 minutes. Add wine and reduce. Add cream and thyme. Simmer until thickened. Return pork chops and simmer on low 10 minutes until cooked through. Season with salt and pepper."},
      {id:"pc8", name:"Pork Chops with Cherry Sauce",servings:"4 servings",ingredients:["4 bone-in pork chops","Cherry Sauce: 2 cups fresh or frozen cherries, 1 shallot minced, ½ cup dry red wine, ½ cup chicken broth, 2 tbsp butter, 1 tbsp balsamic vinegar, 1 tbsp brown sugar, fresh thyme","2 tbsp olive oil","Salt and pepper"],prep:"Season and sear pork chops in hot oil 4 minutes per side until golden and cooked through at 145°F (63°C). Remove and rest. In same pan cook shallot 2 minutes. Add wine and reduce. Add cherries, broth, balsamic, and brown sugar. Simmer 8 minutes until cherries soften and sauce thickens. Swirl in butter. Spoon cherry sauce over rested pork chops."},
      {id:"pc9", name:"Pork Chops with Dijon Cream",servings:"4 servings",ingredients:["4 boneless pork chops","3 shallots, minced","3 garlic cloves, minced","½ cup (120 ml) white wine","1 cup (240 ml) heavy cream","2 tbsp whole grain Dijon mustard","2 tbsp butter","2 tbsp olive oil","Fresh tarragon","Salt and pepper"],prep:"Season chops and sear in hot oil 4–5 minutes per side. Remove. Cook shallots and garlic in butter 2 minutes. Add wine and reduce by half. Add cream and Dijon. Simmer until sauce thickens — about 5 minutes. Add tarragon. Return pork chops and heat through 2 minutes. Season with salt and pepper."},
      {id:"pc10", name:"Breaded Pork Cutlets",servings:"4 servings",ingredients:["4 boneless pork chops, pounded thin","1 cup flour","2 eggs beaten","1 cup panko breadcrumbs mixed with ½ cup Parmesan","Salt and pepper","3 tbsp olive oil","Lemon wedges and arugula salad to serve"],prep:"Season pork with salt and pepper. Coat in flour, then egg, then panko-Parmesan mixture pressing firmly. Pan fry in olive oil over medium heat 3–4 minutes per side until deeply golden and cooked through. Drain on wire rack. Serve topped with arugula dressed with lemon and olive oil. Finish with shaved Parmesan."},
      {id:"pc11", name:"Pork Chops with Apple and Onion",servings:"4 servings",ingredients:["4 bone-in pork chops","2 large apples, peeled, cored, and sliced","1 large onion, thinly sliced","2 tbsp butter","½ cup (120 ml) apple cider","½ cup (120 ml) chicken broth","1 tsp fresh thyme","1 tbsp brown sugar","2 tbsp olive oil","Salt and pepper"],prep:"Season and sear pork chops in hot oil 4 minutes per side. Remove. Melt butter in same pan. Cook onion over medium heat 10 minutes until soft. Add apple slices, brown sugar, and thyme and cook 3 minutes. Add cider and broth. Return pork chops. Cover and simmer 15 minutes until chops are cooked through and sauce has thickened slightly."},
      {id:"pc12", name:"Cajun Pork Chops",servings:"4 servings",ingredients:["4 boneless pork chops","Cajun Rub: 1 tbsp smoked paprika, 1 tsp garlic powder, 1 tsp onion powder, 1 tsp cumin, ½ tsp cayenne, ½ tsp dried thyme, salt and black pepper","2 tbsp olive oil","Lime wedges to serve"],prep:"Mix Cajun rub. Coat pork chops generously on all sides. Let sit 30 minutes at room temperature. Heat oil in a cast iron skillet over high heat. Sear chops 4–5 minutes per side until charred and cooked through at 145°F (63°C). Rest 5 minutes. Serve with lime wedges and your choice of sides."},
      {id:"pc13", name:"Pork Milanese",servings:"4 servings",ingredients:["4 boneless pork chops, pounded very thin","1 cup breadcrumbs","½ cup Parmesan, grated","2 eggs beaten","½ cup flour","3 tbsp olive oil","Salt and pepper","Arugula, cherry tomatoes, lemon"],prep:"Season pork with salt and pepper. Coat in flour, beaten eggs, then breadcrumbs mixed with Parmesan. Pan fry in olive oil over medium heat 3 minutes per side until golden. Drain on a wire rack. Serve topped with arugula and cherry tomatoes tossed in lemon and olive oil. Top with shaved Parmesan."},
      {id:"pc14", name:"Pork Chops with Balsamic Glaze",servings:"4 servings",ingredients:["4 bone-in pork chops","Balsamic Glaze: ½ cup balsamic vinegar, 2 tbsp honey, 2 garlic cloves minced, 1 tsp fresh rosemary","2 tbsp olive oil","Salt and pepper"],prep:"Make glaze by simmering balsamic, honey, garlic, and rosemary until reduced by half and syrupy — about 8 minutes. Season pork chops with salt and pepper. Sear in hot oil in a cast iron 4 minutes per side. Brush with balsamic glaze in the last 2 minutes of cooking on each side. Internal temperature 145°F (63°C). Rest 5 minutes. Drizzle remaining glaze over before serving."},
      {id:"pc15", name:"Pork Chops with Gravy",servings:"4 servings",ingredients:["4 bone-in pork chops","Gravy: 2 cups chicken broth, 3 tbsp all-purpose flour, 1 onion diced, 3 garlic cloves, 2 tbsp butter, fresh thyme, salt and pepper","½ cup flour for dredging","2 tbsp olive oil"],prep:"Season and dredge pork chops in flour. Sear in hot oil 4 minutes per side until golden. Remove. Cook onion in butter until soft. Add garlic 1 minute. Sprinkle flour over and stir 1 minute. Add broth and thyme gradually while stirring. Simmer until thickened. Return pork chops. Cover and simmer 20 minutes until tender and gravy is rich. Season with salt and pepper."}
    ]
  },

  // ===========================
  // 🍖 BBQ & SLOW COOKED PORK
  // ===========================
  {
    id: 'bbq',
    icon:"🍖", name:"BBQ & Slow Cooked Pork",
    desc:"Pulled pork, baby back ribs, pork shoulder, smoked pork, St. Louis ribs, and low and slow BBQ recipes.",
    recipes:[
      {id:"bbq1", name:"Pulled Pork",servings:"8 servings",ingredients:["4 lbs (1.8 kg) bone-in pork shoulder (Boston butt)","Dry Rub: 2 tbsp brown sugar, 1 tbsp salt, 1 tbsp smoked paprika, 1 tsp garlic powder, 1 tsp onion powder, 1 tsp black pepper, 1 tsp cumin, ½ tsp cayenne","1 cup (240 ml) apple cider vinegar","BBQ sauce for serving","Brioche buns and coleslaw"],prep:"Apply dry rub generously all over pork shoulder. Wrap and refrigerate overnight. Bring to room temperature 1 hour. Preheat oven to 300°F (150°C). Place pork fat side up in a roasting pan. Pour apple cider vinegar around the bottom. Cover tightly with foil. Roast 4–5 hours until internal temperature reaches 195–205°F (90–96°C) and meat is fall-apart tender. Rest 30 minutes. Shred with two forks discarding bone and excess fat. Mix with BBQ sauce and pan juices. Serve on brioche buns with coleslaw."},
      {id:"bbq2", name:"Baby Back Ribs",servings:"4 servings",ingredients:["2 racks baby back ribs","Dry Rub: 3 tbsp brown sugar, 1 tbsp salt, 1 tbsp smoked paprika, 1 tsp garlic powder, 1 tsp onion powder, 1 tsp black pepper, ½ tsp cayenne, ½ tsp cumin","1 cup (240 ml) apple juice","1½ cups BBQ sauce"],prep:"Remove membrane from the back of each rack by loosening an edge with a knife and pulling off with a paper towel. Apply dry rub generously on all sides. Wrap tightly in foil. Refrigerate overnight. Preheat oven to 275°F (135°C). Place foil-wrapped ribs on a baking sheet. Bake 2.5–3 hours until very tender. Open foil and pour in apple juice. Reseal and bake 30 more minutes. Unwrap and brush generously with BBQ sauce. Broil or grill 5–8 minutes until sauce caramelizes. Rest 10 minutes before cutting between bones."},
      {id:"bbq3", name:"St. Louis Spare Ribs",servings:"4 servings",ingredients:["2 racks St. Louis style spare ribs","Dry Rub: 3 tbsp brown sugar, 1 tbsp salt, 1 tbsp smoked paprika, 1 tsp garlic powder, 1 tsp black pepper, 1 tsp cumin, ½ tsp cayenne","Apple cider vinegar in a spray bottle","1½ cups BBQ sauce"],prep:"Remove membrane from ribs. Apply dry rub generously. Refrigerate overnight. Smoke at 225°F (107°C) using hickory or apple wood for 3 hours spritzing with apple cider vinegar every 45 minutes. Wrap in foil with a splash of apple juice. Smoke 2 more hours. Unwrap and brush with BBQ sauce. Smoke unwrapped 1 final hour until sauce sets and ribs are deeply mahogany. Rest 15 minutes before slicing. For oven method: bake foil-wrapped at 275°F (135°C) for 3 hours then broil with sauce."},
      {id:"bbq4", name:"Smoked Pork Shoulder",servings:"10 servings",ingredients:["8 lbs (3.6 kg) bone-in pork shoulder","Dry Rub: 3 tbsp salt, 2 tbsp coarsely ground black pepper, 1 tbsp garlic powder, 1 tbsp smoked paprika, 1 tsp cayenne","Apple wood or hickory chips"],prep:"Apply dry rub all over pork shoulder and refrigerate overnight uncovered so rub forms a crust. Set smoker to 225°F (107°C) with wood chips. Smoke fat side up 8–10 hours until internal temperature reaches 195–205°F (90–96°C). Wrap in butcher paper at 160°F (71°C) to push through the stall. Rest wrapped in a cooler 1–2 hours before pulling. The low slow smoke creates an incredible dark mahogany bark."},
      {id:"bbq5", name:"Slow Cooker Pulled Pork",servings:"8 servings",ingredients:["4 lbs (1.8 kg) boneless pork shoulder","Dry Rub: 2 tbsp brown sugar, 1 tbsp smoked paprika, 1 tsp garlic powder, 1 tsp onion powder, 1 tsp salt, 1 tsp black pepper, ½ tsp cayenne","1 cup (240 ml) chicken broth","½ cup (120 ml) apple cider vinegar","BBQ sauce for serving"],prep:"Apply dry rub all over pork. Place in slow cooker. Pour broth and vinegar around the meat. Cook on LOW 8–10 hours or HIGH 5–6 hours until completely fall-apart tender. Remove pork and shred with two forks. Skim fat from cooking juices. Mix shredded pork with cooking juices and BBQ sauce. Serve on buns with coleslaw."},
      {id:"bbq6", name:"Pork Ribs with Dry Rub",servings:"4 servings",ingredients:["2 racks pork ribs","Dry Rub: 3 tbsp brown sugar, 1 tbsp salt, 1 tbsp smoked paprika, 1 tsp garlic powder, 1 tsp onion powder, 1 tsp black pepper, 1 tsp cumin, 1 tsp dried mustard, ½ tsp cayenne"],prep:"Remove membrane from the back of ribs. Apply dry rub all over both sides pressing firmly. Refrigerate overnight. For oven: preheat to 275°F (135°C). Place ribs meat side down on a baking sheet. Cover tightly with foil. Bake 2.5–3 hours until tender when pierced with a fork. Uncover and broil 5 minutes for a crusty exterior. No BBQ sauce needed — the dry rub creates a beautiful crust."},
      {id:"bbq7", name:"Carolina Pulled Pork",servings:"8 servings",ingredients:["4 lbs (1.8 kg) bone-in pork shoulder","Dry Rub: 2 tbsp brown sugar, 1 tbsp salt, 1 tbsp smoked paprika, 1 tsp black pepper, 1 tsp garlic powder","Eastern Carolina Sauce: 1 cup apple cider vinegar, 1 tbsp brown sugar, 1 tsp red pepper flakes, 1 tsp black pepper, 1 tsp salt"],prep:"Apply dry rub and refrigerate overnight. Roast covered in oven at 300°F (150°C) for 5 hours or smoke at 225°F (107°C) until internal temperature reaches 205°F (96°C). Rest and shred. Make Carolina sauce by combining all ingredients. Toss pulled pork generously with the tangy vinegar sauce instead of sweet BBQ sauce. Serve on buns with coleslaw."},
      {id:"bbq8", name:"Pork Belly Burnt Ends",servings:"6 servings",ingredients:["3 lbs (1.4 kg) skinless pork belly, cut into 1½-inch cubes","Dry Rub: 2 tbsp brown sugar, 1 tbsp salt, 1 tbsp smoked paprika, 1 tsp garlic powder, 1 tsp black pepper","1 cup BBQ sauce","3 tbsp honey","2 tbsp butter"],prep:"Toss pork belly cubes with dry rub. Smoke at 250°F (120°C) for 3 hours until bark forms. Transfer to a disposable aluminum pan. Add BBQ sauce, honey, and butter. Cover tightly with foil. Return to smoker or oven at 250°F (120°C) for 1.5–2 hours. Uncover and cook 30 more minutes until sauce reduces and caramelizes and burnt ends are sticky and deeply glazed."},
      {id:"bbq9", name:"Pork Shoulder Carnitas",servings:"8 servings",ingredients:["4 lbs (1.8 kg) boneless pork shoulder, cut into 3-inch chunks","Juice of 2 oranges and 2 limes","4 garlic cloves, minced","1 tsp cumin","1 tsp oregano","1 tsp chili powder","Salt and pepper","3 tbsp lard or vegetable oil","Corn tortillas, cilantro, onion, and lime to serve"],prep:"Season pork with cumin, oregano, chili powder, salt, and pepper. Brown in lard in a Dutch oven in batches. Return all pork. Add orange juice, lime juice, and garlic. Bring to a boil. Cover and braise in oven at 300°F (150°C) for 3 hours until very tender. Remove pork and shred roughly. Spread on a baking sheet. Broil 5–8 minutes until edges are crispy. Serve in warm corn tortillas with cilantro, diced onion, and lime."},
      {id:"bbq10", name:"Ribs with Honey Bourbon Glaze",servings:"4 servings",ingredients:["2 racks baby back ribs","Dry Rub: 2 tbsp brown sugar, 1 tbsp salt, 1 tbsp smoked paprika, 1 tsp black pepper, 1 tsp garlic powder","Glaze: ½ cup bourbon, ½ cup honey, ¼ cup soy sauce, 2 tbsp Dijon mustard, 2 garlic cloves, 1 tbsp apple cider vinegar"],prep:"Apply dry rub to ribs. Wrap in foil. Bake at 275°F (135°C) for 2.5 hours. Make glaze by simmering all glaze ingredients until reduced by half and syrupy. Unwrap ribs. Brush generously with bourbon glaze. Broil or grill 6–8 minutes brushing with more glaze every 2 minutes until sticky and caramelized. Rest 10 minutes before cutting."},
      {id:"bbq11", name:"Pork Neck Bones",servings:"4 servings",ingredients:["3 lbs (1.4 kg) pork neck bones","1 large onion, diced","4 garlic cloves, minced","2 cups (480 ml) chicken broth","1 cup (240 ml) water","2 tbsp Worcestershire sauce","1 tsp smoked paprika","1 tsp garlic powder","Salt, pepper, and dried thyme","2 tbsp vegetable oil"],prep:"Season neck bones generously with salt, pepper, garlic powder, and paprika. Brown in batches in hot oil in a large Dutch oven. Remove. Cook onion and garlic until soft. Return neck bones. Add broth, water, Worcestershire sauce, and thyme. Bring to a boil. Cover and braise in oven at 325°F (165°C) for 2.5–3 hours until meat is very tender and falling off the bone. Serve over white rice with braising liquid spooned over."},
      {id:"bbq12", name:"Hawaiian Kalua Pork",servings:"8 servings",ingredients:["4 lbs (1.8 kg) bone-in pork shoulder","1 tbsp Hawaiian sea salt or kosher salt","1 tbsp liquid smoke","4 large ti leaves or banana leaves (or foil if unavailable)"],prep:"Pierce pork all over with a fork. Rub with salt. Drizzle liquid smoke over all sides. Wrap tightly in ti leaves or foil creating a sealed packet. Place in a slow cooker. Cook on LOW 16–20 hours or in oven at 325°F (165°C) for 5 hours until completely fall-apart tender. Shred with two forks. Mix with accumulated juices. Traditional Hawaiian kalua pork is cooked in an imu underground oven — this is the home version."},
      {id:"bbq13", name:"BBQ Pork Spare Ribs",servings:"4 servings",ingredients:["2 racks spare ribs","Dry Rub: 2 tbsp salt, 2 tbsp brown sugar, 1 tbsp smoked paprika, 1 tsp black pepper, 1 tsp garlic powder, 1 tsp onion powder, ½ tsp cayenne","1 cup apple juice","1½ cups BBQ sauce"],prep:"Remove membrane. Apply dry rub. Refrigerate overnight. Place ribs meat side down in a roasting pan. Add apple juice. Cover tightly with foil. Bake at 275°F (135°C) for 3–3.5 hours until tender. Remove foil. Brush generously with BBQ sauce. Increase heat to 375°F (190°C) and bake uncovered 20 minutes basting every 5 minutes until sauce is sticky and caramelized. Rest 10 minutes before cutting."},
      {id:"bbq14", name:"Mojo Pork",servings:"8 servings",ingredients:["4 lbs (1.8 kg) bone-in pork shoulder","Mojo Marinade: 1 cup sour orange juice or ½ cup lime and ½ cup orange juice, ¾ cup olive oil, 8 garlic cloves, 1 tsp cumin, 1 tsp dried oregano, 1 tsp salt, ½ tsp black pepper","Fresh cilantro and lime to serve"],prep:"Blend mojo marinade until smooth. Score pork deeply all over. Pour marinade over pork. Marinate at least 4 hours or overnight in the refrigerator. Bring to room temperature 1 hour. Roast at 325°F (165°C) for 4–5 hours until very tender and internal temperature reaches 195°F (90°C). Rest 30 minutes. Shred or slice. Serve with fresh cilantro, lime, black beans, and rice."},
      {id:"bbq15", name:"Country Style Pork Ribs",servings:"4 servings",ingredients:["3 lbs (1.4 kg) country style pork ribs","Dry Rub: 1 tbsp smoked paprika, 1 tsp garlic powder, 1 tsp onion powder, 1 tsp salt, 1 tsp black pepper, 1 tsp brown sugar","1 cup BBQ sauce","½ cup chicken broth"],prep:"Apply dry rub to country ribs. For slow cooker: place ribs and broth in slow cooker. Cook on LOW 6–8 hours until very tender. Drain liquid. Brush with BBQ sauce. Broil 5 minutes until caramelized. For oven: place in a roasting pan with broth. Cover and bake at 300°F (150°C) for 2.5 hours. Uncover, brush with BBQ sauce, and bake 30 more minutes."}
    ]
  },

  // ===========================
  // 🥓 BACON & SAUSAGE
  // ===========================
  {
    id: 'bacon and sausage',
    icon:"🥓", name:"Bacon & Sausage",
    desc:"Bacon dishes, Italian sausage, bratwurst, chorizo, andouille, and classic cured pork recipes.",
    recipes:[
      {id:"bs1", name:"Bacon Wrapped Dates",servings:"6 servings",ingredients:["24 Medjool dates, pitted","12 strips bacon, cut in half","4 oz (115 g) goat cheese or blue cheese","24 toothpicks"],prep:"Preheat oven to 400°F (200°C). Stuff each date with a small amount of goat cheese or blue cheese. Wrap each stuffed date with a half strip of bacon and secure with a toothpick. Place on a wire rack over a baking sheet. Bake 15–18 minutes until bacon is crispy and caramelized. The combination of sweet sticky dates, creamy tangy cheese, and salty crispy bacon is irresistible. Serve immediately."},
      {id:"bs2", name:"Sausage and Peppers",servings:"4 servings",ingredients:["1.5 lbs (680 g) Italian sausage links — sweet or hot","3 bell peppers — red, yellow, and green — sliced","1 large onion, sliced","4 garlic cloves, minced","1 can (14 oz) crushed tomatoes","½ cup (120 ml) dry white wine","2 tbsp olive oil","Salt, pepper, and dried oregano","Hoagie rolls or pasta to serve"],prep:"Brown sausages in olive oil in a large skillet over medium-high heat on all sides. Remove and slice into rounds or leave whole. Cook onion and peppers in same pan over medium heat 8 minutes until softened and slightly charred. Add garlic and oregano and cook 1 minute. Add wine and reduce. Add crushed tomatoes. Return sausage. Simmer covered 20 minutes. Season with salt and pepper. Serve on hoagie rolls or over pasta."},
      {id:"bs3", name:"Bratwurst with Beer and Onions",servings:"4 servings",ingredients:["6 bratwurst links","2 large onions, thinly sliced","3 garlic cloves, minced","2 cups (480 ml) German beer","2 tbsp butter","1 tsp caraway seeds","Salt and pepper","Hoagie buns, sauerkraut, and mustard to serve"],prep:"Melt butter in a large skillet or Dutch oven over medium heat. Cook onions slowly 15 minutes until golden. Add garlic and caraway seeds and cook 1 minute. Add beer and bring to a simmer. Add bratwurst. Simmer covered 20 minutes turning once. Remove bratwurst and grill or pan fry over high heat 3–4 minutes until nicely browned and skin is crispy. Continue reducing the beer onion mixture until thick. Serve brats on buns with beer onions, sauerkraut, and mustard."},
      {id:"bs4", name:"Chorizo and Potato Hash",servings:"4 servings",ingredients:["1 lb (450 g) Mexican or Spanish chorizo","4 medium potatoes, diced small","1 onion, diced","1 red bell pepper, diced","3 garlic cloves, minced","4 large eggs","2 tbsp olive oil","1 tsp cumin","Salt and pepper","Fresh cilantro and hot sauce to serve"],prep:"Cook potatoes in salted boiling water 5 minutes. Drain. Cook chorizo in a large skillet over medium-high heat breaking it up until browned. Remove. Cook onion and pepper in chorizo fat until soft. Add garlic and cumin 1 minute. Add potatoes and cook undisturbed 5 minutes until crispy. Return chorizo and toss. Create 4 wells in the hash. Crack an egg into each well. Cover and cook on medium-low heat until eggs are set to your liking. Garnish with cilantro."},
      {id:"bs5", name:"Italian Sausage Pasta",servings:"4 servings",ingredients:["400 g (14 oz) rigatoni or penne","1 lb (450 g) Italian sausage, casings removed","1 onion, diced","4 garlic cloves, minced","1 can (28 oz) crushed tomatoes","½ cup (120 ml) dry red wine","1 tsp dried oregano","Red pepper flakes","½ cup Parmesan","Fresh basil","2 tbsp olive oil"],prep:"Cook pasta until al dente. Brown sausage in olive oil over medium-high heat breaking it up. Remove. Cook onion in same pan until soft. Add garlic, oregano, and red pepper flakes 1 minute. Add wine and reduce. Add crushed tomatoes. Return sausage. Simmer 20 minutes. Toss with drained pasta. Top with Parmesan and fresh basil."},
      {id:"bs6", name:"Bacon Jam",servings:"2 cups",ingredients:["1 lb (450 g) thick-cut bacon, diced","2 large onions, diced","4 garlic cloves, minced","½ cup (120 ml) strong brewed coffee","½ cup (120 ml) apple cider vinegar","½ cup (120 ml) maple syrup","¼ cup (60 g) brown sugar","1 tsp smoked paprika","Pinch of cayenne"],prep:"Cook bacon in a heavy skillet over medium heat until crispy. Remove bacon and drain most of fat leaving 2 tbsp. Cook onions in bacon fat over medium-low heat 20 minutes until deeply golden. Add garlic and cook 2 minutes. Add all remaining ingredients including cooked bacon. Stir well. Simmer on low heat 45–60 minutes stirring occasionally until mixture is very thick and jammy. Cool slightly then pulse in a food processor 4–5 times for a spreadable consistency. Store refrigerated up to 2 weeks."},
      {id:"bs7", name:"Andouille and Red Bean Stew",servings:"6 servings",ingredients:["1 lb (450 g) andouille sausage, sliced","2 cans (14 oz each) red kidney beans, drained","1 onion, diced","3 celery stalks, diced","1 green bell pepper, diced","4 garlic cloves, minced","3 cups (720 ml) chicken broth","1 can (14 oz) diced tomatoes","1 tbsp Cajun seasoning","1 tsp dried thyme","Salt and pepper","Steamed white rice and green onions"],prep:"Cook andouille in a large pot until browned. Remove. Cook onion, celery, and pepper in sausage drippings until soft. Add garlic and Cajun seasoning and cook 1 minute. Return andouille. Add broth, diced tomatoes, beans, and thyme. Bring to a boil. Reduce and simmer 30 minutes until stew thickens. Mash some beans against the side of the pot for a creamier texture. Season with salt and pepper. Serve over white rice with green onions."},
      {id:"bs8", name:"Sausage Stuffed Mushrooms",servings:"6 servings",ingredients:["24 large cremini mushrooms, stems removed and chopped","½ lb (225 g) Italian sausage, casings removed","4 oz (115 g) cream cheese, softened","¼ cup Parmesan, grated","2 garlic cloves, minced","2 tbsp fresh parsley","Salt and pepper","Olive oil"],prep:"Preheat oven to 375°F (190°C). Cook sausage in a skillet breaking it up until browned. Add chopped mushroom stems and garlic and cook 3 minutes. Remove from heat. Mix with cream cheese, Parmesan, and parsley. Season with salt and pepper. Fill each mushroom cap generously. Drizzle with olive oil. Bake 20–25 minutes until mushrooms are tender and filling is golden."},
      {id:"bs9", name:"Chorizo Tacos",servings:"4 servings",ingredients:["1 lb (450 g) Mexican chorizo, casings removed","8 corn tortillas","Toppings: diced white onion, fresh cilantro, avocado, salsa verde, lime wedges, queso fresco"],prep:"Cook chorizo in a dry skillet over medium-high heat breaking it up until fully cooked and slightly crispy — about 8–10 minutes. Drain excess fat. Warm tortillas directly over a gas flame or in a dry skillet until lightly charred. Fill each with chorizo. Top with diced onion, cilantro, avocado, and a spoonful of salsa verde. Crumble queso fresco over top. Serve with lime wedges."},
      {id:"bs10", name:"Bacon Wrapped Pork Tenderloin",servings:"4 servings",ingredients:["2 pork tenderloins, about 1 lb each","8 strips bacon","Herb Rub: 3 garlic cloves minced, 1 tbsp fresh rosemary, 1 tbsp fresh thyme, 1 tbsp Dijon mustard, 2 tbsp olive oil, salt and pepper"],prep:"Preheat oven to 400°F (200°C). Mix herb rub and coat tenderloins all over. Lay 4 strips of bacon on a work surface overlapping slightly. Place tenderloin at the edge and roll tightly. Secure with toothpicks. Repeat with second tenderloin. Heat an oven-safe skillet over high heat. Sear all sides of wrapped tenderloins until bacon is browned — about 4 minutes. Transfer to oven and roast 15–18 minutes until internal temperature reaches 145°F (63°C). Rest 5 minutes. Slice and serve."},
      {id:"bs11", name:"German Sausage Platter",servings:"4 servings",ingredients:["2 bratwurst links","2 knockwurst links","2 weisswurst links","1 lb sauerkraut","2 large onions, sliced","1 cup (240 ml) German beer","2 tbsp butter","1 tsp caraway seeds","1 tbsp whole grain mustard","Pretzels and dark bread to serve"],prep:"Cook onions in butter over medium heat 20 minutes until caramelized. Add sauerkraut, beer, and caraway seeds. Simmer 15 minutes. Grill or pan fry all sausages over medium-high heat turning frequently until browned and cooked through. Arrange sausages on a platter over a bed of beer-braised sauerkraut and onions. Serve with whole grain mustard, pretzels, and dark bread."},
      {id:"bs12", name:"Breakfast Sausage Patties",servings:"4 servings",ingredients:["1 lb (450 g) ground pork","1 tsp dried sage","½ tsp dried thyme","½ tsp garlic powder","½ tsp onion powder","¼ tsp red pepper flakes","½ tsp brown sugar","1 tsp salt","½ tsp black pepper","1 tbsp maple syrup (optional)"],prep:"Mix ground pork with all seasonings and maple syrup if using. Mix well but do not overwork. Form into thin patties about 3 inches wide. Heat a skillet over medium heat. Cook patties 3–4 minutes per side until deeply golden and cooked through to 160°F (71°C). Do not press down — let them cook undisturbed for best browning. Rest 2 minutes before serving."},
      {id:"bs13", name:"Bacon Carbonara",servings:"4 servings",ingredients:["400 g (14 oz) spaghetti","200 g (7 oz) thick-cut bacon or pancetta, diced","4 large egg yolks plus 1 whole egg","100 g (3.5 oz) Pecorino Romano, finely grated","50 g (1.8 oz) Parmesan, finely grated","Freshly cracked black pepper","Salt for pasta water"],prep:"Cook spaghetti in salted water until al dente. While pasta cooks render bacon in a large skillet until crispy. Remove from heat. Whisk egg yolks, whole egg, and cheeses together with generous black pepper. Reserve 1 cup pasta water. Drain pasta and add to skillet off the heat. Add egg mixture tossing quickly while adding pasta water a splash at a time until sauce is creamy and coats the pasta. Serve immediately topped with extra black pepper."},
      {id:"bs14", name:"Sausage Roll",servings:"8 rolls",ingredients:["1 lb (450 g) Italian or breakfast sausage, casings removed","1 sheet puff pastry, thawed","1 onion, finely grated","2 garlic cloves, minced","1 tsp dried sage","½ tsp dried thyme","Salt and pepper","1 egg, beaten for egg wash","Mustard for serving"],prep:"Preheat oven to 400°F (200°C). Mix sausage meat with grated onion, garlic, sage, thyme, salt, and pepper. Roll puff pastry on a lightly floured surface into a rectangle. Spread sausage mixture along one long edge. Roll up tightly. Brush with egg wash. Slice into 8 pieces. Place on a lined baking sheet. Score tops with a knife. Brush again with egg wash. Bake 25–30 minutes until golden and crispy. Serve with mustard."},
      {id:"bs15", name:"Spicy Chorizo Pizza",servings:"4 servings",ingredients:["1 pizza dough, store-bought or homemade","½ lb (225 g) Spanish chorizo, thinly sliced","1 cup crushed San Marzano tomatoes","2 cups shredded mozzarella","1 red onion, thinly sliced","½ cup roasted red peppers","Fresh arugula and Parmesan to top after baking","Red pepper flakes and olive oil"],prep:"Preheat oven to 500°F (260°C) with a pizza stone or inverted baking sheet inside. Stretch dough to desired shape. Spread thin layer of crushed tomatoes. Top with mozzarella, chorizo, red onion, and roasted red peppers. Drizzle with olive oil. Bake 10–12 minutes until crust is charred and crispy and cheese is bubbling. Top immediately with fresh arugula and shaved Parmesan."}
    ]
  },

  // ===========================
  // 🫕 PORK ROASTS & BRAISES
  // ===========================
  {
    id: 'roasts',
    icon:"🫕", name:"Roasts & Braises",
    desc:"Pork loin roast, pork belly, osso buco, braised pork cheeks, stuffed pork loin, and Sunday roast pork.",
    recipes:[
      {id:"pr1", name:"Herb Roasted Pork Loin",servings:"6 servings",ingredients:["3 lbs (1.4 kg) boneless pork loin roast","Herb Rub: 4 garlic cloves minced, 2 tbsp fresh rosemary, 2 tbsp fresh thyme, 1 tbsp Dijon mustard, 3 tbsp olive oil, salt and pepper","Pan Sauce: 1 cup white wine, 1 cup chicken broth, 2 shallots, 2 tbsp butter"],prep:"Score top of pork loin. Apply herb rub all over and refrigerate overnight. Bring to room temperature 1 hour. Preheat oven to 450°F (230°C). Sear pork in a hot oven-safe skillet on all sides. Transfer to oven and roast 15 minutes. Reduce heat to 325°F (165°C) and continue roasting until internal temperature reaches 145°F (63°C) — about 45–60 minutes more. Rest 15 minutes. Make pan sauce with drippings, wine, broth, and shallots. Swirl in butter."},
      {id:"pr2", name:"Pork Belly",servings:"4 servings",ingredients:["2 lbs (900 g) skin-on pork belly","Brine: 4 cups water, 3 tbsp salt, 2 tbsp sugar, 4 garlic cloves, bay leaves, peppercorns","Glaze: 3 tbsp soy sauce, 2 tbsp honey, 1 tbsp rice vinegar, 1 tsp five spice","Salt and pepper"],prep:"Brine pork belly in salt and sugar solution overnight in refrigerator. Remove and pat completely dry. Score skin in a crosshatch pattern with a sharp knife — this is essential for crackling. Rub skin with salt only and refrigerate uncovered overnight to further dry the skin. Roast at 450°F (230°C) for 30 minutes until skin crackles and blisters. Reduce heat to 325°F (165°C) and roast 1.5 more hours until meat is very tender. Rest 15 minutes. Slice and brush meat side with glaze."},
      {id:"pr3", name:"Braised Pork Cheeks",servings:"4 servings",ingredients:["2 lbs (900 g) pork cheeks, trimmed","1 onion, diced","3 carrots, diced","3 celery stalks, diced","4 garlic cloves, minced","1 bottle (750 ml) dry red wine","2 cups (480 ml) chicken broth","2 tbsp tomato paste","Fresh thyme and rosemary","3 tbsp olive oil","Salt and pepper"],prep:"Season pork cheeks generously. Brown in batches in hot oil in a Dutch oven. Remove. Cook vegetables until soft. Add tomato paste 2 minutes. Add wine and reduce by half. Return pork. Add broth and herbs. Braise covered in oven at 300°F (150°C) for 3–4 hours until very tender and sauce is rich. Remove cheeks and reduce sauce until glossy. Serve over creamy polenta or mashed potatoes."},
      {id:"pr4", name:"Stuffed Pork Loin",servings:"6 servings",ingredients:["3 lbs (1.4 kg) boneless pork loin, butterflied open","Filling: 1 cup spinach sautéed, ½ cup sun-dried tomatoes, ½ cup Parmesan, 4 garlic cloves, 2 tbsp pine nuts, 2 tbsp fresh basil, salt and pepper","Kitchen twine","3 tbsp olive oil","Salt and pepper"],prep:"Butterfly pork loin by cutting horizontally almost all the way through and opening like a book. Pound to even thickness. Spread filling over interior leaving a ½-inch border. Roll tightly and tie with kitchen twine at 1-inch intervals. Season outside with salt and pepper. Sear on all sides in hot olive oil. Roast at 350°F (175°C) for 50–60 minutes until internal temperature reaches 145°F (63°C). Rest 15 minutes before slicing."},
      {id:"pr5", name:"Pork Osso Buco",servings:"4 servings",ingredients:["4 pork shank cross-cuts, 1½ inches thick","1 onion, diced","2 carrots, diced","2 celery stalks, diced","4 garlic cloves, minced","1 cup (240 ml) dry white wine","1 cup (240 ml) chicken broth","1 can (14 oz) crushed tomatoes","Fresh thyme and bay leaves","3 tbsp olive oil","Salt and pepper","Gremolata: lemon zest, garlic, fresh parsley"],prep:"Season pork shanks. Brown on all sides in hot oil in a Dutch oven. Remove. Cook vegetables until soft. Add wine and reduce by half. Add broth, tomatoes, and herbs. Return shanks. Braise covered at 325°F (165°C) for 2–2.5 hours until very tender. Make gremolata by mixing lemon zest, minced garlic, and parsley. Serve shanks over risotto or polenta topped with gremolata."},
      {id:"pr6", name:"Porchetta",servings:"8 servings",ingredients:["4 lbs (1.8 kg) pork belly, skin on","Filling: 6 garlic cloves, 2 tbsp fresh rosemary, 2 tbsp fresh sage, 1 tbsp fennel seeds, 1 tsp red pepper flakes, lemon zest, salt and pepper","Kitchen twine"],prep:"Score the pork belly skin. Open flat skin side down. Mix filling ingredients into a paste. Spread generously over the meat side. Roll tightly into a log skin side out. Tie with kitchen twine every 2 inches. Season outside with salt only. Refrigerate uncovered overnight to dry the skin. Roast at 450°F (230°C) for 30 minutes until skin blisters and crackles. Reduce to 325°F (165°C) and roast 1.5–2 more hours until very tender. Rest 20 minutes before slicing."},
      {id:"pr7", name:"Pork Tenderloin with Apple Pan Sauce",servings:"4 servings",ingredients:["2 pork tenderloins, about 1 lb each","2 apples, peeled and sliced","2 shallots, minced","1 cup (240 ml) apple cider","½ cup (120 ml) chicken broth","2 tbsp butter","Fresh thyme","Salt and pepper","2 tbsp olive oil"],prep:"Season tenderloins with salt and pepper. Sear in hot oil in an oven-safe skillet on all sides. Transfer to oven at 400°F (200°C) and roast 15–18 minutes until internal temperature reaches 145°F (63°C). Rest 5 minutes. In same skillet cook shallots in butter 2 minutes. Add apples and cook 3 minutes. Add cider and broth. Reduce until slightly syrupy. Add thyme and season with salt and pepper. Slice tenderloin and serve with apple pan sauce."},
      {id:"pr8", name:"Slow Roasted Pork Shoulder",servings:"8 servings",ingredients:["5 lbs (2.3 kg) bone-in pork shoulder","Paste: 6 garlic cloves, 2 tbsp fresh rosemary, 2 tbsp fresh thyme, 2 tbsp olive oil, 1 tsp fennel seeds, salt and pepper","1 cup (240 ml) white wine","1 cup (240 ml) chicken broth"],prep:"Make herb paste in a food processor. Score pork deeply all over with a knife. Rub paste into cuts and all over the exterior. Refrigerate overnight. Bring to room temperature 1 hour. Place in a roasting pan. Pour wine and broth around the base. Roast covered at 325°F (165°C) for 4–5 hours until very tender and internal temperature reaches 195°F (90°C). Uncover last 30 minutes to crisp the exterior. Rest 20 minutes before serving."},
      {id:"pr9", name:"Pork Belly Ramen",servings:"4 servings",ingredients:["1 lb (450 g) pork belly, whole piece","Chashu Marinade: 4 tbsp soy sauce, 3 tbsp mirin, 2 tbsp sake, 2 tbsp sugar, 3 garlic cloves, 2 green onions","Broth: 6 cups chicken broth, 4 tbsp white miso, 2 tbsp soy sauce, 1 tbsp sesame oil","4 portions ramen noodles","Soft boiled eggs, nori, corn, bamboo shoots, green onions"],prep:"Roll pork belly and tie with twine. Brown in a pan. Place in a zip bag or container with chashu marinade. Sous vide at 167°F (75°C) for 12 hours or braise covered in oven at 275°F (135°C) for 3 hours. Cool and refrigerate. Slice and pan-fry until caramelized. Make broth by combining chicken broth, miso, soy sauce, and sesame oil. Cook noodles. Build ramen bowls with noodles, hot broth, chashu slices, soft boiled eggs, and toppings."},
      {id:"pr10", name:"Pork Crown Roast",servings:"8 servings",ingredients:["One crown roast of pork ribs (8–10 ribs), shaped by your butcher","Herb Butter: 4 tbsp butter softened, 4 garlic cloves, 2 tbsp rosemary, 2 tbsp sage, salt and pepper","Stuffing: 3 cups breadcrumbs, 1 onion, 3 celery stalks, 4 tbsp butter, apple, fresh herbs, chicken broth"],prep:"Preheat oven to 450°F (230°C). Apply herb butter all over roast. Season generously. Roast 20 minutes until browned. Make stuffing and fill center of crown. Reduce heat to 325°F (165°C). Continue roasting until internal temperature reaches 145°F (63°C) — about 20 minutes per pound from the start. Rest 20 minutes before carving between ribs."},
      {id:"pr11", name:"Pork Belly Bao Buns",servings:"4 servings",ingredients:["1 lb (450 g) pork belly, sliced into 1-inch thick slabs","Marinade: 3 tbsp soy sauce, 2 tbsp hoisin, 1 tbsp sesame oil, 1 tbsp honey, 3 garlic cloves, 1 tsp five spice","8 store-bought steamed bao buns","Quick pickled cucumbers: cucumber sliced, rice vinegar, sugar, salt","Hoisin sauce, sriracha, cilantro, and green onions"],prep:"Marinate pork belly at least 2 hours. Cook in a 375°F (190°C) oven for 30 minutes basting with marinade twice. Slice. Heat bao buns by steaming 2 minutes. Open each bun and fill with glazed pork belly slices, pickled cucumber, hoisin sauce, sriracha, cilantro, and green onions."},
      {id:"pr12", name:"Braised Pork with Sauerkraut",servings:"6 servings",ingredients:["3 lbs (1.4 kg) pork shoulder, cut into large pieces","2 lbs (900 g) sauerkraut, drained","1 large onion, diced","3 garlic cloves, minced","1 cup (240 ml) chicken broth","1 cup (240 ml) dry white wine","1 tsp caraway seeds","2 bay leaves","Salt and pepper","3 tbsp vegetable oil"],prep:"Season pork and brown in batches in hot oil in a Dutch oven. Remove. Cook onion until soft. Return pork. Add sauerkraut, broth, wine, caraway seeds, and bay leaves. Bring to a boil. Cover and braise in oven at 325°F (165°C) for 2.5–3 hours until pork is very tender. Remove bay leaves. Adjust seasoning. Serve with boiled potatoes or egg noodles."},
      {id:"pr13", name:"Pork Roast with Crackling",servings:"6 servings",ingredients:["4 lbs (1.8 kg) bone-in pork loin with skin","2 tbsp coarse salt for skin","Herb Rub for meat: 4 garlic cloves, 2 tbsp fresh rosemary, 1 tbsp fennel seeds, 2 tbsp olive oil, salt and pepper"],prep:"Score pork skin very deeply in a crosshatch pattern going all the way through the fat to the meat. Rub coarse salt vigorously into all the scores. Refrigerate uncovered overnight. Pat skin dry. Rub herb mixture on the meat side and in the scores. Roast at 450°F (230°C) for 30 minutes until skin crackles and blisters. Reduce to 325°F (165°C) and roast until internal temperature reaches 145°F (63°C). Rest 20 minutes. The crackling should be shatteringly crispy."},
      {id:"pr14", name:"Pork and Apple Cider Braise",servings:"6 servings",ingredients:["3 lbs (1.4 kg) pork shoulder, cut into large pieces","2 cups (480 ml) apple cider","1 cup (240 ml) chicken broth","2 apples, peeled and chopped","1 onion, diced","4 garlic cloves, minced","Fresh thyme and rosemary","2 tbsp Dijon mustard","3 tbsp olive oil","Salt and pepper"],prep:"Season pork and brown in batches in hot oil. Remove. Cook onion until soft. Add garlic 1 minute. Add Dijon and stir. Add cider, broth, apples, and herbs. Return pork. Bring to a boil. Cover and braise in oven at 325°F (165°C) for 2.5 hours until very tender. Remove pork and blend sauce until smooth. Season with salt and pepper. Return pork to serve."},
      {id:"pr15", name:"Vietnamese Caramel Pork",servings:"4 servings",ingredients:["2 lbs (900 g) pork belly or shoulder, cut into 2-inch cubes","Caramel: ½ cup sugar, 3 tbsp water","Braising Liquid: 3 tbsp fish sauce, 2 tbsp soy sauce, 2 cups (480 ml) coconut water, 3 garlic cloves, 1-inch ginger, black pepper","4 soft boiled eggs, halved","Fresh cilantro and steamed rice to serve"],prep:"Make caramel by cooking sugar and water over medium-high heat without stirring until deep amber. Add braising liquid carefully — it will sizzle. Add pork and bring to a boil. Skim foam. Cover and simmer on low heat 1.5 hours until pork is very tender and sauce is thick and mahogany colored. Add soft boiled eggs in the last 15 minutes. Serve over steamed rice garnished with cilantro."}
    ]
  },

  // ===========================
  // 🌍 INTERNATIONAL PORK
  // ===========================
  {
    id: 'international',
    icon:"🌍", name:"International Pork",
    desc:"Tonkatsu, char siu, al pastor, pernil, lechon kawali, pork gyoza, and global pork recipes from around the world.",
    recipes:[
      {id:"ip1", name:"Tonkatsu",servings:"4 servings",ingredients:["4 boneless pork loin chops, ¾ inch thick","1 cup all-purpose flour","2 large eggs beaten","1½ cups panko breadcrumbs","Salt and pepper","Vegetable oil for frying","Tonkatsu Sauce: ¼ cup Worcestershire sauce, 3 tbsp ketchup, 1 tbsp soy sauce, 1 tbsp sugar","Shredded cabbage and steamed rice to serve"],prep:"Pound pork chops to even ¾-inch thickness. Make shallow cuts around the edges to prevent curling. Season with salt and pepper. Coat in flour, then beaten egg, then panko pressing firmly. Heat 1 inch of oil to 340°F (170°C). Fry 4–5 minutes per side until deep golden and cooked through to 145°F (63°C). Drain on a wire rack — never paper towels as steam makes breading soggy. Slice into strips. Mix tonkatsu sauce. Serve over shredded cabbage with steamed rice."},
      {id:"ip2", name:"Char Siu (Chinese BBQ Pork)",servings:"4 servings",ingredients:["2 lbs (900 g) pork shoulder or tenderloin, cut into long strips","Marinade: 4 tbsp hoisin sauce, 3 tbsp soy sauce, 3 tbsp honey, 2 tbsp oyster sauce, 2 tbsp Chinese rose wine or dry sherry, 1 tsp five spice, 3 garlic cloves, red food coloring (optional)"],prep:"Mix marinade and coat pork strips thoroughly. Marinate at least overnight or up to 2 days. Preheat oven to 425°F (220°C). Place pork on a rack over a foil-lined pan with water in the bottom. Roast 20 minutes. Flip and brush with remaining marinade. Roast 15 more minutes. Brush again and broil 3–5 minutes until edges are slightly charred and caramelized. Rest 10 minutes before slicing. The pork should be sticky, caramelized, and deeply flavorful."},
      {id:"ip3", name:"Al Pastor Pork",servings:"6 servings",ingredients:["3 lbs (1.4 kg) pork shoulder, thinly sliced","Marinade: 3 dried guajillo chiles, 2 dried ancho chiles, 4 chipotle peppers in adobo, ½ pineapple juice, 4 garlic cloves, 1 tsp cumin, 1 tsp oregano, 1 tsp achiote paste, salt","1 pineapple, sliced","Corn tortillas, cilantro, diced onion, and lime to serve"],prep:"Toast dried chiles and soak in hot water 20 minutes. Blend with chipotles, pineapple juice, garlic, and spices. Marinate pork overnight. Stack marinated pork slices vertically with pineapple slices between layers — traditional al pastor is cooked on a trompo spit. For home cooking grill over high heat in batches or broil 5–6 minutes per side. Chop and serve in warm corn tortillas with cilantro, onion, fresh pineapple, and lime."},
      {id:"ip4", name:"Pernil (Puerto Rican Roast Pork)",servings:"10 servings",ingredients:["6 lbs (2.7 kg) bone-in pork shoulder with skin","Adobo Paste: 8 garlic cloves, 2 tbsp dried oregano, 2 tbsp olive oil, 1 tbsp salt, 1 tbsp black pepper, 1 tsp cumin, 1 tbsp white wine vinegar","Sofrito: ½ cup green peppers, ½ cup cilantro, 4 garlic cloves, 1 small onion"],prep:"Score pork skin deeply. Make deep cuts all over the meat. Blend adobo paste and sofrito together. Push paste deep into all cuts. Coat entire exterior. Marinate overnight. Bring to room temperature 1 hour. Roast at 400°F (200°C) for 1 hour with skin up. Reduce to 300°F (150°C). Cover with foil and braise 3–4 hours until fork tender. Uncover. Increase to 425°F (220°C) and roast 20–30 minutes until skin crackles and becomes chicharrón-style crispy."},
      {id:"ip5", name:"Pork Gyoza",servings:"4 servings",ingredients:["30 round gyoza wrappers","Filling: ½ lb (225 g) ground pork, 1 cup napa cabbage finely chopped and squeezed dry, 2 green onions, 3 garlic cloves minced, 1 tbsp fresh ginger, 2 tbsp soy sauce, 1 tbsp sesame oil, 1 tbsp sake, salt and pepper","Vegetable oil for frying","Dipping Sauce: 3 tbsp soy sauce, 2 tbsp rice vinegar, 1 tsp sesame oil, chili oil"],prep:"Mix all filling ingredients until well combined. Place a teaspoon of filling in the center of each wrapper. Wet edges with water. Fold in half making pleats along one edge to seal into a crescent shape. Heat oil in a flat-bottomed skillet over medium-high heat. Place gyoza flat side down. Cook undisturbed until bottoms are golden — about 3 minutes. Add ¼ cup water to the pan. Cover immediately and steam 3 minutes. Uncover and cook until water evaporates. Serve with dipping sauce."},
      {id:"ip6", name:"Lechon Kawali",servings:"4 servings",ingredients:["2 lbs (900 g) pork belly, skin on","4 cups water","1 tbsp salt","1 bay leaf","1 tbsp black peppercorns","4 garlic cloves","Oil for deep frying","Lechon sauce or vinegar dipping sauce to serve"],prep:"Simmer pork belly in water with salt, bay leaf, peppercorns, and garlic for 45–60 minutes until just tender. Remove and cool completely — refrigerate overnight uncovered to completely dry the skin. Cut into serving portions. Deep fry in oil at 375°F (190°C) for 8–10 minutes until skin blisters and crackles into perfect chicharrón and pork is deep golden. Drain on a wire rack. Serve with lechon sauce."},
      {id:"ip7", name:"Moo Shu Pork",servings:"4 servings",ingredients:["1 lb (450 g) pork tenderloin, thinly sliced","3 cups napa cabbage, shredded","1 cup wood ear mushrooms, soaked and sliced","3 eggs scrambled","3 garlic cloves, minced","1 tbsp fresh ginger","Sauce: 3 tbsp hoisin, 2 tbsp soy sauce, 1 tbsp sesame oil, 1 tsp sugar","Mandarin pancakes or flour tortillas","Hoisin sauce and green onions for serving"],prep:"Stir fry pork in a hot wok until cooked. Remove. Scramble eggs lightly and remove. Add garlic and ginger. Add mushrooms and cabbage and stir fry 3 minutes. Return pork and eggs. Add sauce and toss. Serve with warm mandarin pancakes or tortillas. Spread hoisin on each pancake, add moo shu pork, and top with green onions. Roll and eat."},
      {id:"ip8", name:"Cuban Lechón",servings:"8 servings",ingredients:["4 lbs (1.8 kg) bone-in pork shoulder","Mojo: 1 cup sour orange juice or lime juice, ½ cup olive oil, 8 garlic cloves, 1 tsp cumin, 1 tsp oregano, salt and pepper","Black beans and rice for serving"],prep:"Score pork and make deep cuts all over. Blend mojo ingredients and pour over pork. Marinate overnight. Roast at 325°F (165°C) for 4–5 hours until very tender at 195°F (90°C). Rest 20 minutes. Shred or pull apart. Serve with black beans and rice. Also excellent sliced and served with mojo drizzled over."},
      {id:"ip9", name:"Pork Gyros",servings:"4 servings",ingredients:["1.5 lbs (680 g) pork shoulder, thinly sliced","Marinade: 3 tbsp olive oil, juice of 1 lemon, 4 garlic cloves, 1 tbsp dried oregano, 1 tsp cumin, salt and pepper","Tzatziki: 1 cup Greek yogurt, 1 cucumber grated, 2 garlic cloves, dill, lemon juice","4 pita breads","Tomatoes, red onion, and lettuce"],prep:"Marinate pork at least 2 hours. Cook in a very hot skillet or grill pan in batches until slightly charred and cooked through. Slice thin. Make tzatziki. Warm pita bread. Top with pork, tzatziki, tomatoes, red onion, and lettuce. Wrap and serve."},
      {id:"ip10", name:"Pork Katsu Curry",servings:"4 servings",ingredients:["4 pork loin chops, pounded thin, breaded and fried (see Tonkatsu recipe)","Japanese Curry Sauce: 2 tbsp butter, 1 onion diced, 2 carrots diced, 2 potatoes cubed, 2 cups chicken broth, 2 boxes Japanese curry roux, 1 tbsp soy sauce","Steamed rice"],prep:"Make tonkatsu as in the recipe above. Make curry sauce by cooking onion in butter until golden. Add carrots and potatoes. Add broth and simmer 20 minutes until tender. Remove from heat and add curry roux blocks stirring until dissolved. Return to low heat and simmer 10 minutes until thick. Slice pork tonkatsu and serve over rice with curry sauce poured alongside."},
      {id:"ip11", name:"Chicharrones",servings:"4 servings",ingredients:["2 lbs (900 g) pork skin, cut into 3-inch squares","2 tbsp salt","1 tsp baking powder","Vegetable oil for frying","Lime juice and hot sauce to serve"],prep:"Simmer pork skin in salted water 1 hour until soft. Drain and dry completely. Season with salt and baking powder — the baking powder helps puffing. Refrigerate uncovered overnight to completely dry. Deep fry small batches in oil at 400°F (200°C) for 3–5 minutes until they puff dramatically and are very crispy. Drain immediately. Season with salt. Squeeze lime juice over. Serve with hot sauce. They deflate quickly so serve immediately."},
      {id:"ip12", name:"Thai Basil Pork",servings:"4 servings",ingredients:["1 lb (450 g) ground pork","3 garlic cloves, minced","3 Thai red chilies, sliced","1 large handful fresh Thai basil","Sauce: 2 tbsp oyster sauce, 1 tbsp fish sauce, 1 tbsp soy sauce, 1 tsp sugar","2 tbsp vegetable oil","Steamed rice and fried egg to serve"],prep:"Mix sauce ingredients. Heat oil in a wok over very high heat until smoking. Add garlic and chilies and stir fry 30 seconds. Add ground pork and cook on high heat without stirring until bottom browns. Break up and stir fry until cooked through and slightly crispy. Add sauce and toss. Remove from heat and fold in fresh Thai basil. Serve immediately over steamed rice with a crispy fried egg on top."},
      {id:"ip13", name:"Filipino Adobo Pork",servings:"4 servings",ingredients:["2 lbs (900 g) pork shoulder, cut into 2-inch cubes","½ cup (120 ml) soy sauce","½ cup (120 ml) white cane vinegar","6 garlic cloves, smashed","1 tsp whole black peppercorns","3 bay leaves","1 tbsp sugar","2 tbsp vegetable oil"],prep:"Combine soy sauce, vinegar, garlic, peppercorns, and bay leaves. Add pork and marinate 30 minutes. Bring to a boil. Reduce and simmer covered 40 minutes. Remove pork. Reduce sauce by half over high heat. Heat oil in a skillet and fry pork until crispy and golden. Pour reduced sauce over pork. The tangy, savory, slightly caramelized sauce is the defining characteristic of Filipino adobo. Serve over steamed white rice."},
      {id:"ip14", name:"Pork Souvlaki",servings:"4 servings",ingredients:["1.5 lbs (680 g) pork shoulder or tenderloin, cubed","Marinade: 3 tbsp olive oil, juice of 2 lemons, 4 garlic cloves, 1 tbsp dried oregano, salt and pepper","Tzatziki: 1 cup Greek yogurt, 1 cucumber grated, 2 garlic cloves, dill, lemon juice","Pita, tomatoes, red onion, lettuce"],prep:"Marinate pork cubes at least 2 hours. Thread onto soaked wooden skewers. Grill over high heat 10–12 minutes turning regularly until cooked through and charred. Make tzatziki. Serve skewers in warm pita with tzatziki, tomatoes, red onion, and lettuce."},
      {id:"ip15", name:"Dong Po Rou (Red Braised Pork Belly)",servings:"4 servings",ingredients:["2 lbs (900 g) pork belly, cut into 2-inch squares","½ cup (120 ml) soy sauce","¼ cup (60 ml) dark soy sauce","½ cup (120 ml) Shaoxing wine","3 tbsp sugar or rock sugar","3 garlic cloves","3 green onions","3 slices fresh ginger","2 cups (480 ml) water or broth"],prep:"Blanch pork belly 5 minutes. Drain and rinse. Place in a clay pot or Dutch oven skin side down. Add all remaining ingredients. Bring to a boil. Reduce to the lowest heat. Cover and braise 1.5–2 hours turning once until pork is incredibly tender and sauce is thick and glossy. The pork belly should be meltingly soft and deeply soy-caramel flavored. Serve over steamed rice."}
    ]
  },

  // ===========================
  // 🥪 PORK SANDWICHES & WRAPS
  // ===========================
  {
    id: 'sandwiches',
    icon:"🥪", name:"Sandwiches & Wraps",
    desc:"Pulled pork sandwiches, Cuban sandwiches, banh mi, pork belly bao, Italian beef, and pork wraps.",
    recipes:[
      {id:"ps1", name:"Cuban Sandwich",servings:"4 servings",ingredients:["4 Cuban or hoagie rolls","½ lb (225 g) roasted pork loin or mojo pork, thinly sliced","½ lb (225 g) deli ham, thinly sliced","4 oz (115 g) Swiss cheese, sliced","Dill pickles, sliced","Yellow mustard","Butter for pressing"],prep:"Spread yellow mustard on both sides of each roll. Layer ham, roasted pork, Swiss cheese, and pickles inside each roll. Butter the outside of the sandwich. Press in a sandwich press or heavy skillet weighted down with another pan over medium heat 4–5 minutes per side until bread is golden and crispy and cheese is fully melted. The sandwich should be flat and compressed. Cut diagonally and serve immediately."},
      {id:"ps2", name:"Banh Mi",servings:"4 servings",ingredients:["4 French baguettes or hoagie rolls","Char Siu pork or Vietnamese pork meatballs","Pickled vegetables: 1 cup daikon and 1 cup carrots julienned, ½ cup rice vinegar, 2 tbsp sugar, 1 tsp salt","Cucumber, thinly sliced","Fresh cilantro and jalapeño slices","Sriracha mayo: ½ cup mayo, 2 tbsp sriracha"],prep:"Make pickled vegetables by soaking daikon and carrots in vinegar, sugar, and salt solution 1 hour. Prepare char siu pork or meatballs. Make sriracha mayo. Split rolls and spread with sriracha mayo. Layer with pork, pickled vegetables, cucumber slices, cilantro, and jalapeño. The contrast of warm savory pork, tangy pickled vegetables, and fresh herbs is the essence of banh mi."},
      {id:"ps3", name:"Pulled Pork Sandwich",servings:"6 servings",ingredients:["3 cups pulled pork (see pulled pork recipe)","BBQ sauce","6 brioche buns","Coleslaw: 3 cups cabbage shredded, ½ cup mayo, 2 tbsp apple cider vinegar, 1 tbsp sugar, salt and pepper","Dill pickles"],prep:"Make pulled pork as in the recipe. Mix pulled pork with BBQ sauce until well coated. Make coleslaw by combining all ingredients and refrigerating 30 minutes. Toast brioche buns. Pile pulled pork generously on the bottom bun. Top with coleslaw and dill pickles. Add top bun. Serve immediately. The coleslaw on the sandwich is essential — it provides creamy crunch against the tender smoky pork."},
      {id:"ps4", name:"Italian Pork Sandwich",servings:"4 servings",ingredients:["1.5 lbs (680 g) Italian sausage or pork tenderloin, cooked and sliced","4 hoagie rolls","Giardiniera (Italian pickled vegetables)","1 cup banana peppers","Provolone cheese, sliced","Olive oil and oregano"],prep:"Cook sausage or tenderloin. Drizzle inside of rolls with olive oil and sprinkle with dried oregano. Layer provolone on the bottom. Add hot sausage or pork. Top with giardiniera and banana peppers. Press together. The giardiniera provides the essential briny, spicy, crunchy contrast to the rich pork."},
      {id:"ps5", name:"Pork Belly Banh Mi",servings:"4 servings",ingredients:["1 lb (450 g) pork belly, braised or roasted and sliced","4 French baguette pieces","Pickled daikon and carrots","Cucumber slices","Fresh cilantro","Jalapeño","Sriracha mayo","Pâté (optional, for authenticity)"],prep:"Slice braised or roasted pork belly into thin strips. Heat in a pan until caramelized. Split baguettes. Spread with sriracha mayo and pâté if using. Layer with warm pork belly slices, pickled vegetables, cucumber, cilantro, and jalapeño. Press together. The richness of the pork belly is balanced by the tangy pickled vegetables and fresh herbs."},
      {id:"ps6", name:"Mojo Pork Tacos",servings:"4 servings",ingredients:["2 cups mojo pork, shredded (see pernil or mojo pork recipe)","8 corn tortillas","Black beans, warmed","White rice","Toppings: pickled red onions, fresh cilantro, avocado, lime crema, lime wedges"],prep:"Warm shredded mojo pork in a pan until slightly crispy on the edges. Warm tortillas. Build tacos with pork, black beans, and rice. Top with pickled red onions, cilantro, and avocado. Drizzle with lime crema. Serve with lime wedges. The citrusy garlicky mojo pork is exceptional in taco form."},
      {id:"ps7", name:"Pork Katsu Sandwich",servings:"4 servings",ingredients:["4 boneless pork chops, pounded thin and breaded","Tonkatsu sauce","4 thick slices soft white bread or milk bread","Shredded cabbage","Japanese mayo","Salt"],prep:"Fry breaded pork chops as in the Tonkatsu recipe until deeply golden. The key to a Japanese katsu sandwich is very fresh soft white bread. Spread Japanese mayo on both sides of each bread slice. Place shredded cabbage on the bottom. Add hot tonkatsu and drizzle generously with tonkatsu sauce. Top with second slice. Press firmly. Cut into thirds — the Japanese katsu sando is always cut into thirds revealing the layers. Wrap tightly in plastic for a few minutes for classic katsu sando texture."},
      {id:"ps8", name:"Vietnamese Pork Meatball Banh Mi",servings:"4 servings",ingredients:["Meatballs: 1 lb (450 g) ground pork, 2 garlic cloves, 2 green onions, 1 tbsp fish sauce, 1 tbsp lemongrass minced, 1 tsp sugar, 1 tsp cornstarch","4 baguette pieces","Pickled daikon and carrots","Cucumber, cilantro, jalapeño","Sriracha mayo"],prep:"Mix meatball ingredients until smooth. Roll into small balls. Bake at 400°F (200°C) for 15 minutes or pan fry in oil until cooked through and golden. Build banh mi with sriracha mayo, warm meatballs, pickled vegetables, cucumber, cilantro, and jalapeño."},
      {id:"ps9", name:"Pork Rib Sandwich",servings:"4 servings",ingredients:["8 baby back rib portions, bones removed or boneless country ribs","BBQ sauce","4 brioche buns","Coleslaw","Pickles","Butter"],prep:"Cook ribs until very tender using the baby back rib recipe. Remove bones if present. Brush ribs generously with BBQ sauce and broil or grill until caramelized. Toast buttered buns. Place saucy ribs on the bottom bun. Top with coleslaw and pickles. Add top bun. Serve immediately — have lots of napkins ready."},
      {id:"ps10", name:"BLT with Thick Bacon",servings:"2 servings",ingredients:["6 strips thick-cut bacon","4 slices sourdough or artisan bread, toasted","2 leaves butter lettuce","2 thick tomato slices","3 tbsp mayonnaise","Salt and black pepper"],prep:"Cook thick-cut bacon in a cold skillet over medium heat turning occasionally until very crispy but not burnt — about 8–10 minutes. Drain on a wire rack. Toast bread. Spread mayo generously on both slices. Season tomato slices with salt and pepper. Layer lettuce, tomato, and crispy bacon on one slice. Top with second slice. Slice diagonally. The secret to a great BLT is thick-cut bacon, perfectly ripe tomatoes, and enough mayo."},
      {id:"ps11", name:"Pork Carnitas Burrito",servings:"4 servings",ingredients:["2 cups carnitas (see pork shoulder carnitas recipe)","4 large flour tortillas, warmed","2 cups cilantro lime rice","1 can (14 oz) black beans, seasoned","1 cup pico de gallo","2 avocados, diced or guacamole","Sour cream","Shredded cheddar","Lime wedges"],prep:"Warm carnitas in a skillet until crispy on edges. Warm tortillas. Lay each tortilla flat. Layer rice, beans, carnitas, pico de gallo, avocado, sour cream, and cheese in the center. Fold sides in and roll tightly from bottom to top. For a crispy burrito toast in a dry skillet 1–2 minutes per side until golden."},
      {id:"ps12", name:"Pork Banh Mi with Lemongrass",servings:"4 servings",ingredients:["1.5 lbs (680 g) pork shoulder, thinly sliced","Marinade: 2 stalks lemongrass minced, 4 garlic cloves, 2 tbsp fish sauce, 1 tbsp sugar, 1 tbsp soy sauce, 1 tsp turmeric","4 French baguette pieces","Pickled vegetables, cucumber, cilantro, jalapeño, sriracha mayo"],prep:"Marinate pork at least 2 hours. Cook in a very hot skillet or grill pan in batches until slightly charred and caramelized — about 2 minutes per side. Build banh mi with sriracha mayo, lemongrass pork, pickled vegetables, cucumber, cilantro, and jalapeño."},
      {id:"ps13", name:"Pork Belly Tacos",servings:"4 servings",ingredients:["1.5 lbs (680 g) pork belly, braised until tender and sliced","8 corn tortillas","Toppings: pickled red onions, shredded cabbage, avocado, salsa verde, cilantro, lime","Chipotle crema: ½ cup sour cream, 2 chipotle peppers, lime juice"],prep:"Slice braised pork belly and pan-fry in a dry skillet over high heat until caramelized and edges are crispy. Warm tortillas. Build tacos with pork belly, shredded cabbage, pickled onions, and avocado. Drizzle with salsa verde and chipotle crema. Garnish with cilantro and lime."},
      {id:"ps14", name:"Ham and Swiss Croissant",servings:"4 servings",ingredients:["4 large croissants","8 slices deli ham","8 slices Swiss cheese","Dijon mustard","Honey","Butter"],prep:"Preheat oven to 350°F (175°C). Split croissants. Mix Dijon mustard with a little honey and spread on the inside of each croissant. Layer 2 slices Swiss cheese and 2 slices ham inside each croissant. Close and place on a baking sheet. Brush tops with melted butter. Bake 12–15 minutes until croissants are golden and cheese is melted. Serve warm."},
      {id:"ps15", name:"Pulled Pork Quesadilla",servings:"4 servings",ingredients:["2 cups pulled pork","8 large flour tortillas","2 cups shredded Monterey Jack and cheddar blend","1 cup BBQ sauce","½ cup jalapeños, sliced","Sour cream and guacamole to serve"],prep:"Mix pulled pork with a little BBQ sauce. In a dry skillet over medium heat lay a tortilla flat. Sprinkle cheese on half. Add pulled pork and jalapeños. Fold over. Cook 2–3 minutes per side until golden and crispy and cheese is melted. Slice into wedges. Serve with sour cream and guacamole."}
    ]
  }

];


// ================================================================
//  TOGGLE CATEGORY — shows/hides recipe list under a card
// ================================================================
function toggleCategory(catId) {
  var ul = document.getElementById(catId);
  if (!ul) return;

  if (ul.style.display === 'block') {
    ul.style.display = 'none';
    return;
  }

  var cat = pork_data.find(function(c) { return c.id === catId; });
  if (!cat) return;

  if (ul.innerHTML === '') {
    cat.recipes.forEach(function(recipe, idx) {
      var li = document.createElement('li');
      li.className = 'browser-item';
      li.innerHTML =
        '<span class="browser-item-name">' + recipe.name + '</span>' +
        '<span class="browser-item-arrow">›</span>';
      li.addEventListener('click', function() {
        open_recipe_modal(recipe, catId);
      });
      ul.appendChild(li);
    });
  }

  ul.style.display = 'block';
}
