const seafoodData = [

  // ===========================
  // 🐟 FISH
  // ===========================
  {
    id: 'fish',
    icon:"🐟", name:"Fish",
    desc:"Salmon, cod, tilapia, halibut, sea bass, mahi mahi, and classic pan-seared and baked fish recipes.",
    recipes:[
      {id:"fi1", name:"Pan-Seared Salmon",servings:"4 servings",ingredients:["4 salmon fillets, 6 oz each, skin-on","2 tbsp olive oil","2 tbsp unsalted butter","3 garlic cloves, smashed","Fresh thyme sprigs","Kosher salt and black pepper","Lemon wedges to serve"],prep:"Pat salmon fillets completely dry with paper towels — this is essential for a good sear. Season generously with salt and pepper on both sides. Heat olive oil in a large skillet over medium-high heat until shimmering. Place salmon skin side up and do not move. Cook 4 minutes until a golden crust forms. Flip. Add butter, garlic, and thyme to pan. Baste salmon continuously with the foaming butter 3–4 minutes until fish is just cooked through — it should flake easily but still be slightly translucent in the very center. Rest 2 minutes. Serve with lemon wedges."},
      {id:"fi2", name:"Baked Lemon Herb Salmon",servings:"4 servings",ingredients:["4 salmon fillets, 6 oz each","3 tbsp olive oil","3 garlic cloves, minced","Juice and zest of 1 lemon","2 tbsp fresh dill, chopped","1 tbsp fresh parsley","1 tsp dried oregano","Salt and black pepper","Lemon slices for topping"],prep:"Preheat oven to 400°F (200°C). Line a baking sheet with foil. Mix olive oil, garlic, lemon juice and zest, dill, parsley, and oregano. Place salmon fillets on prepared baking sheet. Pour herb mixture over salmon. Top each fillet with lemon slices. Season with salt and pepper. Bake 12–15 minutes until salmon flakes easily with a fork. Do not overbake — salmon should still be slightly pink in the center for best texture."},
      {id:"fi3", name:"Miso Glazed Salmon",servings:"4 servings",ingredients:["4 salmon fillets, 6 oz each","Glaze: 3 tbsp white miso paste, 2 tbsp mirin, 2 tbsp sake or dry sherry, 1 tbsp soy sauce, 1 tbsp sugar, 1 tsp sesame oil","Sesame seeds and green onions to garnish","Steamed rice to serve"],prep:"Whisk glaze ingredients until smooth. Marinate salmon in glaze at least 30 minutes or up to overnight in the refrigerator. Preheat broiler to high. Line a baking sheet with foil and lightly oil it. Place salmon skin side down. Broil 6–8 inches from heat for 8–10 minutes until glaze is caramelized and deep golden and salmon is just cooked through. Watch carefully as the sugar in the miso can burn quickly. Garnish with sesame seeds and sliced green onions."},
      {id:"fi4", name:"Baked Cod with Herb Crust",servings:"4 servings",ingredients:["4 cod fillets, 6 oz each","Crust: 1 cup panko breadcrumbs, 3 tbsp Parmesan grated, 2 tbsp fresh parsley, 2 tbsp olive oil, 2 garlic cloves minced, 1 tsp lemon zest, salt and pepper","2 tbsp Dijon mustard","Lemon wedges to serve"],prep:"Preheat oven to 400°F (200°C). Pat cod dry and place on a greased baking sheet. Brush top of each fillet with Dijon mustard. Mix panko, Parmesan, parsley, olive oil, garlic, lemon zest, salt, and pepper until well combined. Press herb crust firmly onto the mustard-coated top of each fillet. Bake 15–18 minutes until crust is golden and fish flakes easily. Serve with lemon wedges."},
      {id:"fi5", name:"Blackened Fish Tacos",servings:"4 servings",ingredients:["1.5 lbs (680 g) white fish — cod, mahi mahi, or tilapia","Blackening Spice: 2 tsp smoked paprika, 1 tsp cumin, 1 tsp garlic powder, 1 tsp onion powder, ½ tsp cayenne, ½ tsp dried thyme, salt","2 tbsp vegetable oil","8 corn tortillas","Slaw: 2 cups cabbage shredded, lime juice, cilantro, mayo, salt","Avocado, lime, and salsa to serve"],prep:"Mix blackening spice. Coat fish fillets generously on all sides. Heat oil in a cast iron skillet over very high heat until smoking. Cook fish 3 minutes per side until deeply charred and cooked through. Rest 2 minutes and break into large flakes. Mix slaw ingredients. Warm tortillas. Fill each with blackened fish and slaw. Top with avocado slices, salsa, and a squeeze of lime."},
      {id:"fi6", name:"Pan-Seared Halibut",servings:"4 servings",ingredients:["4 halibut fillets, 6 oz each","3 tbsp olive oil","2 tbsp unsalted butter","3 garlic cloves, smashed","Fresh thyme","Salt and white pepper","Beurre blanc: 2 shallots minced, ½ cup white wine, ¼ cup white wine vinegar, 1 cup cold butter cubed, salt"],prep:"Pat halibut completely dry. Season with salt and white pepper. Heat olive oil in a skillet over medium-high heat. Sear halibut 4 minutes without moving until golden crust forms. Flip. Add butter, garlic, and thyme and baste 3–4 minutes until cooked through. Make beurre blanc by reducing shallots in wine and vinegar until almost dry. Over low heat whisk in cold butter a piece at a time until glossy sauce forms. Season with salt. Serve halibut with beurre blanc."},
      {id:"fi7", name:"Baked Sea Bass",servings:"4 servings",ingredients:["4 sea bass fillets or 2 whole small sea bass","3 tbsp olive oil","4 garlic cloves, sliced","1 cup cherry tomatoes, halved","½ cup Kalamata olives","½ cup dry white wine","Fresh thyme and rosemary","Salt and pepper","Lemon slices"],prep:"Preheat oven to 400°F (200°C). Place fish in a baking dish. Scatter garlic, cherry tomatoes, and olives around the fish. Pour wine over everything. Drizzle with olive oil. Lay fresh herbs and lemon slices on top. Season generously. Bake 18–22 minutes until fish flakes easily and tomatoes have burst and caramelized. Spoon pan juices over fish to serve."},
      {id:"fi8", name:"Tilapia Piccata",servings:"4 servings",ingredients:["4 tilapia fillets","½ cup all-purpose flour","3 tbsp olive oil","3 tbsp unsalted butter","4 garlic cloves, minced","½ cup dry white wine","½ cup chicken broth","Juice of 2 lemons","3 tbsp capers, rinsed","Fresh flat-leaf parsley","Salt and pepper"],prep:"Season tilapia with salt and pepper. Dredge lightly in flour. Heat olive oil in a large skillet over medium-high heat. Cook fillets 3 minutes per side until golden. Remove. In same pan add 1 tbsp butter and garlic and cook 1 minute. Add wine and reduce by half. Add broth, lemon juice, and capers. Simmer 3 minutes. Swirl in remaining butter. Return fillets to sauce for 1 minute. Garnish with parsley."},
      {id:"fi9", name:"Mahi Mahi with Mango Salsa",servings:"4 servings",ingredients:["4 mahi mahi fillets, 6 oz each","2 tbsp olive oil","1 tsp cumin","1 tsp paprika","Salt and pepper","Mango Salsa: 2 mangos diced, ½ red onion diced, 1 jalapeño diced, ¼ cup cilantro, juice of 2 limes, salt"],prep:"Make mango salsa by combining all salsa ingredients. Refrigerate 30 minutes. Season mahi mahi with cumin, paprika, salt, and pepper. Heat olive oil in a skillet over medium-high heat. Cook fish 4 minutes per side until cooked through and golden. Serve topped generously with fresh mango salsa."},
      {id:"fi10", name:"Teriyaki Salmon",servings:"4 servings",ingredients:["4 salmon fillets, 6 oz each","Teriyaki Sauce: 4 tbsp soy sauce, 2 tbsp mirin, 2 tbsp sake, 2 tbsp brown sugar, 1 tsp cornstarch dissolved in 1 tbsp water","2 tbsp vegetable oil","Sesame seeds and green onions","Steamed rice to serve"],prep:"Mix sauce ingredients except cornstarch in a small saucepan. Simmer until sugar dissolves. Add cornstarch slurry and stir until slightly thickened. Set aside. Heat oil in a skillet over medium-high heat. Cook salmon skin side up 4 minutes. Flip and cook 3 more minutes. Brush with teriyaki sauce and cook 1 more minute per side until lacquered. Serve over steamed rice. Garnish with sesame seeds and green onions."},
      {id:"fi11", name:"Fish and Chips",servings:"4 servings",ingredients:["1.5 lbs (680 g) thick cod or haddock fillets","Batter: 1 cup all-purpose flour, 1 cup cold beer or sparkling water, 1 tsp baking powder, 1 tsp salt","Extra flour for dredging","Vegetable oil for frying","4 large russet potatoes, cut into thick chips","Malt vinegar, tartar sauce, and lemon to serve"],prep:"Fry chips first at 325°F (165°C) for 8 minutes until cooked through but not colored. Drain and set aside. Make batter by whisking flour, beer, baking powder, and salt until smooth — do not overmix. Increase oil to 375°F (190°C). Dredge fish in flour, then dip in batter. Fry 5–6 minutes until deeply golden and crispy. Drain. Re-fry chips at 375°F (190°C) for 3–4 minutes until golden and crispy. Season both immediately with salt. Serve with malt vinegar, tartar sauce, and lemon."},
      {id:"fi12", name:"Poached Salmon with Dill Sauce",servings:"4 servings",ingredients:["4 salmon fillets, 6 oz each","Court Bouillon: 4 cups water, 1 cup white wine, 1 lemon sliced, 1 onion sliced, fresh dill, peppercorns, bay leaf, salt","Dill Sauce: 1 cup sour cream, 2 tbsp fresh dill, 1 tbsp lemon juice, 1 garlic clove minced, salt and pepper"],prep:"Combine court bouillon ingredients in a wide pan and simmer 10 minutes. Gently lower salmon fillets into the barely simmering liquid — water should not be boiling. Poach 8–10 minutes until fish is just cooked through and flakes easily. Remove gently with a slotted spatula. Make dill sauce by mixing all ingredients. Serve salmon warm or chilled with dill sauce."},
      {id:"fi13", name:"Sole Meunière",servings:"2 servings",ingredients:["4 sole fillets or 2 whole small sole","½ cup all-purpose flour","Salt and white pepper","4 tbsp unsalted butter","2 tbsp vegetable oil","Juice of 1 lemon","2 tbsp fresh flat-leaf parsley, chopped","Extra lemon wedges to serve"],prep:"Season sole with salt and white pepper. Dredge lightly in flour shaking off excess. Heat 2 tbsp butter and oil in a large skillet over medium-high heat until foaming subsides. Cook sole 2 minutes per side — it is very delicate and cooks quickly. Remove to warm plates. Wipe pan clean. Add remaining butter and cook over medium heat until it turns golden brown and smells nutty. Remove from heat immediately and add lemon juice — it will sizzle. Pour brown butter over sole and garnish with parsley."},
      {id:"fi14", name:"Grilled Swordfish",servings:"4 servings",ingredients:["4 swordfish steaks, 1 inch thick","Marinade: 3 tbsp olive oil, juice of 1 lemon, 3 garlic cloves, 1 tsp dried oregano, salt and pepper","Salsa Verde: 1 cup parsley, ¼ cup capers, 2 garlic cloves, 2 anchovy fillets, ½ cup olive oil, 2 tbsp lemon juice, salt"],prep:"Marinate swordfish 30 minutes — no longer as acid will start to break down the flesh. Make salsa verde by blending all ingredients. Grill swordfish over high heat 4 minutes per side until cooked through and grill marks appear. Swordfish is done when it flakes but still has a slight translucency in the center. Serve with salsa verde."},
      {id:"fi15", name:"Trout Almondine",servings:"4 servings",ingredients:["4 trout fillets or 2 whole trout, butterflied","½ cup all-purpose flour","Salt and pepper","4 tbsp unsalted butter","½ cup sliced almonds","Juice of 1 lemon","2 tbsp fresh parsley","2 tbsp vegetable oil"],prep:"Season trout with salt and pepper. Dredge in flour. Heat oil and 2 tbsp butter in a large skillet over medium-high heat. Cook trout 3–4 minutes per side until golden. Remove and keep warm. In same pan melt remaining butter over medium heat. Add sliced almonds and cook stirring until golden and fragrant — about 3 minutes. Add lemon juice and parsley. Pour almond butter sauce over trout and serve immediately."}
    ]
  },

  // ===========================
  // 🦐 SHRIMP & PRAWNS
  // ===========================
  {
    id: 'shrimp',
    icon:"🦐", name:"Shrimp & Prawns",
    desc:"Shrimp scampi, garlic butter shrimp, coconut shrimp, shrimp tacos, jambalaya, and classic shrimp recipes.",
    recipes:[
      {id:"sp1", name:"Shrimp Scampi",servings:"4 servings",ingredients:["1.5 lbs (680 g) large shrimp, peeled and deveined","400 g (14 oz) linguine","6 garlic cloves, minced","½ cup (120 ml) dry white wine","4 tbsp unsalted butter","3 tbsp olive oil","Juice and zest of 1 lemon","¼ cup fresh flat-leaf parsley, chopped","Red pepper flakes","Salt and pepper"],prep:"Cook linguine until al dente. Reserve 1 cup pasta water. Heat olive oil and 2 tbsp butter in a large skillet over medium-high heat. Season shrimp with salt, pepper, and red pepper flakes. Add shrimp and cook 1–2 minutes per side until pink and just cooked. Remove shrimp. Add garlic to same pan and cook 30 seconds. Add white wine and cook until reduced by half. Add remaining butter, lemon juice, and zest. Return shrimp and toss. Add pasta and pasta water as needed. Toss with parsley."},
      {id:"sp2", name:"Garlic Butter Shrimp",servings:"4 servings",ingredients:["1.5 lbs (680 g) large shrimp, peeled and deveined","5 tbsp unsalted butter","6 garlic cloves, minced","½ tsp red pepper flakes","Juice of 1 lemon","¼ cup fresh parsley, chopped","Salt and pepper"],prep:"Pat shrimp dry with paper towels. Season with salt and pepper. Melt 2 tbsp butter in a large skillet over medium-high heat. Add shrimp in a single layer and cook 1 minute without moving. Flip and cook 1 more minute. Remove shrimp. Add remaining butter and garlic to pan and cook 1 minute until golden. Add red pepper flakes and lemon juice. Return shrimp and toss to coat in garlic butter. Garnish with parsley. Serve immediately with crusty bread or over rice."},
      {id:"sp3", name:"Coconut Shrimp",servings:"4 servings",ingredients:["1.5 lbs (680 g) large shrimp, peeled and deveined, tails on","1 cup all-purpose flour","2 large eggs beaten","1½ cups sweetened shredded coconut","½ cup panko breadcrumbs","Salt and pepper","Vegetable oil for frying","Dipping Sauce: ½ cup orange marmalade, 2 tbsp Dijon mustard, 1 tbsp horseradish"],prep:"Set up breading station: seasoned flour, beaten eggs, and coconut mixed with panko. Hold each shrimp by the tail. Coat in flour, then egg, then coconut-panko mixture pressing firmly to adhere. Heat 2 inches of oil to 350°F (175°C). Fry shrimp in batches 2–3 minutes until golden and coconut is toasted. Drain on a wire rack. Mix dipping sauce ingredients. Serve immediately."},
      {id:"sp4", name:"Shrimp Tacos",servings:"4 servings",ingredients:["1.5 lbs (680 g) large shrimp, peeled and deveined","Seasoning: 1 tsp cumin, 1 tsp chili powder, 1 tsp paprika, ½ tsp garlic powder, salt","2 tbsp olive oil","8 corn tortillas","Chipotle Crema: ½ cup sour cream, 2 chipotle peppers in adobo, 1 tbsp lime juice","Cabbage slaw, avocado, pico de gallo, lime"],prep:"Toss shrimp with seasoning and olive oil. Cook in a hot skillet 1–2 minutes per side until pink and cooked. Blend chipotle crema ingredients until smooth. Warm tortillas. Fill with shrimp, cabbage slaw, and avocado. Drizzle with chipotle crema and pico de gallo. Serve with lime wedges."},
      {id:"sp5", name:"Shrimp and Grits",servings:"4 servings",ingredients:["1.5 lbs (680 g) large shrimp, peeled and deveined","6 strips bacon, diced","1 onion, diced","3 garlic cloves, minced","1 red bell pepper, diced","1 cup (240 ml) chicken broth","2 tbsp lemon juice","Grits: 1 cup stone-ground grits, 4 cups water, 3 tbsp butter, ½ cup cheddar, salt","Fresh parsley and green onions"],prep:"Cook grits in salted water according to package stirring frequently. Stir in butter and cheddar. Season with salt. Cook bacon until crispy. Remove. Cook onion, pepper, and garlic in bacon fat until soft. Add shrimp and cook 2 minutes per side. Add broth and lemon juice and simmer 2 minutes. Return bacon. Serve shrimp mixture over creamy grits. Top with parsley and green onions."},
      {id:"sp6", name:"Jambalaya",servings:"6 servings",ingredients:["1 lb (450 g) large shrimp, peeled","1 lb (450 g) andouille sausage, sliced","1 lb (450 g) boneless chicken thighs, cubed","1 onion, diced","3 celery stalks, diced","1 green bell pepper, diced","4 garlic cloves, minced","1 can (28 oz) crushed tomatoes","2 cups long grain white rice","3 cups chicken broth","1 tbsp Cajun seasoning","1 tsp thyme","Salt and pepper","Green onions and parsley"],prep:"Brown sausage in a large Dutch oven. Remove. Brown chicken. Remove. Cook onion, celery, and pepper until soft. Add garlic 1 minute. Add Cajun seasoning and thyme. Return sausage and chicken. Add crushed tomatoes, broth, and rice. Bring to boil. Cover and cook on low heat 20 minutes. Add shrimp on top. Cover and cook 5 more minutes until shrimp are pink and rice is cooked. Fluff and garnish with green onions and parsley."},
      {id:"sp7", name:"Shrimp Stir Fry",servings:"4 servings",ingredients:["1.5 lbs (680 g) large shrimp, peeled","2 cups broccoli florets","1 red bell pepper, sliced","1 cup snap peas","3 garlic cloves, minced","1 tbsp fresh ginger","Sauce: 3 tbsp soy sauce, 2 tbsp oyster sauce, 1 tbsp sesame oil, 1 tsp sugar, 1 tsp cornstarch, ½ cup chicken broth","2 tbsp vegetable oil","Steamed rice to serve"],prep:"Mix sauce ingredients. Heat oil in a wok over very high heat. Cook shrimp 1 minute per side until pink. Remove. Add garlic and ginger and cook 30 seconds. Add broccoli and pepper and stir fry 3 minutes. Add snap peas and cook 1 minute. Return shrimp. Pour sauce over and toss until sauce thickens and coats everything — about 1 minute. Serve over steamed rice."},
      {id:"sp8", name:"Shrimp Fried Rice",servings:"4 servings",ingredients:["3 cups day-old cooked rice","1 lb (450 g) large shrimp, peeled","3 large eggs","1 cup frozen peas and carrots","3 garlic cloves, minced","3 green onions, sliced","3 tbsp soy sauce","1 tbsp oyster sauce","1 tsp sesame oil","2 tbsp vegetable oil"],prep:"Heat oil in a wok over very high heat. Cook shrimp 1 minute per side until pink. Remove. Add eggs and scramble. Add garlic and cook 30 seconds. Add cold rice and break up clumps. Stir fry 3 minutes until heated through. Return shrimp. Add peas and carrots, soy sauce, oyster sauce, and sesame oil. Toss together over high heat. Garnish with green onions."},
      {id:"sp9", name:"Cajun Shrimp Pasta",servings:"4 servings",ingredients:["1.5 lbs (680 g) large shrimp, peeled","400 g (14 oz) penne or fettuccine","Cajun Seasoning: 1 tsp paprika, 1 tsp garlic powder, ½ tsp cayenne, ½ tsp thyme, salt and pepper","3 tbsp butter","4 garlic cloves, minced","1 cup (240 ml) heavy cream","½ cup Parmesan","1 cup cherry tomatoes, halved","Fresh parsley"],prep:"Cook pasta until al dente. Toss shrimp with Cajun seasoning. Cook in 1 tbsp butter over high heat 1–2 minutes per side. Remove. In same pan melt remaining butter and cook garlic 1 minute. Add cherry tomatoes and cook 2 minutes. Add cream and simmer 3 minutes. Stir in Parmesan. Return shrimp. Toss with drained pasta. Garnish with parsley."},
      {id:"sp10", name:"Bang Bang Shrimp",servings:"4 servings",ingredients:["1.5 lbs (680 g) medium shrimp, peeled","½ cup cornstarch","Salt and pepper","Vegetable oil for frying","Bang Bang Sauce: ½ cup mayonnaise, 3 tbsp sweet chili sauce, 1 tbsp sriracha, 1 tbsp honey","Lettuce leaves, green onions, and sesame seeds to serve"],prep:"Mix bang bang sauce and refrigerate. Season shrimp with salt and pepper. Toss with cornstarch until well coated. Fry in batches at 375°F (190°C) for 2–3 minutes until golden and crispy. Drain. Toss immediately with bang bang sauce. Serve on a bed of lettuce leaves garnished with green onions and sesame seeds."},
      {id:"sp11", name:"Shrimp Bisque",servings:"4 servings",ingredients:["1.5 lbs (680 g) shrimp, peeled — reserve shells","1 onion, diced","3 garlic cloves, minced","2 celery stalks, diced","2 carrots, diced","3 tbsp butter","2 tbsp tomato paste","½ cup (120 ml) dry sherry or white wine","4 cups (960 ml) seafood or chicken broth","1 cup (240 ml) heavy cream","1 tsp smoked paprika","Cayenne, salt, and white pepper","Fresh chives to garnish"],prep:"Simmer shrimp shells in broth 20 minutes. Strain and reserve shrimp broth. Melt butter in a large pot. Cook onion, celery, and carrot until soft. Add garlic 1 minute. Add tomato paste and paprika and cook 2 minutes. Add sherry and reduce. Add shrimp broth and simmer 15 minutes. Blend until very smooth. Return to pot. Add cream and simmer 5 minutes. Season with cayenne, salt, and white pepper. Cook shrimp separately in butter and use as a garnish. Serve bisque topped with shrimp and chives."},
      {id:"sp12", name:"Shrimp Po Boy",servings:"4 servings",ingredients:["1.5 lbs (680 g) large shrimp, peeled","Coating: 1 cup flour, 1 cup cornmeal, 1 tbsp Cajun seasoning, salt","1 cup buttermilk","Vegetable oil for frying","4 hoagie rolls","Remoulade: ½ cup mayo, 2 tbsp Dijon, 1 tbsp horseradish, 1 tbsp hot sauce, 1 tbsp capers, 1 tsp smoked paprika","Shredded lettuce, tomato, and pickles"],prep:"Soak shrimp in buttermilk 15 minutes. Mix flour, cornmeal, and Cajun seasoning. Dredge shrimp in coating. Fry at 350°F (175°C) for 2–3 minutes until golden. Drain. Mix remoulade. Toast hoagie rolls. Spread remoulade on both sides. Fill with fried shrimp, lettuce, tomato, and pickles. Serve immediately."},
      {id:"sp13", name:"Honey Garlic Shrimp",servings:"4 servings",ingredients:["1.5 lbs (680 g) large shrimp, peeled","Sauce: 3 tbsp honey, 3 tbsp soy sauce, 4 garlic cloves minced, 1 tbsp fresh ginger, 1 tbsp lime juice, 1 tsp sriracha","2 tbsp butter","Sesame seeds and green onions","Steamed rice to serve"],prep:"Mix sauce ingredients. Melt butter in a large skillet over medium-high heat. Add shrimp in a single layer and cook 1 minute per side until pink. Remove shrimp. Add sauce to the pan and simmer 2 minutes until slightly thickened. Return shrimp and toss to coat. Garnish with sesame seeds and green onions. Serve over steamed rice."},
      {id:"sp14", name:"Shrimp Ceviche",servings:"4 servings",ingredients:["1 lb (450 g) medium shrimp, peeled and deveined","Juice of 6 limes (about ¾ cup)","Juice of 2 lemons","1 cup cucumber, finely diced","1 cup cherry tomatoes, quartered","½ red onion, very finely diced","1 jalapeño, minced","¼ cup fresh cilantro, chopped","1 avocado, diced","Salt","Tortilla chips to serve"],prep:"If using raw shrimp cook briefly in boiling salted water 1–2 minutes until just pink. Cool and chop into ½-inch pieces. If using cooked shrimp chop directly. Combine shrimp with lime and lemon juice. Add cucumber, tomatoes, red onion, and jalapeño. Toss well. Refrigerate 30 minutes to 1 hour — the acid will continue to cure the shrimp. Just before serving stir in cilantro and avocado. Season with salt. Serve with tortilla chips."},
      {id:"sp15", name:"Shrimp Étouffée",servings:"4 servings",ingredients:["1.5 lbs (680 g) large shrimp, peeled","1 stick (115 g) unsalted butter","1 onion, diced","3 celery stalks, diced","1 green bell pepper, diced","4 garlic cloves, minced","2 cups (480 ml) shrimp or chicken broth","2 tbsp all-purpose flour","1 tbsp Cajun seasoning","Salt, cayenne, and black pepper","Green onions and parsley","Steamed white rice to serve"],prep:"Melt butter in a large heavy skillet over medium heat. Add onion, celery, and bell pepper and cook until very soft — about 10 minutes. Add garlic and cook 2 minutes. Sprinkle flour over vegetables and stir 2 minutes. Add broth gradually while stirring. Add Cajun seasoning, salt, cayenne, and pepper. Simmer 10 minutes until sauce thickens. Add shrimp and cook 4–5 minutes until just cooked through. Garnish with green onions and parsley. Serve over white rice."}
    ]
  },

  // ===========================
  // 🦞 LOBSTER & CRAB
  // ===========================
  {
    id: 'lobster-crab',
    icon:"🦞", name:"Lobster & Crab",
    desc:"Lobster bisque, lobster rolls, crab cakes, steamed crab, crab pasta, and classic shellfish recipes.",
    recipes:[
      {id:"lc1", name:"Classic Lobster Roll",servings:"4 servings",ingredients:["4 lobster tails, cooked, meat removed and chopped — about 1.5 lbs total","½ cup mayonnaise","2 celery stalks, very finely diced","1 tbsp fresh lemon juice","1 tbsp fresh chives, snipped","Salt and white pepper","4 split-top hot dog buns","3 tbsp unsalted butter, softened","Lettuce leaves (optional)"],prep:"Mix lobster meat with mayonnaise, celery, lemon juice, and chives. Season with salt and white pepper. Taste — the filling should be lightly dressed not heavy. Butter the outsides of the split-top buns. Toast in a skillet over medium heat until golden on both sides. Line buns with lettuce if desired. Fill generously with lobster mixture. Serve immediately. For a Connecticut-style hot lobster roll omit the mayo and toss warm lobster meat in melted butter instead."},
      {id:"lc2", name:"Lobster Bisque",servings:"4 servings",ingredients:["2 lobster tails, cooked — reserve shells","1 onion, diced","2 celery stalks, diced","2 carrots, diced","4 garlic cloves, minced","3 tbsp butter","2 tbsp tomato paste","½ cup (120 ml) dry sherry or cognac","4 cups (960 ml) seafood or chicken broth","1 cup (240 ml) heavy cream","1 tsp smoked paprika","Cayenne, salt, and white pepper","Fresh tarragon and chives to garnish"],prep:"Simmer lobster shells in broth 25 minutes. Strain and reserve lobster broth. Melt butter in a large pot over medium heat. Cook onion, celery, carrot until soft. Add garlic 1 minute. Add tomato paste and paprika and cook 2 minutes. Add sherry and reduce. Add lobster broth and simmer 15 minutes. Blend until very smooth. Return to pot. Add cream and simmer 5 minutes. Season with cayenne, salt, and white pepper. Dice reserved lobster meat. Ladle bisque into bowls. Top with lobster meat and fresh tarragon."},
      {id:"lc3", name:"Crab Cakes",servings:"4 servings",ingredients:["1 lb (450 g) fresh lump crab meat, picked over for shells","½ cup mayonnaise","1 large egg","1 tbsp Dijon mustard","1 tbsp Worcestershire sauce","1 tbsp Old Bay seasoning","1 tsp hot sauce","½ cup panko breadcrumbs","2 tbsp fresh parsley","Salt and pepper","3 tbsp olive oil for searing","Remoulade or tartar sauce to serve"],prep:"Gently mix crab meat with mayonnaise, egg, Dijon, Worcestershire, Old Bay, hot sauce, parsley, salt, and pepper. Fold in just enough panko to bind — do not overwork or crab cakes will be dense. Form into 8 patties. Refrigerate 30 minutes so they hold together. Heat olive oil in a skillet over medium-high heat. Sear crab cakes 3–4 minutes per side until deeply golden and heated through. Serve with remoulade or tartar sauce."},
      {id:"lc4", name:"Steamed Dungeness Crab",servings:"2 servings",ingredients:["2 whole Dungeness crabs, live or precooked","1 cup (240 ml) white wine or beer","2 cups water","2 garlic cloves","1 lemon, sliced","Bay leaves and Old Bay seasoning","Melted butter and lemon for serving"],prep:"If using live crabs humanely dispatch by placing in freezer 30 minutes. Set up a large pot with a steamer insert. Add wine, water, garlic, lemon, bay leaves, and a generous amount of Old Bay. Bring to a boil. Place crabs in steamer. Cover and steam 15–18 minutes for whole crabs until shell is bright red. Rest 5 minutes. Crack legs and claws with a mallet. Serve with melted butter and lemon wedges."},
      {id:"lc5", name:"Crab Linguine",servings:"4 servings",ingredients:["400 g (14 oz) linguine","1 lb (450 g) fresh crab meat","4 garlic cloves, minced","3 shallots, minced","½ cup (120 ml) dry white wine","4 tbsp unsalted butter","3 tbsp olive oil","Juice and zest of 1 lemon","¼ cup fresh parsley","Red pepper flakes","Salt and pepper"],prep:"Cook linguine until al dente. Reserve 1 cup pasta water. Heat olive oil in a large skillet over medium heat. Cook shallots and garlic 2 minutes. Add wine and reduce by half. Add butter and lemon juice and zest. Add crab meat and toss gently to warm through — do not break it up too much. Add pasta and toss with pasta water as needed. Add red pepper flakes and parsley. Season with salt and pepper."},
      {id:"lc6", name:"Lobster Thermidor",servings:"2 servings",ingredients:["2 whole lobsters, cooked and halved lengthwise","3 tbsp unsalted butter","2 shallots, minced","2 garlic cloves, minced","½ cup (120 ml) dry white wine","½ cup (120 ml) heavy cream","1 tbsp Dijon mustard","¼ cup Parmesan, grated","Fresh tarragon","Salt, white pepper, and cayenne"],prep:"Remove lobster meat from shells carefully and cut into chunks. Reserve shells. Make sauce: cook shallots and garlic in butter 2 minutes. Add wine and reduce by half. Add cream and simmer until thickened. Add mustard, tarragon, salt, white pepper, and cayenne. Mix lobster chunks with half the sauce. Fill shells with lobster mixture. Spoon remaining sauce over top. Sprinkle with Parmesan. Broil until golden and bubbly — 3–5 minutes."},
      {id:"lc7", name:"Crab Stuffed Mushrooms",servings:"6 servings",ingredients:["24 large cremini mushrooms, stems removed","Filling: 8 oz (225 g) cream cheese softened, 1 cup lump crab meat, ¼ cup Parmesan, 2 green onions minced, 2 garlic cloves minced, 1 tbsp lemon juice, 1 tsp Old Bay, salt and pepper","Panko and Parmesan for topping","Olive oil"],prep:"Preheat oven to 375°F (190°C). Mix cream cheese, crab, Parmesan, green onions, garlic, lemon juice, and Old Bay until well combined. Season with salt and pepper. Fill each mushroom cap generously. Mix a little panko with Parmesan and sprinkle on top. Drizzle with olive oil. Bake 20–25 minutes until mushrooms are tender and topping is golden."},
      {id:"lc8", name:"Lobster Mac and Cheese",servings:"6 servings",ingredients:["500 g (1 lb) elbow macaroni","2 lobster tails, cooked and chopped","4 tbsp unsalted butter","¼ cup flour","3 cups (720 ml) whole milk","1 cup (240 ml) heavy cream","2 cups Gruyère, grated","1 cup sharp cheddar, grated","½ cup Parmesan","1 tsp dry mustard","Salt, white pepper, and cayenne","Panko and butter for topping"],prep:"Preheat oven to 375°F (190°C). Cook macaroni until al dente. Make cheese sauce: melt butter, whisk in flour 1 minute, gradually add milk and cream until smooth and thickened. Remove from heat and stir in all three cheeses, mustard, salt, white pepper, and cayenne. Combine with pasta and lobster. Pour into a baking dish. Top with buttered panko. Bake 25–30 minutes until golden and bubbly."},
      {id:"lc9", name:"Crab Dip",servings:"8 servings",ingredients:["1 lb (450 g) lump crab meat","8 oz (225 g) cream cheese, softened","½ cup mayonnaise","½ cup sour cream","1 cup shredded mozzarella","¼ cup Parmesan","1 tbsp lemon juice","1 tbsp Worcestershire sauce","1 tsp Old Bay seasoning","2 green onions, sliced","Salt and cayenne"],prep:"Preheat oven to 350°F (175°C). Beat cream cheese until smooth. Mix in mayonnaise, sour cream, lemon juice, Worcestershire sauce, and Old Bay. Fold in crab, mozzarella, Parmesan, and green onions. Season with salt and cayenne. Transfer to a baking dish. Bake 25 minutes until hot and bubbly. Serve with crusty bread, crackers, or tortilla chips."},
      {id:"lc10", name:"Maryland Crab Soup",servings:"6 servings",ingredients:["1 lb (450 g) blue crab claws or lump crab meat","1 onion, diced","3 celery stalks, diced","3 carrots, diced","2 potatoes, diced","1 cup corn kernels","1 cup green beans, cut","1 can (28 oz) crushed tomatoes","6 cups seafood or chicken broth","2 tbsp Old Bay seasoning","Salt and pepper","Fresh parsley"],prep:"In a large pot combine broth, crushed tomatoes, and Old Bay. Bring to a boil. Add onion, celery, carrots, and potatoes. Simmer 15 minutes. Add corn, green beans, and crab. Simmer 10 more minutes until all vegetables are tender and crab is heated through. Adjust seasoning. Garnish with fresh parsley. This is a classic Maryland blue crab soup."},
      {id:"lc11", name:"Crab Rangoon",servings:"6 servings",ingredients:["24 wonton wrappers","Filling: 8 oz (225 g) cream cheese softened, 6 oz (170 g) crab meat, 2 green onions minced, 1 garlic clove minced, 1 tsp soy sauce, 1 tsp Worcestershire sauce, salt","Vegetable oil for frying","Sweet chili sauce or duck sauce for dipping"],prep:"Mix filling ingredients until smooth. Place a small spoonful in the center of each wonton wrapper. Wet edges with water. Fold into triangles or pull all corners up to the center and pinch to seal into a purse shape. Heat 2 inches of oil to 350°F (175°C). Fry in batches 2–3 minutes until golden and crispy. Drain. Serve with sweet chili sauce or duck sauce."},
      {id:"lc12", name:"Lobster Pasta",servings:"4 servings",ingredients:["2 lobster tails, cooked, meat removed and chopped","400 g (14 oz) tagliatelle or linguine","4 garlic cloves, minced","3 shallots, minced","½ cup (120 ml) dry white wine","1 cup (240 ml) heavy cream","3 tbsp butter","Juice of 1 lemon","Fresh tarragon and chives","Salt, white pepper, and cayenne"],prep:"Cook pasta until al dente. Reserve pasta water. Cook shallots and garlic in butter 2 minutes. Add wine and reduce. Add cream and simmer until thickened. Add lemon juice, cayenne, salt, and white pepper. Add lobster and heat through gently. Toss with pasta adding pasta water as needed. Garnish with fresh tarragon and chives."},
      {id:"lc13", name:"Soft Shell Crab",servings:"4 servings",ingredients:["4 soft shell crabs, cleaned","1 cup all-purpose flour","1 cup buttermilk","1 cup cornmeal seasoned with Old Bay, salt and pepper","Vegetable oil for frying","Remoulade sauce and lemon to serve"],prep:"Dip each crab in buttermilk, then dredge in flour, back in buttermilk, then in seasoned cornmeal. Press firmly to adhere. Heat 1 inch of oil in a skillet over medium-high heat to 350°F (175°C). Fry crabs 3 minutes per side until golden and crispy. They will splatter — be careful. Drain on a wire rack. Serve immediately with remoulade sauce and lemon."},
      {id:"lc14", name:"Crab Salad",servings:"4 servings",ingredients:["1 lb (450 g) lump crab meat","½ cup mayonnaise","2 celery stalks, finely diced","2 tbsp fresh lemon juice","1 tbsp fresh chives","1 tsp Old Bay seasoning","Salt and white pepper","Butter lettuce, avocado, and lemon to serve"],prep:"Gently pick through crab meat removing any shells. Fold together with mayonnaise, celery, lemon juice, chives, and Old Bay. Season with salt and white pepper. Taste carefully — the seasoning should be light. Refrigerate 30 minutes. Serve on butter lettuce leaves with avocado slices and lemon wedges. Also excellent on toasted brioche or in avocado halves."},
      {id:"lc15", name:"Garlic Butter King Crab Legs",servings:"2 servings",ingredients:["2 lbs (900 g) king crab legs, split","Garlic Butter: ½ cup (115 g) unsalted butter, 5 garlic cloves minced, 1 tbsp fresh parsley, juice of ½ lemon, pinch of cayenne","Salt"],prep:"Preheat oven to 375°F (190°C). Split crab legs lengthwise if not already split. Place in a baking dish flesh side up. Make garlic butter by melting butter with garlic, parsley, lemon juice, and cayenne. Spoon generously over exposed crab meat. Bake 12–15 minutes until heated through and butter is bubbly. Serve immediately with remaining garlic butter for dipping and extra lemon wedges."}
    ]
  },

  // ===========================
  // 🦪 CLAMS, MUSSELS & OYSTERS
  // ===========================
  {
    id: 'clams-mussels',
    icon:"🦪", name:"Clams, Mussels & Oysters",
    desc:"Steamed mussels, clam chowder, oysters Rockefeller, linguine alle vongole, and classic shellfish recipes.",
    recipes:[
      {id:"cm1", name:"Moules Marinières",servings:"4 servings",ingredients:["2 kg (4.4 lbs) fresh mussels, scrubbed and debearded","4 shallots, finely minced","4 garlic cloves, minced","1 cup (240 ml) dry white wine","4 tbsp unsalted butter","Fresh flat-leaf parsley, chopped","Salt and pepper","Crusty bread to serve"],prep:"Scrub mussels and pull out any beards. Discard any mussels that are open and do not close when tapped. Melt butter in a large pot over medium heat. Cook shallots and garlic until soft — about 3 minutes. Increase heat to high. Add wine and bring to a boil. Add mussels. Cover tightly and cook 4–5 minutes shaking the pot occasionally until all mussels have opened. Discard any that remain closed. Season broth with salt and pepper. Ladle into deep bowls. Garnish with fresh parsley. Serve with crusty bread for dunking."},
      {id:"cm2", name:"New England Clam Chowder",servings:"6 servings",ingredients:["3 cans (6.5 oz each) chopped clams — reserve liquid","6 strips bacon, diced","1 large onion, diced","3 celery stalks, diced","3 garlic cloves, minced","4 medium potatoes, cubed","2 cups (480 ml) whole milk","1 cup (240 ml) heavy cream","3 tbsp all-purpose flour","2 tbsp unsalted butter","1 tsp dried thyme","Salt and white pepper","Fresh chives and oyster crackers to serve"],prep:"Cook bacon in a large pot until crispy. Remove and set aside. Cook onion, celery, and garlic in bacon fat until soft. Add flour and stir 2 minutes. Gradually add clam liquid and milk while stirring to avoid lumps. Add potatoes and thyme. Simmer 15 minutes until potatoes are tender. Add heavy cream and chopped clams. Heat through — do not boil after adding clams or they will become rubbery. Season with salt and white pepper. Serve topped with bacon, chives, and oyster crackers."},
      {id:"cm3", name:"Manhattan Clam Chowder",servings:"6 servings",ingredients:["3 cans (6.5 oz each) chopped clams, liquid reserved","6 strips bacon, diced","1 onion, diced","3 celery stalks, diced","2 carrots, diced","3 garlic cloves, minced","1 can (28 oz) crushed tomatoes","4 potatoes, diced","3 cups (720 ml) seafood or chicken broth","1 tsp dried thyme","1 bay leaf","Salt, pepper, and red pepper flakes"],prep:"Cook bacon until crispy. Cook onion, celery, carrots, and garlic in bacon fat until soft. Add crushed tomatoes and cook 5 minutes. Add broth, reserved clam liquid, potatoes, thyme, and bay leaf. Simmer 20 minutes until potatoes are tender. Add clams and heat through. Season with salt, pepper, and red pepper flakes. Remove bay leaf. Serve with crusty bread."},
      {id:"cm4", name:"Oysters Rockefeller",servings:"4 servings",ingredients:["24 fresh oysters on the half shell","Topping: 1 cup fresh spinach blanched and squeezed dry, 4 tbsp butter, 4 shallots minced, 2 garlic cloves, ¼ cup Parmesan, ¼ cup breadcrumbs, 2 tbsp Pernod or anise liqueur, salt, cayenne, and pepper","Rock salt for baking pan"],prep:"Preheat oven to 450°F (230°C). Cook shallots and garlic in butter 2 minutes. Add spinach and cook 1 minute. Add Pernod and cook until evaporated. Mix with Parmesan and breadcrumbs. Season with salt and cayenne. Fill a baking pan with rock salt to hold oysters steady. Nestle oysters in their half shells into the salt. Top each oyster with a generous spoonful of spinach mixture. Bake 10–12 minutes until topping is golden and oysters are just cooked."},
      {id:"cm5", name:"Steamed Clams with Garlic and Wine",servings:"4 servings",ingredients:["2 kg (4.4 lbs) littleneck clams, scrubbed","6 garlic cloves, minced","4 shallots, minced","1 cup (240 ml) dry white wine","4 tbsp unsalted butter","¼ cup fresh parsley","Red pepper flakes","Salt","Crusty bread to serve"],prep:"Soak clams in cold salted water 30 minutes to purge sand. Drain and scrub. Discard any that do not close when tapped. Melt butter in a large pot over medium heat. Cook shallots and garlic with red pepper flakes 2 minutes. Add wine and bring to a boil. Add clams. Cover tightly and cook 6–8 minutes until all clams open. Discard any that remain closed. Season broth. Ladle into bowls with plenty of broth. Garnish with parsley. Serve with crusty bread for dipping."},
      {id:"cm6", name:"Mussels in Cream Sauce",servings:"4 servings",ingredients:["2 kg (4.4 lbs) mussels, scrubbed and debearded","4 shallots, minced","4 garlic cloves, minced","1 cup (240 ml) dry white wine","1 cup (240 ml) heavy cream","3 tbsp butter","Fresh thyme","Fresh parsley","Salt and pepper","Crusty bread to serve"],prep:"Discard any open mussels that do not close when tapped. Melt butter in a large pot over medium heat. Cook shallots and garlic 2 minutes. Add wine and thyme and bring to a boil. Add mussels and cover. Cook 4–5 minutes until all mussels open. Remove mussels to a bowl. Add cream to the broth and simmer 3 minutes until slightly thickened. Season with salt and pepper. Return mussels to pot and toss. Garnish with parsley. Serve with crusty bread."},
      {id:"cm7", name:"Fried Oysters",servings:"4 servings",ingredients:["24 fresh oysters, shucked","1 cup all-purpose flour","2 large eggs beaten","1 cup panko breadcrumbs seasoned with Old Bay, salt and pepper","Vegetable oil for frying","Tartar sauce and lemon to serve"],prep:"Pat oysters dry. Set up breading station: flour, beaten eggs, and seasoned panko. Coat each oyster in flour, then egg, then panko pressing firmly to adhere. Heat 2 inches of oil to 375°F (190°C). Fry oysters in batches 2–3 minutes until golden and crispy. Do not overcook. Drain on a wire rack. Serve immediately with tartar sauce and lemon."},
      {id:"cm8", name:"Clams Casino",servings:"4 servings",ingredients:["24 littleneck clams, scrubbed and opened on the half shell","Topping: 6 strips bacon diced and cooked, 1 red bell pepper finely diced, 3 shallots minced, 3 garlic cloves minced, 3 tbsp butter, ¼ cup breadcrumbs, 2 tbsp Parmesan, fresh parsley, salt and pepper"],prep:"Preheat oven to 450°F (230°C). Cook shallots, garlic, and red pepper in butter until soft. Mix with crispy bacon, breadcrumbs, and Parmesan. Season with salt and pepper. Nestle clams in their half shells in a baking pan filled with rock salt. Top each clam with a generous spoonful of topping. Bake 10–12 minutes until topping is golden and clams are just cooked. Garnish with parsley."},
      {id:"cm9", name:"Thai Steamed Mussels",servings:"4 servings",ingredients:["2 kg (4.4 lbs) mussels, scrubbed and debearded","2 stalks lemongrass, smashed and cut","4 kaffir lime leaves","3 red chilies, sliced","4 garlic cloves, minced","1-inch ginger, sliced","1 cup (240 ml) coconut milk","½ cup (120 ml) white wine or chicken broth","2 tbsp fish sauce","1 tbsp lime juice","Fresh cilantro and Thai basil"],prep:"Discard any open mussels. In a large pot combine lemongrass, kaffir lime leaves, chilies, garlic, and ginger with coconut milk and wine. Bring to a boil. Add mussels. Cover and cook 4–5 minutes until all mussels open. Discard any that remain closed. Add fish sauce and lime juice. Adjust seasoning. Garnish with fresh cilantro and Thai basil."},
      {id:"cm10", name:"Oyster Stew",servings:"4 servings",ingredients:["1 pint fresh shucked oysters with their liquor","4 tbsp unsalted butter","1 onion, finely diced","3 celery stalks, finely diced","3 cups (720 ml) whole milk","1 cup (240 ml) heavy cream","Salt, white pepper, and cayenne","Fresh parsley and oyster crackers to serve"],prep:"Melt butter in a pot over medium heat. Cook onion and celery until very soft — about 10 minutes. Add milk and cream and bring to a very gentle simmer — do not boil. Add oysters with their liquor. Cook gently 5–8 minutes until oysters just begin to curl at the edges and are just cooked through. Season with salt, white pepper, and cayenne. Serve immediately topped with parsley and oyster crackers."},
      {id:"cm11", name:"Baked Oysters with Parmesan",servings:"4 servings",ingredients:["24 fresh oysters on the half shell","Topping: 4 tbsp butter softened, 4 garlic cloves minced, ½ cup Parmesan grated, ¼ cup breadcrumbs, 2 tbsp fresh parsley, juice of ½ lemon, cayenne, salt"],prep:"Preheat broiler to high. Mix all topping ingredients together until combined. Fill a baking pan with rock salt. Nestle oysters in their shells into the salt so they sit level. Top each oyster with a generous amount of Parmesan topping. Broil 4–5 minutes until topping is golden and bubbly and oysters are just cooked. Serve immediately with lemon wedges."},
      {id:"cm12", name:"Clam Linguine (Linguine alle Vongole)",servings:"4 servings",ingredients:["400 g (14 oz) linguine","1 kg (2.2 lbs) fresh clams, scrubbed","6 garlic cloves, thinly sliced","1 cup (240 ml) dry white wine","4 tbsp olive oil","¼ tsp red pepper flakes","¼ cup fresh flat-leaf parsley, chopped","Salt and black pepper"],prep:"Soak clams in salted water 30 minutes to purge grit. Cook linguine until al dente. Reserve 1 cup pasta water. Heat olive oil in a large deep skillet over medium heat. Add garlic and red pepper flakes and cook until golden. Add wine and bring to a boil. Add clams, cover, and cook until all open — about 5–7 minutes. Discard any that do not open. Drain pasta and add to clam pan. Toss vigorously over high heat adding pasta water as needed. Stir in parsley."},
      {id:"cm13", name:"Mussels with Chorizo",servings:"4 servings",ingredients:["2 kg (4.4 lbs) mussels, scrubbed","200 g (7 oz) Spanish chorizo, sliced","4 garlic cloves, minced","3 shallots, minced","1 cup (240 ml) dry white wine","1 can (14 oz) crushed tomatoes","3 tbsp olive oil","Fresh parsley","Crusty bread to serve"],prep:"Cook chorizo in olive oil in a large pot over medium-high heat until browned and oil is orange. Remove chorizo. Cook shallots and garlic in same pot 2 minutes. Add wine and reduce. Add crushed tomatoes and simmer 10 minutes. Return chorizo. Add mussels and cover. Cook 4–5 minutes until all mussels open. Discard any that do not open. Garnish with parsley. Serve with crusty bread."},
      {id:"cm14", name:"Raw Oysters with Mignonette",servings:"4 servings",ingredients:["24 fresh oysters, freshly shucked on the half shell","Mignonette: 2 shallots very finely minced, ½ cup red wine vinegar, 1 tbsp sugar, ½ tsp cracked black pepper","Crushed ice for serving","Lemon wedges and Tabasco to serve"],prep:"Make mignonette by combining shallots, red wine vinegar, sugar, and cracked black pepper. Refrigerate at least 30 minutes — the shallots will mellow and the flavors meld. Shuck oysters and loosen meat from shells leaving in the shell. Arrange on crushed ice. Serve with mignonette sauce, lemon wedges, and Tabasco. Eat immediately while very cold."},
      {id:"cm15", name:"Clam Bake",servings:"6 servings",ingredients:["2 lbs (900 g) littleneck clams","1 lb (450 g) mussels","1 lb (450 g) large shrimp","2 lobster tails, halved","4 ears corn, halved","1 lb (450 g) small red potatoes","1 lb (450 g) andouille sausage, sliced","1 onion, quartered","4 cups water or seafood broth","Old Bay seasoning","Melted butter and lemon to serve"],prep:"In a very large pot layer potatoes on the bottom. Add onion, sausage, and corn. Add enough water or broth to cover the bottom 2 inches. Season very generously with Old Bay. Bring to a boil and cook covered 15 minutes. Add clams and mussels. Cook 5 minutes. Add shrimp and lobster. Cover and cook 5–8 more minutes until all shellfish are open and shrimp and lobster are cooked. Serve everything from the pot with melted butter and lemon."}
    ]
  },

  // ===========================
  // 🍣 SUSHI & RAW SEAFOOD
  // ===========================
  {
    id: 'sushi-raw',
    icon:"🍣", name:"Sushi & Raw Seafood",
    desc:"Homemade sushi rolls, sashimi, poke bowls, ceviche, tartare, and fresh raw seafood recipes.",
    recipes:[
      {id:"sr1", name:"Sushi Rice",servings:"4 servings",ingredients:["2 cups (400 g) Japanese short grain sushi rice","2½ cups (600 ml) water","Sushi Vinegar: 4 tbsp rice vinegar, 2 tbsp sugar, 1 tsp salt"],prep:"Rinse rice in cold water until water runs clear — about 5–7 rinses. This removes excess starch. Soak rinsed rice in cold water 30 minutes. Drain. Cook rice with 2½ cups water in a heavy pot. Bring to a boil. Reduce to the lowest heat. Cover tightly and cook 15 minutes. Remove from heat and steam covered 10 more minutes without lifting the lid. Mix vinegar, sugar, and salt until dissolved. Spread hot rice in a large shallow bowl. Pour vinegar mixture over and fold gently using a wooden paddle while fanning to cool — this gives sushi rice its shine and prevents it from getting sticky."},
      {id:"sr2", name:"California Roll",servings:"4 servings",ingredients:["2 cups prepared sushi rice","4 nori sheets","1 cup imitation crab or real crab meat","2 avocados, sliced","1 cucumber, julienned","Sesame seeds","Soy sauce, wasabi, and pickled ginger to serve"],prep:"Place a nori sheet on a bamboo mat shiny side down. With wet hands spread a thin even layer of sushi rice over the nori leaving a ½-inch border at the top. Sprinkle with sesame seeds. Flip the nori so the rice side is down on the mat. Place crab, avocado, and cucumber in a line along the edge closest to you. Roll tightly using the mat to guide, pressing firmly as you roll. Seal the edge with a little water. Slice with a wet sharp knife into 8 pieces. Serve with soy sauce, wasabi, and pickled ginger."},
      {id:"sr3", name:"Spicy Tuna Roll",servings:"4 servings",ingredients:["2 cups prepared sushi rice","4 nori sheets","1 lb (450 g) sushi-grade tuna, finely chopped","Spicy Mayo: 3 tbsp mayonnaise, 1 tbsp sriracha, 1 tsp sesame oil","Cucumber, julienned","Sesame seeds","Soy sauce and pickled ginger to serve"],prep:"Mix chopped tuna with spicy mayo. Make inside-out rolls: place nori on bamboo mat. Spread rice over nori. Flip so rice is face down. Place spicy tuna mixture and cucumber along the edge. Roll tightly. Sprinkle with sesame seeds. Slice with a wet sharp knife. Serve with soy sauce and pickled ginger."},
      {id:"sr4", name:"Salmon Sashimi",servings:"4 servings",ingredients:["1 lb (450 g) sushi-grade salmon, very fresh","Soy sauce","Wasabi","Pickled ginger","Daikon radish, shredded","Shiso leaves (optional)","Lemon wedges"],prep:"Purchase only sushi-grade salmon from a reputable fishmonger. Place salmon in the freezer 30 minutes — slightly firm fish is easier to slice. Using a very sharp long knife slice salmon against the grain at a slight diagonal into ¼-inch thick slices. Each slice should be smooth and clean — do not saw. Arrange on a plate with shredded daikon and shiso leaves. Serve immediately with soy sauce, wasabi, and pickled ginger."},
      {id:"sr5", name:"Tuna Poke Bowl",servings:"4 servings",ingredients:["1 lb (450 g) sushi-grade tuna, cubed","Poke Marinade: 3 tbsp soy sauce, 1 tbsp sesame oil, 1 tbsp rice vinegar, 1 tsp sriracha, 1 tsp ginger grated","2 cups cooked sushi rice or brown rice","1 avocado, sliced","1 cup cucumber, diced","½ cup edamame","1 cup mango, diced","Sesame seeds and green onions","Furikake seasoning (optional)"],prep:"Mix poke marinade. Toss tuna cubes with marinade and refrigerate 15–30 minutes. Build bowls with rice base. Arrange marinated tuna, avocado, cucumber, edamame, and mango in sections on top. Drizzle with extra sesame oil and soy sauce. Garnish with sesame seeds, green onions, and furikake if using."},
      {id:"sr6", name:"Dragon Roll",servings:"4 servings",ingredients:["2 cups prepared sushi rice","4 nori sheets","1 lb (450 g) shrimp tempura","Cucumber, julienned","2 avocados, thinly sliced","Tobiko (flying fish roe)","Unagi sauce: ½ cup soy sauce, ¼ cup mirin, 2 tbsp sugar, reduced by half","Spicy mayo"],prep:"Make shrimp tempura by coating shrimp in tempura batter and frying. Make inside-out rolls with rice on the outside. Fill with shrimp tempura and cucumber. Roll tightly. Fan thin avocado slices over the top of the roll. Wrap in plastic and press gently with the bamboo mat to shape. Remove plastic and slice. Top with tobiko. Drizzle with unagi sauce and spicy mayo."},
      {id:"sr7", name:"Salmon Poke Bowl",servings:"4 servings",ingredients:["1 lb (450 g) sushi-grade salmon, cubed","Marinade: 3 tbsp soy sauce, 1 tbsp sesame oil, 1 tbsp mirin, 1 tsp ginger, 1 tsp sriracha","2 cups rice","Toppings: avocado, cucumber, edamame, shredded carrots, radish, pickled ginger","Sesame seeds, furikake, and green onions","Sriracha mayo drizzle"],prep:"Toss salmon cubes with marinade and refrigerate 15 minutes. Cook rice. Make sriracha mayo by mixing equal parts mayo and sriracha. Build bowls with rice base. Add marinated salmon. Arrange toppings in sections. Drizzle with sriracha mayo. Garnish with sesame seeds, furikake, and green onions."},
      {id:"sr8", name:"Fish Tartare",servings:"4 servings",ingredients:["1 lb (450 g) sushi-grade tuna or salmon, very finely diced","2 shallots, very finely minced","2 tbsp capers, finely chopped","1 tbsp Dijon mustard","1 tbsp fresh lemon juice","1 tbsp olive oil","1 tbsp fresh chives, snipped","Salt, white pepper, and cayenne","Toast points or blinis to serve"],prep:"All ingredients must be very cold. Dice fish into very small even pieces. Mix with shallots, capers, Dijon, lemon juice, olive oil, and chives. Season carefully with salt, white pepper, and a pinch of cayenne. Taste — the flavor should be clean and bright. Serve immediately on toast points or blinis. Do not prepare more than 30 minutes ahead."},
      {id:"sr9", name:"Yellowtail Jalapeño",servings:"4 servings",ingredients:["1 lb (450 g) sushi-grade yellowtail, thinly sliced","1 jalapeño, very thinly sliced","Ponzu Sauce: 3 tbsp soy sauce, 2 tbsp lime juice, 1 tbsp mirin, 1 tsp sesame oil","Yuzu or lemon juice","Micro cilantro or thin cilantro leaves","Crispy garlic chips or fried shallots"],prep:"Mix ponzu sauce. Arrange thin slices of yellowtail on a chilled plate. Place one thin jalapeño slice on each piece of fish. Spoon ponzu sauce over each piece. Garnish with cilantro and crispy garlic chips. Serve immediately."},
      {id:"sr10", name:"Oyster Shooters",servings:"4 servings",ingredients:["8 fresh oysters, shucked","Shooter Mix: 8 tbsp vodka, 8 tsp horseradish, 8 tsp ketchup or cocktail sauce, 8 tsp hot sauce, 8 tsp lemon juice","Celery salt","Cracked black pepper"],prep:"Shuck oysters and collect their liquor. Mix all shooter liquid ingredients and season with celery salt and black pepper. Pour a small amount of shooter mix into shot glasses. Slide one raw oyster with its liquor into each glass. Serve immediately. The diner should drink the entire contents in one shot."},
      {id:"sr11", name:"Salmon Tartare",servings:"4 servings",ingredients:["1 lb (450 g) sushi-grade salmon, very finely diced","1 tbsp capers, chopped","1 shallot, finely minced","1 tbsp fresh dill","1 tbsp crème fraîche","1 tsp lemon juice","1 tsp olive oil","Salt and white pepper","Cucumber slices or crackers to serve"],prep:"Keep all ingredients very cold. Dice salmon very finely. Combine with capers, shallot, dill, crème fraîche, lemon juice, and olive oil. Season with salt and white pepper. Serve immediately using a ring mold for presentation or on cucumber slices and crackers. Do not prepare more than 30 minutes in advance."},
      {id:"sr12", name:"Tuna Tataki",servings:"4 servings",ingredients:["1 lb (450 g) sushi-grade tuna loin","1 tsp sesame oil","Salt and black pepper","Ponzu: 3 tbsp soy sauce, 2 tbsp lemon juice, 1 tbsp mirin","Sesame seeds, green onions, micro greens, and grated daikon"],prep:"Brush tuna loin with sesame oil and season with salt and pepper. Heat a cast iron pan over the highest heat possible until smoking. Sear tuna 30 seconds per side — all four sides. The outside should be seared and the inside completely raw. Immediately plunge into ice water 1 minute to stop cooking. Pat dry. Slice very thin. Arrange on a plate with daikon, green onions, and micro greens. Drizzle with ponzu. Garnish with sesame seeds."},
      {id:"sr13", name:"Ahi Tuna Poke Nachos",servings:"4 servings",ingredients:["1 lb (450 g) sushi-grade ahi tuna, diced","Poke Marinade: 3 tbsp soy sauce, 1 tbsp sesame oil, 1 tsp sriracha, 1 tsp ginger","Wonton chips or taro chips","1 avocado, mashed","Spicy mayo","Pickled jalapeños","Green onions and sesame seeds"],prep:"Toss diced tuna with poke marinade and refrigerate 15 minutes. Make spicy mayo by mixing mayo and sriracha. Arrange wonton or taro chips on a platter. Add a dollop of mashed avocado on each chip. Top with marinated tuna. Drizzle with spicy mayo. Garnish with pickled jalapeños, green onions, and sesame seeds. Serve immediately."},
      {id:"sr14", name:"Scallop Crudo",servings:"4 servings",ingredients:["12 fresh sea scallops, very fresh, sliced thin","Dressing: 3 tbsp extra virgin olive oil, 2 tbsp lemon juice, 1 tbsp lemon zest, 1 shallot finely minced, salt and white pepper","Microgreens or arugula","Shaved Parmesan or fennel","Sea salt flakes and cracked black pepper"],prep:"Use only the freshest dry scallops available. Slice each scallop crosswise into 3 thin rounds. Arrange on a chilled plate. Mix dressing and drizzle lightly over scallops. Garnish with microgreens and shaved Parmesan or fennel. Finish with a pinch of sea salt flakes and cracked black pepper. Serve immediately — the acid will start curing the scallops if left too long."},
      {id:"sr15", name:"Homemade Sushi Temaki Hand Rolls",servings:"4 servings",ingredients:["2 cups prepared sushi rice","8 nori sheets, cut in half","Fillings: sushi-grade salmon and tuna diced, cucumber julienned, avocado sliced, cream cheese (optional)","Sesame seeds","Spicy mayo","Soy sauce and wasabi to serve"],prep:"Lay a half-sheet of nori flat in your hand shiny side down. Place a small scoop of rice on the left side of the nori. Add 2–3 fillings diagonally across the rice. Fold the bottom left corner of the nori over the filling, then continue rolling into a cone shape. The hand roll should be eaten immediately — nori becomes soggy quickly. Serve with soy sauce and wasabi. Set up all fillings in small bowls so guests can make their own."}
    ]
  },

  // ===========================
  // 🥘 SEAFOOD STEWS & SOUPS
  // ===========================
  {
    id: 'seafood-stews',
    icon:"🥘", name:"Seafood Stews & Soups",
    desc:"Cioppino, bouillabaisse, seafood chowder, tom yum, seafood paella, and rich seafood soups and stews.",
    recipes:[
      {id:"ss1", name:"Cioppino",servings:"6 servings",ingredients:["1 lb (450 g) firm white fish such as cod or halibut, cut into chunks","1 lb (450 g) large shrimp, peeled","1 lb (450 g) mussels, scrubbed","1 lb (450 g) clams, scrubbed","½ lb (225 g) scallops","1 large onion, diced","6 garlic cloves, minced","1 red bell pepper, diced","1 cup (240 ml) dry white wine","2 cans (28 oz each) crushed tomatoes","2 cups (480 ml) seafood or chicken broth","1 tsp dried oregano","½ tsp red pepper flakes","3 tbsp olive oil","Fresh basil and parsley","Sourdough bread to serve"],prep:"Heat olive oil in a large Dutch oven over medium heat. Cook onion and pepper until soft. Add garlic and red pepper flakes and cook 2 minutes. Add wine and reduce by half. Add crushed tomatoes, broth, and oregano. Simmer 20 minutes. Add fish and scallops — they take longest. Simmer 5 minutes. Add clams and mussels and cover. Cook 5 minutes until shells open. Add shrimp and cook 2 more minutes until pink. Discard any unopened shells. Season with salt and pepper. Garnish with basil and parsley. Serve with sourdough."},
      {id:"ss2", name:"Bouillabaisse",servings:"6 servings",ingredients:["2 lbs (900 g) mixed firm white fish — monkfish, snapper, halibut","1 lb (450 g) mussels and clams","½ lb (225 g) shrimp","Broth: 1 onion, 1 leek, 4 garlic cloves, 2 tomatoes, 1 cup white wine, 4 cups fish broth, 1 can diced tomatoes, saffron, fennel fronds, orange zest, bay leaf, thyme","Rouille: ½ cup mayo, 3 garlic cloves, 1 tsp saffron, 1 tsp paprika, 1 tbsp lemon juice","Toasted baguette slices to serve"],prep:"Make broth by sautéing onion, leek, and garlic in olive oil. Add tomatoes, wine, fish broth, saffron, fennel, orange zest, bay leaf, and thyme. Simmer 30 minutes. Strain. Return broth to pot. Bring to a rapid boil. Add fish — cook 5 minutes. Add shellfish and cook until open. Season with salt and pepper. Make rouille by blending all ingredients. Serve bouillabaisse in deep bowls with toasted baguette spread with rouille."},
      {id:"ss3", name:"Seafood Chowder",servings:"6 servings",ingredients:["1 lb (450 g) white fish, cubed","½ lb (225 g) shrimp, peeled","½ lb (225 g) scallops","6 strips bacon, diced","1 onion, diced","3 celery stalks, diced","4 potatoes, cubed","2 cups (480 ml) whole milk","1 cup (240 ml) heavy cream","3 tbsp flour","2 tbsp butter","Old Bay seasoning","Salt, white pepper, and fresh chives"],prep:"Cook bacon until crispy. Remove. Cook onion and celery in bacon fat until soft. Add flour and stir 2 minutes. Add milk gradually while stirring. Add potatoes and simmer 15 minutes. Add cream and Old Bay. Add fish, shrimp, and scallops. Cook 5–7 minutes until seafood is just cooked. Season with salt and white pepper. Serve topped with bacon and chives."},
      {id:"ss4", name:"Tom Yum Goong",servings:"4 servings",ingredients:["1 lb (450 g) large shrimp, peeled — reserve shells","4 cups (960 ml) water or light chicken broth","3 stalks lemongrass, cut and smashed","6 kaffir lime leaves, torn","4 slices galangal or ginger","3 Thai red chilies, smashed","3 tbsp fish sauce","3 tbsp lime juice","1 tsp sugar","200 g (7 oz) mushrooms, sliced","Fresh cilantro and Thai basil"],prep:"Simmer shrimp shells in water 15 minutes. Strain and return shrimp broth to pot. Add lemongrass, kaffir lime leaves, galangal, and chilies. Simmer 10 minutes to infuse. Add mushrooms and shrimp. Cook 3–4 minutes until shrimp are pink. Season with fish sauce, lime juice, and sugar — the soup should be intensely sour, salty, and spicy. Garnish with cilantro. Discard lemongrass and galangal before serving."},
      {id:"ss5", name:"Seafood Paella",servings:"6 servings",ingredients:["2 cups (400 g) short grain Spanish rice (Bomba)","1 lb (450 g) shrimp, shell on","1 lb (450 g) mussels and clams","½ lb (225 g) squid, cut into rings","4 cups (960 ml) warm seafood broth","½ tsp saffron soaked in ¼ cup warm broth","1 onion, diced","4 garlic cloves, minced","1 red bell pepper, diced","1 can (14 oz) diced tomatoes","1 tsp smoked paprika","4 tbsp olive oil","Fresh parsley and lemon to serve"],prep:"Heat olive oil in a large paella pan over medium-high heat. Cook onion and pepper until soft. Add garlic and paprika 1 minute. Add diced tomatoes and cook 3 minutes. Add rice and stir to coat 2 minutes. Add warm saffron broth. Bring to a boil. Reduce heat and cook uncovered without stirring 15 minutes. Add squid and shrimp on top. Arrange mussels and clams around the pan. Cook 8–10 minutes until rice has absorbed liquid and shellfish have opened. Let rest 5 minutes. Garnish with parsley and lemon."},
      {id:"ss6", name:"Portuguese Seafood Stew",servings:"6 servings",ingredients:["1 lb (450 g) cod or haddock, cubed","1 lb (450 g) clams","1 lb (450 g) shrimp","1 onion, diced","4 garlic cloves, minced","2 tomatoes, chopped","1 can (14 oz) diced tomatoes","1 cup (240 ml) white wine","2 cups (480 ml) fish broth","1 tsp smoked paprika","1 tsp sweet paprika","½ tsp saffron","Fresh parsley and cilantro","3 tbsp olive oil"],prep:"Heat olive oil in a large pot. Cook onion until soft. Add garlic and paprikas and cook 1 minute. Add tomatoes and cook 5 minutes. Add wine and reduce. Add broth and saffron. Simmer 15 minutes. Add clams and cover 5 minutes until they open. Add fish and shrimp and cook 5 more minutes until just cooked. Season with salt and pepper. Garnish with parsley and cilantro. Serve with crusty bread."},
      {id:"ss7", name:"Seafood Gumbo",servings:"6 servings",ingredients:["1 lb (450 g) shrimp, peeled","1 lb (450 g) crab meat","½ lb (225 g) andouille sausage, sliced","Roux: ½ cup vegetable oil, ½ cup all-purpose flour","Holy Trinity: 1 onion, 3 celery stalks, 1 green bell pepper — all diced","4 garlic cloves, minced","4 cups (960 ml) seafood or chicken broth","1 cup (240 ml) tomato juice","1 tbsp Cajun seasoning","1 tsp dried thyme","File powder","Steamed rice and green onions to serve"],prep:"Make roux by cooking oil and flour in a heavy pot over medium heat stirring constantly 20–30 minutes until dark chocolate brown — this is essential to gumbo. Add holy trinity vegetables to hot roux and cook 5 minutes. Add garlic 1 minute. Add broth and tomato juice gradually while stirring. Add sausage, Cajun seasoning, and thyme. Simmer 30 minutes. Add shrimp and crab and cook 5 more minutes. Adjust seasoning. Serve over steamed rice. Sprinkle with file powder."},
      {id:"ss8", name:"New England Fish Chowder",servings:"6 servings",ingredients:["2 lbs (900 g) firm white fish — cod or haddock, cubed","6 strips bacon, diced","1 large onion, diced","3 celery stalks, diced","4 medium potatoes, cubed","3 cups (720 ml) whole milk","1 cup (240 ml) heavy cream","2 tbsp butter","Salt, white pepper, and fresh dill","Oyster crackers to serve"],prep:"Cook bacon until crispy in a large pot. Remove. Cook onion and celery in bacon fat until soft. Add potatoes and enough water or fish broth to cover. Simmer 15 minutes until potatoes are tender. Add milk and cream and bring to a gentle simmer — do not boil. Add fish and cook 8–10 minutes until fish is flaky and cooked through. Season with salt, white pepper, and fresh dill. Serve topped with bacon and oyster crackers."},
      {id:"ss9", name:"Italian Seafood Soup (Zuppa di Pesce)",servings:"4 servings",ingredients:["1 lb (450 g) mixed fish fillets, cubed","½ lb (225 g) clams","½ lb (225 g) mussels","½ lb (225 g) shrimp","4 garlic cloves, minced","1 onion, diced","½ cup (120 ml) dry white wine","1 can (28 oz) crushed tomatoes","2 cups (480 ml) fish broth","Red pepper flakes","Fresh parsley and basil","3 tbsp olive oil","Crusty bread to serve"],prep:"Heat olive oil in a large pot. Cook onion and garlic until soft. Add red pepper flakes and cook 1 minute. Add wine and reduce. Add crushed tomatoes and broth. Simmer 15 minutes. Add clams and mussels and cover until they open. Add fish and shrimp and cook 5 minutes until just done. Discard any unopened shells. Season with salt. Garnish with parsley and basil. Serve with crusty bread."},
      {id:"ss10", name:"Korean Spicy Seafood Soup (Haemul Jeongol)",servings:"4 servings",ingredients:["Mixed seafood: shrimp, mussels, clams, squid, white fish — 2 lbs total","4 cups (960 ml) anchovy or seafood broth","3 tbsp gochujang","2 tbsp soy sauce","1 tbsp gochugaru (Korean red pepper flakes)","3 garlic cloves, minced","1-inch ginger, grated","1 block firm tofu, cubed","2 zucchini, sliced","4 green onions, cut into pieces","Sesame oil"],prep:"Combine broth, gochujang, soy sauce, gochugaru, garlic, and ginger in a large pot. Bring to a boil. Add firmer vegetables like zucchini first. Add tofu. Add seafood — firm fish first, then shellfish, then shrimp. Cover and cook 5–8 minutes until all seafood is cooked and shells have opened. Add green onions. Drizzle with sesame oil. Serve bubbling in the pot at the table."},
      {id:"ss11", name:"Shrimp and Corn Soup",servings:"4 servings",ingredients:["1 lb (450 g) shrimp, peeled","3 cups corn kernels, fresh or frozen","1 onion, diced","3 garlic cloves, minced","2 potatoes, cubed","3 cups (720 ml) chicken broth","1 cup (240 ml) heavy cream","3 tbsp butter","1 tsp smoked paprika","Salt, pepper, and fresh chives"],prep:"Cook onion in butter until soft. Add garlic and paprika 1 minute. Add potatoes and broth. Simmer 15 minutes. Add corn and blend half the soup until creamy. Return to pot. Add cream and bring to a gentle simmer. Add shrimp and cook 3–4 minutes until pink. Season with salt and pepper. Garnish with chives."},
      {id:"ss12", name:"Seafood Hot Pot",servings:"4 servings",ingredients:["Mixed seafood: shrimp, scallops, mussels, fish fillets, squid — 2 lbs total","6 cups (1.4 L) dashi or seafood broth","2 tbsp soy sauce","1 tbsp mirin","1 block firm tofu, cubed","Napa cabbage, thinly sliced","Enoki and shiitake mushrooms","Glass noodles, soaked","4 green onions","Ponzu sauce for dipping"],prep:"Prepare dipping broth by combining dashi, soy sauce, and mirin in a hot pot or large pot. Bring to a simmer at the table or on the stove. Arrange all seafood and vegetables on platters. Dip and cook items in the simmering broth — cabbage and tofu take longer while seafood and thin items cook in 1–3 minutes. Eat with ponzu dipping sauce."},
      {id:"ss13", name:"Spanish Seafood Stew (Zarzuela)",servings:"4 servings",ingredients:["1 lb (450 g) white fish, cubed","½ lb (225 g) shrimp","½ lb (225 g) mussels and clams","½ lb (225 g) squid rings","1 onion, diced","4 garlic cloves, minced","1 cup (240 ml) dry white wine","1 can (14 oz) crushed tomatoes","1 cup (240 ml) fish broth","Saffron, paprika, and cayenne","Toasted almonds ground","3 tbsp olive oil","Fresh parsley"],prep:"Heat olive oil in a cazuela or Dutch oven. Cook onion and garlic until soft. Add paprika, cayenne, and saffron. Add wine and reduce. Add crushed tomatoes and broth. Simmer 15 minutes. Add squid and fish first. Cook 5 minutes. Add shellfish and cover until shells open. Add shrimp and cook 3 more minutes. Stir in ground toasted almonds to thicken sauce. Garnish with parsley."},
      {id:"ss14", name:"Lobster Bisque with Sherry",servings:"4 servings",ingredients:["2 lobster tails — cook meat and reserve shells","1 onion, diced","2 carrots, diced","2 celery stalks, diced","4 garlic cloves, minced","3 tbsp butter","2 tbsp tomato paste","½ cup (120 ml) dry sherry","4 cups (960 ml) seafood broth","1 cup (240 ml) heavy cream","1 tsp smoked paprika","Cayenne, salt, and white pepper","Heavy cream drizzle and chives to garnish"],prep:"Simmer lobster shells with broth 25 minutes. Strain. Melt butter in a large pot. Cook vegetables until very soft. Add garlic 1 minute. Add tomato paste and paprika 2 minutes. Add sherry and cook until evaporated. Add lobster broth. Simmer 20 minutes. Blend very smooth. Strain through a fine mesh sieve for an ultra-smooth bisque. Return to pot. Add cream and simmer 5 minutes. Season with cayenne, salt, and white pepper. Dice lobster meat and add. Serve with a swirl of cream and fresh chives."},
      {id:"ss15", name:"Seafood Congee",servings:"4 servings",ingredients:["1 cup (200 g) jasmine rice","6 cups (1.4 L) seafood or chicken broth","½ lb (225 g) shrimp, peeled","½ lb (225 g) white fish, thinly sliced","1 tsp fresh ginger, grated","2 tbsp soy sauce","1 tsp sesame oil","Green onions, fresh ginger julienned, cilantro","White pepper","Fried shallots and sesame seeds to garnish"],prep:"Rinse rice. Combine with broth in a large pot. Bring to a boil. Reduce to low heat and simmer uncovered 45–60 minutes stirring occasionally until rice breaks down into a thick creamy porridge. Add more broth if too thick. Add ginger, soy sauce, and sesame oil. Add thinly sliced fish and shrimp and cook gently 3–5 minutes until just cooked. Season with white pepper. Serve topped with green onions, julienned ginger, cilantro, fried shallots, and sesame seeds."}
    ]
  }

];

// ================================================================
//  TOGGLE CATEGORY
// ================================================================
function toggleCategory(catId) {
  var ul = document.getElementById(catId);
  if (!ul) return;
  if (ul.style.display === 'block') { ul.style.display = 'none'; return; }
  var cat = seafoodData.find(function(c) { return c.id === catId; });
  if (!cat) return;
  if (ul.innerHTML === '') {
    cat.recipes.forEach(function(recipe) {
      var li = document.createElement('li');
      li.className = 'browser-item';
      li.innerHTML = '<span class="browser-item-name">' + recipe.name + '</span><span class="browser-item-arrow">›</span>';
      li.addEventListener('click', function() { openRecipeModal(recipe, catId); });
      ul.appendChild(li);
    });
  }
  ul.style.display = 'block';
}

// ================================================================
//  RECIPE MODAL
// ================================================================
function openRecipeModal(recipe, catId) {
  var modal = document.getElementById('recipeModal');
  var title = document.getElementById('recipeModalTitle');
  var body  = document.getElementById('recipeModalBody');
  title.textContent = recipe.name;
  body.innerHTML = buildDetailHTML(recipe, catId);
  modal.style.display = 'flex';
}
function closeRecipeModal() {
  document.getElementById('recipeModal').style.display = 'none';
}

// ================================================================
//  BUILD DETAIL HTML
// ================================================================
function buildDetailHTML(recipe, catId) {
  var ingredientItems = recipe.ingredients.map(function(ing) { return '<li>' + ing + '</li>'; }).join('');
  return '' +
    '<div class="sub-heading">Servings</div>' +
    '<p class="toc-text">' + recipe.servings + '</p>' +
    '<div class="sub-heading">Ingredients</div>' +
    '<ul class="recipe-ingredients">' + ingredientItems + '</ul>' +
    '<div class="sub-heading">Preparation</div>' +
    '<p class="recipe-prep">' + recipe.prep + '</p>' +
    '<div class="recipe-actions">' +
      '<button class="btn-gold" onclick="saveToFavorites(\'' + recipe.name.replace(/'/g, "\\'") + '\', \'' + catId + '\')">♡ Save to Favorites</button>' +
    '</div>';
}

// ================================================================
//  SAVE TO FAVORITES
// ================================================================
function saveToFavorites(recipeName, catId) {
  var cat = seafoodData.find(function(c) { return c.id === catId; });
  if (!cat) return;
  var recipe = cat.recipes.find(function(r) { return r.name === recipeName; });
  if (!recipe) return;
  try {
    var favs = JSON.parse(localStorage.getItem('mealplanner_favorites') || '[]');
    var exists = favs.find(function(f) { return f.name === recipeName; });
    if (!exists) {
      favs.push({ name: recipe.name, catName: cat.name, ingredients: recipe.ingredients, prep: recipe.prep });
      localStorage.setItem('mealplanner_favorites', JSON.stringify(favs));
      alert('"' + recipeName + '" saved to favorites!');
    } else {
      alert('"' + recipeName + '" is already in your favorites.');
    }
  } catch(e) {
    alert('"' + recipeName + '" saved!');
  }
}
